### ISSUE TITLE
Compiling Error #2

### ISSUE THREAD

**Issue by Tekameikite** [BEEmod/BEE2.4#1003]
VRAD failed.

[I] vrad.main(): BEE2 VRAD hook started!
[I] vrad.main(): Map path is F:\Steam\steamapps\common\Portal 2\sdk_content\maps\preview.bsp
[I] vrad.load_config(): Loading Settings...
[I] vrad.load_config(): Config Loaded!
[I] vrad.main(): Final status: is_peti=True, edit_args=True
[I] vrad.main(): Reading BSP
[I] vrad.main(): Done!
[I] vrad.main(): Reading our FGD files...
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vrad.py", line 865, in <module>
  File "vrad.py", line 758, in main
  File "F:\Git\srctools\srctools\packlist.py", line 379, in load_soundscript_manifest
  File "F:\Git\srctools\srctools\property_parser.py", line 378, in parse
srctools.property_parser.KeyValError: End of text reached with remaining open sections.

File ended with at least one property that didn't have an ending "}".
Error occurred with file "F:\Steam\steamapps\common\Portal 2\bin\bee2\sndscript_cache.vdf".
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vrad.py", line 865, in <module>
  File "vrad.py", line 758, in main
  File "F:\Git\srctools\srctools\packlist.py", line 379, in load_soundscript_manifest
  File "F:\Git\srctools\srctools\property_parser.py", line 378, in parse
srctools.property_parser.KeyValError: End of text reached with remaining open sections.

File ended with at least one property that didn't have an ending "}".
Error occurred with file "F:\Steam\steamapps\common\Portal 2\bin\bee2\sndscript_cache.vdf".

**Comment by TeamSpen210** [comment]
Delete that file mentioned at the end, it'll regenerate.
