### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by Miguelangelgb** [BEEmod/BEE2.4#1008]
Hello, I started using Beemod since last winter and it worked very well. But several months ago the compilation fails. I have been installing the new versions but it still does not work. I have also followed these steps: https://github.com/BEEmod/BEE2-items/wiki/Updating-Beemod
It doesn't work either.

This is the message of the console:

VBSP failed.

Traceback (most recent call last):
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 20, in <module>
zipimport.ZipImportError: not a Zip file

Any solution, please? Thank you

**Comment by LautaroL20** [comment]
Try out the latest pre-release.
