### ISSUE TITLE
Traceback Error

### ISSUE THREAD

**Issue by MeloettaRules28** [BEEmod/BEE2.4#1033]
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\UI.py", line 806, in export_editoritems
  File "F:\Git\BEE2.4\src\gameMan.py", line 792, in export
  File "F:\Git\BEE2.4\src\gameMan.py", line 860, in clean_editor_models
ZeroDivisionError: division by zero

I don't exactly know what happened, neither know if it's the Items or App, so I'll just post it in the app part.

**Comment by MeloettaRules28** [comment]
Nevermind, I just had to re-export, sorry for creating this issue for nothing!
