### ISSUE TITLE
I got this message when i try to select music

### ISSUE THREAD

**Issue by wimklaver** [BEEmod/BEE2.4#1042]
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\sound.py", line 200, in play_sample
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\media\__init__.py", line 1429, in load
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\media\__init__.py", line 1405, in load
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\media\avbin.py", line 238, in __init__
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\media\avbin.py", line 196, in f
OSError: exception: access violation reading 0x00000000

**Comment by Luke18033** [comment]
This has already been reported *many* times. Use Pr31, open the music files yourself, or just don't preview music until the issue is fixed.
