### ISSUE TITLE
BEE2.4 v4.33.0 Won't Launch at All

### ISSUE THREAD

**Issue by calclover2514** [BEEmod/BEE2.4#1052]
Every time the newest version of BEE2 launches, it quits with this error
```
An error occurred: 
Traceback (most recent call last):
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\__init__.py", line 378, in __getattr__
AttributeError: 'NoneType' object has no attribute 'EventDispatcher'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2_launch.pyw", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "F:\Git\BEE2.4\src\BEE2.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "F:\Git\BEE2.4\src\UI.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "F:\Git\BEE2.4\src\music_conf.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "F:\Git\BEE2.4\src\SubPane.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "F:\Git\BEE2.4\src\sound.py", line 52, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\media\__init__.py", line 82, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\media\player.py", line 48, in <module>
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\__init__.py", line 384, in __getattr__
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\event.py", line 139, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\past\__init__.py", line 88, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\past\translation\__init__.py", line 42, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\lib2to3\refactor.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\lib2to3\fixer_util.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\lib2to3\pygram.py", line 32, in <module>
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\lib2to3\pgen2\driver.py", line 124, in load_grammar
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\lib2to3\pgen2\pgen.py", line 385, in generate_grammar
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\lib2to3\pgen2\pgen.py", line 15, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\Portal 2 BEE2 Editor\\BEE2_4.33.0_win\\bin\\python36.zip\\lib2to3\\Grammar.txt'
```
`Grammar.txt`  appears to be missing from `python36.zip`.

**Comment by snorepion** [comment]
@TeamSpen210 I'm receiving a similar crash upon startup, although the current stable release was working perfectly fine earlier today. Portal 2 is not open and I've tried restarting as well as verifying the integrity of the game files, none of which have worked
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2_launch.pyw", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "F:\Git\BEE2.4\src\BEE2.py", line 98, in <module>
  File "F:\Git\BEE2.4\src\packageLoader.py", line 419, in load_packages
  File "F:\Git\BEE2.4\src\packageLoader.py", line 331, in find_packages
  File "F:\Git\srctools\srctools\filesys.py", line 97, in open_ref
  File "F:\Git\srctools\srctools\filesys.py", line 567, in _create_ref
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\zipfile.py", line 1100, in __init__
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\zipfile.py", line 1167, in _RealGetContents
zipfile.BadZipFile: File is not a zip file
```

**Comment by TeamSpen210** [comment]
That implies one of the package zips is corrupt.
