### ISSUE TITLE
"Failed to exacute script BEE2_launch"

### ISSUE THREAD

**Issue by Goombassador** [BEEmod/BEE2.4#1118]
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\BEE2_launch.pyw", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "F:\Git\BEE2.4\src\BEE2.py", line 82, in <module>
  File "F:\Git\BEE2.4\src\gameMan.py", line 1335, in load
  File "F:\Git\BEE2.4\src\gameMan.py", line 369, in edit_gameinfo
  File "F:\Git\BEE2.4\src\gameMan.py", line 311, in dlc_priority
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:/SteamLibrary/steamapps/common/Portal 2'

**Comment by Goombassador** [comment]
I think i've fixed it myself, but I am not sure.

**Comment by Goombassador** [comment]
Fixed.
