### ISSUE TITLE
I have this error:

### ISSUE THREAD

**Issue by TANER05** [BEEmod/BEE2.4#1156]
When I open the .exe this happens:

Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\BEE2_launch.pyw", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "F:\Git\BEE2.4\src\BEE2.py", line 73, in <module>
  File "F:\Git\BEE2.4\src\gameMan.py", line 1410, in load
  File "F:\Git\BEE2.4\src\gameMan.py", line 398, in edit_gameinfo
  File "F:\Git\BEE2.4\src\gameMan.py", line 340, in dlc_priority
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'G:/SteamLibrary/steamapps/common/Portal 2'

I have extracted the packages.

**Comment by ENDERZOMBI102** [comment]
the path to portal 2 is wrong

**Comment by TANER05** [comment]
> the path to portal 2 is wrong

I can't open the .exe

**Comment by ENDERZOMBI102** [comment]
Try reinstalling,ù

**Comment by ENDERZOMBI102** [comment]
Reopen bee and selecting the "Portal2.exe" file and clicking "open"

**Comment by ENDERZOMBI102** [comment]
in case try putting bee in the SAME drive, or folder

**Comment by TANER05** [comment]
I have reinstalled BEE2, did the things, and  when I open the .exe, this shows up. I can't select the directory, nothing opens. And I don't have a SteamLibrary folder in any of my drives.

**Comment by calclover2514** [comment]
I had this problem as well when I changed a drive letter.
I fixed it by simply deleting the file `%AppData%\BEEMOD2\config\games.cfg`.
Then, when you run BEE2, it will prompt you for the .exe file.

**Comment by TANER05** [comment]
Ok, thanks.

**Comment by Konclan** [comment]
Whats the issue here?

**Comment by TeamSpen210** [comment]
If the game directories in the config were moved or otherwise made inaccessible, the app crashes super early and so doesn't allow you to remove them.
