### ISSUE TITLE
Broken basemodui.txt file in P2 Splitscreen update

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [BEEmod/BEE2.4#1207]
[bee2.log](https://github.com/BEEmod/BEE2.4/files/3872497/bee2.log)
```
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\BEE2_launch.pyw", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "F:\Git\BEE2.4\src\BEE2.py", line 110, in <module>
  File "F:\Git\BEE2.4\src\gameMan.py", line 1137, in init_trans
  File "F:\Git\BEE2.4\src\gameMan.py", line 1184, in load_trans
  File "F:\Git\srctools\srctools\property_parser.py", line 395, in parse
srctools.property_parser.KeyValError: End of text reached with remaining open sections.

File ended with at least one property that didn't have an ending "}".
Error occurred with file "basemodui.txt".
```
Error window copied the above traceback to my clipboard.

Fresh install, first launch. The fix listed in #927 didn't help. I'd try and fix it myself, but I can't even _find_ `basemodui.txt`.

[The actual popup](https://user-images.githubusercontent.com/14184826/69298403-b9225600-0bdb-11ea-92d5-36a31ef45eac.png)

**Comment by TeamSpen210** [comment]
Valve messed up a file with invalid syntax - so BEE crashes since it is a broken file.
Go into `Portal 2/portal2_dlc2/resource/basemodui_{yourlang}.txt`, then add a second }  so there's two at the end of the file.

I'll fix this by being more forgiving in my code.

**Comment by SIGSTACKFAULT** [comment]
🎉

**Comment by GolfinhoVoador** [comment]
This also happens on windows.
