### ISSUE TITLE
Bee2.4 won't launch correctly

### ISSUE THREAD

**Issue by MrPokemon11** [BEEmod/BEE2.4#1221]
When I tried starting Bee2.4 I got this error. anyone know how to remedy this? I can't figure out what I need to do from just this error log. not sure of the version of Bee2.4 i am using. I'm using Windows 10 if that helps. Any help is appreciated. Thank you!

> Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\BEE2_launch.pyw", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "F:\Git\BEE2.4\src\BEE2.py", line 119, in <module>
  File "F:\Git\BEE2.4\src\gameMan.py", line 1081, in init_trans
  File "F:\Git\BEE2.4\src\gameMan.py", line 1109, in load_trans
  File "F:\Git\srctools\srctools\property_parser.py", line 381, in parse
srctools.property_parser.KeyValError: End of text reached with remaining open sections.
File ended with at least one property that didn't have an ending "}".
Error occurred with file "basemodui.txt".

**Comment by Flash4433** [comment]
That bug came from a recent update for Portal 2 that broke BEE2, download the latest fix and it should be fixed.

**Comment by LautaroL20** [comment]
This is an issue that has been solved since a week ago with the latest Beemod´s release (PRL4.36.1) and you can download it from there, below:

https://github.com/BEEmod/BEE2.4/releases/tag/2.4.36.1_ (Interface)
https://github.com/BEEmod/BEE2-items/releases/tag/v4.36.0 (Packages)

Enjoy!
