### ISSUE TITLE
Error when attempting to load Bee 2.4.0

### ISSUE THREAD

**Issue by classictourneys** [BEEmod/BEE2.4#1230]
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2.pyw", line 139, in <module>
  File "F:\Git\BEE2.4\src\gameMan.py", line 788, in init_trans
  File "F:\Git\srctools\srctools\property_parser.py", line 418, in parse
srctools.property_parser.KeyValError: End of text reached with remaining open sections.
Error occured with file "basemodui.txt"

**Comment by TeamSpen210** [comment]
Update BEEmod to the current version.
