### ISSUE TITLE
Unicode error when parsing files causes crash

### ISSUE THREAD

**Issue by MrJasonRus** [BEEmod/BEE2.4#1282]
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\BEE2_launch.pyw", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "F:\Git\BEE2.4\src\BEE2.py", line 113, in <module>
  File "F:\Git\BEE2.4\src\UI.py", line 2047, in init_windows
  File "F:\Git\BEE2.4\src\BEE2_config.py", line 61, in read_settings
  File "F:\Git\srctools\srctools\property_parser.py", line 246, in parse
  File "srctools\_tokenizer.pyx", line 272, in srctools._tokenizer.Tokenizer.__call__
  File "srctools\_tokenizer.pyx", line 288, in srctools._tokenizer.Tokenizer.next_token
  File "srctools\_tokenizer.pyx", line 237, in srctools._tokenizer.Tokenizer._next_char
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\codecs.py", line 321, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcb in position 2182: invalid continuation byte

**Comment by CheezyPig** [comment]
What exactly were you doing when this happened? What version of the App and Packages are you using?

**Comment by TeamSpen210** [comment]
Somehow the settings file has become corrupt. Open a Windows Explorer window, and type in `%appdata%` into the address bar at the top. Then go to `BEEMOD/config/`, and attach `config.vdf` here so I can have a look at it (you might need to rename it to `txt` or zip it for GitHub to accept it). You'll then want to delete it to make BEE2 use the default settings.

**Comment by MrJasonRus** [comment]
[config.txt](https://github.com/BEEmod/BEE2.4/files/4432843/config.txt)

**Comment by TeamSpen210** [comment]
Thanks! Narrowed down the problem here.
