### ISSUE TITLE
It keeps giving me errors after I start it.

### ISSUE THREAD

**Issue by GorganFreemad** [BEEmod/BEE2.4#1292]
[D] BEE2.<module>(): Loading settings...
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\BEE2_launch.pyw", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "F:\Git\BEE2.4\src\BEE2.py", line 73, in <module>
  File "F:\Git\BEE2.4\src\gameMan.py", line 1415, in load
  File "F:\Git\BEE2.4\src\gameMan.py", line 437, in edit_gameinfo
  File "F:\Git\srctools\srctools\__init__.py", line 333, in __exit__
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2\\portal2_dlc2\\tmp_11' -> 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2\\portal2_dlc2\\gameinfo.txt'

I don't know why but this keeps happening and they are all errors.

**Comment by Flash4433** [comment]
Since you closed it you fixed it?... Anyways it's probably because you had Portal 2 or even Hammer running.
