### ISSUE TITLE
Teach config files to use Windows environment variables

### ISSUE THREAD

**Issue by metaa** [BEEmod/BEE2.4#1311]
I add my BEEMOD2 configurations to Git repositories along with the map files, so I can always jump to a map and edit it with the correct configuration, however there is one setting that has an absolute path that would make it impossible to use the exact same configuration on another machine / user.

In `%APPDATA%\BEEMOD2\config\compile.cfg` there is this bit of configuration:
```ini
[Screenshot]
loc = C:\Users\Username\AppData\Roaming\BEEMOD2\screenshot.jpg
```
In order to make it work independently of my machine / user, I changed this to
```ini
[Screenshot]
loc = %APPDATA%\BEEMOD2\screenshot.jpg
```
but that would then throw an exception, because apparently the config parser does not take Windows environment variables into account (`%APPDATA%` would usually resolve to `C:\Users\Username\AppData\Roaming`).

Here's the error report:
```
---------------------------
BEE2 Error!
---------------------------
An error occurred: 
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\BEE2_launch.pyw", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "F:\Git\BEE2.4\src\BEE2.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "F:\Git\BEE2.4\src\UI.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "F:\Git\BEE2.4\src\CompilerPane.py", line 100, in <module>
  File "F:\Git\BEE2.4\src\BEE2_config.py", line 185, in get_val
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\configparser.py", line 1231, in __getitem__
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\configparser.py", line 797, in get
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\configparser.py", line 393, in before_get
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\configparser.py", line 443, in _interpolate_some
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%APPDATA%\\BEEMOD2\\screenshot.jpg'
```

Can we add support for Windows environment variables here? (it doesn't even need to *save* it with `%APPDATA%` upon selecting a new one, that could be handled manually even).

**Comment by TeamSpen210** [comment]
Actually that option is fairly useless now, since as you can see it's always set to `%APPDATA%/BEEMOD2/screenshot.jpg`. So I should just compute that in the compiler.
