### ISSUE TITLE
Exporting Palette error/crash

### ISSUE THREAD

**Issue by PortalusMaximus** [BEEmod/BEE2.4#1317]
When I try to make a palette and export items, I get the following error:

Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\UI.py", line 852, in export_editoritems
  File "F:\Git\BEE2.4\src\gameMan.py", line 871, in export
  File "F:\Git\BEE2.4\src\gameMan.py", line 549, in refresh_cache
  File "F:\Git\srctools\srctools\filesys.py", line 69, in open_bin
  File "F:\Git\srctools\srctools\filesys.py", line 276, in open_bin
  File "F:\Git\srctools\srctools\filesys.py", line 69, in open_bin
  File "F:\Git\srctools\srctools\filesys.py", line 477, in open_bin
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Steam\\steamapps\\common\\Portal 2\\BEE2_4.36.1_win\\packages\\BEE2-items-master\\BEE2-items-master\\packages\\Lautaro\\left_middle_right_ped_buttons\\resources\\materials\\models\\props_map_editor\\palette\\Lautaro\\pedestal_button_left_middle_right\\bts\\pedestal_button_combined.vtf'

**Comment by LautaroL20** [comment]
Like Flash4433 said, try installing BEE2 in a separated folder instead of the Portal 2 folder, otherwise issues like this can happen. Also, make sure to get the latest version of BEE2.
