### ISSUE TITLE
Can't Launch Bee2

### ISSUE THREAD

**Issue by Kevin-Blacktalon** [BEEmod/BEE2.4#1329]
Upon launching the application, I receive an error message followed by an immediate crash.
The message is as follows:
**_**_`Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\BEE2_launch.pyw", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "F:\Git\BEE2.4\src\BEE2.py", line 73, in <module>
  File "F:\Git\BEE2.4\src\gameMan.py", line 1415, in load
  File "F:\Git\BEE2.4\src\gameMan.py", line 437, in edit_gameinfo
  File "F:\Git\srctools\srctools\__init__.py", line 333, in __exit__
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2\\portal2_dlc2\\tmp_18' -> 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2\\portal2_dlc2\\gameinfo.txt'
`_**_**
I know nothing about programming and I'm unsure if this was the result of a legitimate issue with the application, a failure to follow installation instructions, an issue with my computer, or something else I'm overlooking.

**Comment by A-PENCIL-SHARPENER** [comment]
This seems like a permission error to me...

**Comment by Luke18033** [comment]
Try restarting your computer, Windows thinks there's still a program accessing that file for some reason.

**Comment by Kevin-Blacktalon** [comment]
Thanks for the assistance.
