### ISSUE TITLE
Experiencing a strange crash that I couldn't find documented elsewhere.

### ISSUE THREAD

**Issue by Luvvly9518** [BEEmod/BEE2.4#1364]
It came with an error message that read the following : 
```
Traceback (most recent call last):

  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load

  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible

  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>

  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load

  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible

  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>

  File "BEE2.pyw", line 139, in <module>

  File "F:\Git\BEE2.4\src\gameMan.py", line 788, in init_trans

  File "F:\Git\srctools\srctools\property_parser.py", line 418, in parse

srctools.property_parser.KeyValError: End of text reached with remaining open sections.
Error occured with file "basemodui.txt"


```
As far as I'm aware, I have the correct installation(s), although if I don't, it'd be helpful to point me the right way.

**Comment by Luke18033** [comment]
I highly doubt that you actually looked around to see if this was documented anywhere, given that there have been at least 10 other issues about it and it's in the FAQ. You need to update to 4.36.0 or later, or add a single `}` at the end of that file.
