### ISSUE TITLE
[Dev instructions] compiler directory not seen by bee2

### ISSUE THREAD

**Issue by GiovanH** [BEEmod/BEE2.4#1372]
After uninstalling and reinstalling BEE from Portal 2, exporting to Portal 2 still skips copying the compiler, even though the installed compiler is still the vanilla one. Thus, trying to compile a styled puzzle leads to errors like `Could not open instance file instances/BEE2/50s/sphere_sp/door_frame_black.vmf`.

There's a logical issue here, but it might also be good to be able to force BEE2 to copy the compilers.

**Comment by GiovanH** [comment]
I am actually having a surprisingly hard time getting the custom compiler reinstalled at all. Copying the compiler folder manually doesn't work, as building puzzles just gives an error:

```
connections.gen_item_outputs(): Item IO generated.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_QUARTER", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_HALF", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_THREE_QUARTER", which is no longer used.
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[W] instanceLocs.get_subitems(): Invalid custom instance name - "single" for <item_rail_platform> (Valid: {'static': 'instances/bee2/50s/items/track/static.vmf'})
[E] cond.core.check_all(): Error in <BEE2_OLD_AP>/items/mandatory/50s/entry_door:
Traceback (most recent call last):
  File "precomp\conditions\__init__.py", line 523, in check_all
  File "precomp\conditions\__init__.py", line 312, in test
  File "precomp\conditions\__init__.py", line 301, in test_result
  File "<string>", line 1, in <lambda>
  File "precomp\conditions\addInstance.py", line 142, in res_cave_portrait
TypeError: res_add_overlay_inst() missing 1 required positional argument: 'res'
```

I assume this is because you can't just copy the compiler folder manually, but I also can't get BEE2 to copy it properly.

**Comment by TeamSpen210** [comment]
Ah, I must have broken that condition.

**Comment by TeamSpen210** [comment]
Compiler copying always occurs, do you have it compiled and saved in `compiler/` for it to copy over?

**Comment by GiovanH** [comment]
I built developer versions of everything myself, so I'm running BEE2 out of `BEE2.4\dist\BEE2` with compilers at `BEE2.4\dist\compiler`.

When I export, I get this in the log:

```
[I] BEE2.<module>(): UI initialised!
[I] gameMan.export(): --------------------
[I] gameMan.export(): Exporting Items and Style for "PORTAL 2"!
[I] gameMan.export(): Style = BEE2_1950s
[I] gameMan.export(): Music = {<MusicChannel.BASE: 'base'>: <Music VALVE_CONTROL_GROUP>, <MusicChannel.TBEAM: 'tbeam'>: <Music VALVE_TEST>, <MusicChannel.BOUNCE: 'bouncegel'>: <Music VALVE_FRIENDLY_FAITH_PLATE>, <MusicChannel.SPEED: 'speedgel'>: <Music VALVE_GEL_REUNION>}
[I] gameMan.export(): Skybox = BEE2_SPHERE_INTERIOR
[I] gameMan.export(): QuotePack = BEE2_CAVE_50s
[I] gameMan.export(): Elevator = None
[I] gameMan.export(): Item = [('ITEM_BUTTON_PEDESTAL', 0), ('ITEM_BUTTON_FLOOR', 0), ('ITEM_CUBE', 0), ('ITEM_PAINT_SPLAT', 3), ('ITEM_TBEAM', 0), ('ITEM_CATAPULT', 0), ('ITEM_PANEL_STAIRS', 0), ('ITEM_BARRIER_HAZARD', 0), ('ITEM_LIGHT_BRIDGE', 0), ('ITEM_PISTON_PLATFORM', 0), ('ITEM_RAIL_PLATFORM', 0), ('ITEM_LASER_EMITTER_CENTER', 0), ('ITEM_LASER_CATCHER_CENTER', 0), ('ITEM_LASER_RELAY_CENTER', 0), ('ITEM_BARRIER', 0), ('ITEM_PANEL_CLEAR', 0), ('ITEM_PANEL_ANGLED', 0), ('ITEM_PANEL_FLIP', 0), ('ITEM_GOO', 0), ('ITEM_TURRET', 0), ('DOOR', 0), ('ITEM_TSPEN_SP_CHECKPOINT', 0), ('ITEM_LIGHT_PANEL', 0), ('ITEM_SECONDARY_OBSERVATION_ROOM', 0), ('ITEM_LOGIC_GATE', 0), ('ITEM_TRIGGERS', 0), ('ITEM_AUTOPORTAL', 0), ('ITEM_BEE2_PORTALGUN', 0), ('ITEM_PORTAL_MAGNET', 0), ('ITEM_BEE2_SPECIAL_MARKER', 0), ('ITEM_BEE2_CATWALK', 0), ('ITEM_TSPEN_BUTTON_PEDESTAL_RETRACT', 0)]
[I] gameMan.export(): StyleVar = {'DoorCameras': True, 'RestartOnExit': True, 'MultiverseCave': True, 'FixFizzlerBump': False, 'NoMidVoices': False, 'UnlockDefault': False, 'AllowGooMist': True, 'FunnelAllowSwitchedLights': True, 'EnableShapeSignageFrame': True}
[I] gameMan.export(): Signage = [('3', 'SIGN_NUM_1'), ('4', 'SIGN_NUM_2'), ('5', 'SIGN_NUM_3'), ('6', 'SIGN_NUM_4'), ('7', 'SIGN_EXIT'), ('8', 'SIGN_CUBE_DROPPER'), ('9', 'SIGN_BALL_DROPPER'), ('10', 'SIGN_REFLECT_CUBE'), ('11', 'SIGN_GOO_TOXIC'), ('12', 'SIGN_TBEAM'), ('13', 'SIGN_TBEAM_POLARITY'), ('14', 'SIGN_LASER_RELAY'), ('15', 'SIGN_TURRET'), ('16', 'SIGN_LIGHT_BRIDGE'), ('17', 'SIGN_PAINT_BOUNCE'), ('18', 'SIGN_PAINT_SPEED')]
[W] gameMan.export(): No compiler files!
[I] gameMan.export(): Should refresh: True
[I] packageLoader.is_stale(): Need to extract resources - APERTURE_TAG_ITEMS is unzipped!
[I] gameMan.export(): Cache invalid - copying..
[I] gameMan.export(): Exporting "Item"
[I] gameMan.export(): Exporting "ItemConfig"
[I] gameMan.export(): Exporting "QuotePack"
[I] packageLoader.export(): Voice conf path: C:\Users\Gio\AppData\Roaming\BEEMOD2\config\voice\BEE2_CAVE_50s.cfg
[I] packageLoader.export(): No normal voice config!
[I] packageLoader.export(): Voice conf path: C:\Users\Gio\AppData\Roaming\BEEMOD2\config\voice\MID_BEE2_CAVE_50s.cfg
[I] packageLoader.export(): No MidChamber voice config!
[I] packageLoader.export(): Voice conf path: C:\Users\Gio\AppData\Roaming\BEEMOD2\config\voice\RESP_BEE2_CAVE_50s.cfg
[I] packageLoader.export(): No Responses voice config!
[I] gameMan.export(): Exporting "Skybox"
[I] gameMan.export(): Exporting "Music"
[I] gameMan.export(): Exporting "Signage"
[W] packageLoader._serialise(): No valid "BEE2_1950s" style for "SIGN_REFLECTION_DROPPER" signage!
[W] packageLoader._serialise(): No valid "BEE2_1950s" style for "SIGN_NO_DRINK" signage!
[I] gameMan.export(): Exporting "StyleVar"
[I] gameMan.export(): Exporting "StyleVPK"
[I] packageLoader.export(): Sound cache: d:\steamlibrary\steamapps\common\portal 2\portal2_dlc3\maps\soundcache\_master.cache
[I] packageLoader.export(): Written 70 files to VPK!
[I] gameMan.export(): Exporting "Elevator"
[I] gameMan.export(): Exporting "PackList"
[I] packageLoader.export(): Writing packing list!
[I] gameMan.export(): Exporting "EditorSound"
[I] gameMan.export(): Exporting "BrushTemplate"
[I] gameMan.export(): Exporting "ConfigGroup"
[I] BEE2_config.save(): Saving changes in config "C:\Users\Gio\AppData\Roaming\BEEMOD2\config\item_cust_configs.cfg"!
[I] gameMan.export(): bin/vbsp.exe: normal=Valve, backup=Valve
[I] gameMan.export(): Backing up original Windows VBSP!
[I] gameMan.export(): bin/vrad.exe: normal=Valve, backup=Valve
[I] gameMan.export(): Backing up original Windows VRAD!
[I] gameMan.export(): bin/vbsp_osx: normal=Valve, backup=Valve
[I] gameMan.export(): Backing up original OSX VBSP!
[I] gameMan.export(): bin/vrad_osx: normal=Valve, backup=Valve
[I] gameMan.export(): Backing up original OSX VRAD!
[I] gameMan.export(): bin/vbsp_linux: normal=Valve, backup=Valve
[I] gameMan.export(): Backing up original Linux VBSP!
[I] gameMan.export(): bin/vrad_linux: normal=Valve, backup=Valve
[I] gameMan.export(): Backing up original Linux VRAD!
[I] gameMan.export(): Editing Gameinfo...
[I] gameMan.export(): Adding ents to FGD.
[I] gameMan.export(): Writing instance list...
[I] gameMan.export(): Writing Editoritems...
[I] gameMan.export(): Writing VBSP Config!
[I] gameMan.export(): Copying Resources!
[I] gameMan.refresh_cache(): Cache copied.
[I] gameMan.refresh_cache(): Deleting: d:\steamlibrary\steamapps\common\portal 2\bee2\materials\bee2\fizz_sides\side_color_06a31a.vmt
[I] gameMan.refresh_cache(): Deleting: d:\steamlibrary\steamapps\common\portal 2\bee2\materials\bee2\fizz_sides\side_color_0d6699.vmt
[I] gameMan.refresh_cache(): Deleting: d:\steamlibrary\steamapps\common\portal 2\bee2\materials\bee2\fizz_sides\side_color_1a3366.vmt
[I] gameMan.refresh_cache(): Deleting: d:\steamlibrary\steamapps\common\portal 2\bee2\materials\bee2\fizz_sides\side_color_323232.vmt
[I] gameMan.refresh_cache(): Deleting: d:\steamlibrary\steamapps\common\portal 2\bee2\materials\bee2\fizz_sides\side_color_4c1a66.vmt
[I] gameMan.refresh_cache(): Deleting: d:\steamlibrary\steamapps\common\portal 2\bee2\materials\bee2\fizz_sides\side_color_4c260a.vmt
[I] gameMan.refresh_cache(): Deleting: d:\steamlibrary\steamapps\common\portal 2\bee2\materials\bee2\fizz_sides\side_color_999926.vmt
[I] gameMan.refresh_cache(): Deleting: d:\steamlibrary\steamapps\common\portal 2\bee2\materials\bee2\fizz_sides\side_color_e61a1a.vmt
[I] BEE2_config.save(): Saving changes in config "C:\Users\Gio\AppData\Roaming\BEEMOD2\config\games.cfg"!
[I] gameMan.export(): Optimizing editor models...
[I] gameMan.clean_editor_models(): 258/502 (51%) editor models used.
[I] paletteLoader.save(): Saving "<Last Export>"!
[I] BEE2_config.save(): Saving changes in config "C:\Users\Gio\AppData\Roaming\BEEMOD2\config\config.cfg"!

```

which includes a relevant-seeming `[W] gameMan.export(): No compiler files!` warning.

**Comment by GiovanH** [comment]
Copying `BEE2.4\dist\compiler` to `BEE2.4\dist\BEE2\compiler` seems to fix it, so this is a dev environment thing.

**Comment by GiovanH** [comment]
After pulling in https://github.com/BEEmod/BEE2.4/commit/e6c01baa0e5073aea9f973ba0d36b7935211848a I'm getting this error: https://github.com/BEEmod/BEE2.4/issues/1373. Not sure if it might be related?

(Sorry for *actually* mixing up two bugs in one issue this time.)

**Comment by Luke18033** [comment]
I don't think there's an actual issue here
