### ISSUE TITLE
Can't open Mac versions! (HELP!)

### ISSUE THREAD

**Issue by ThaFeeesh** [BEEmod/BEE2.4#1422]
Using the older, Mac-compatible versions.

An error occurred:
Traceback (most recent call last):
File "BEE2_launch.pyw", line 23, in
File "", line 971, in _find_and_load
File "", line 955, in _find_and_load_unlocked
File "", line 665, in _load_unlocked
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
File "BEE2.py", line 119, in
File "gameMan.py", line 1081, in init_trans
File "gameMan.py", line 1109, in load_trans
File "site-packages/srctools-1.2.0-py3.6-macosx-10.9-x86_64.egg/srctools/property_parser.py", line 381, in parse
srctools.property_parser.KeyValError: End of text reached with remaining open sections.

File ended with at least one property that didn't have an ending "}".
Error occurred with file "basemodui.txt".

This has been copied to the clipboard.

Please help!

(ps. this is a repost because someone closed the last issue before it was solved.)

**Comment by FrozenDragon0** [comment]
Duplicate. You can easily reopen the last issue: https://github.com/BEEmod/BEE2.4/issues/1418
