### ISSUE TITLE
Error when exporting

### ISSUE THREAD

**Issue by Koyot3** [BEEmod/BEE2.4#1436]
I'm currently running BEEMOD 4.37.0
BEEmod error's when exporting I tried redownloading everything and starting over but it always gives me this error log.

Traceback (most recent call last):
  File "F:\Git\srctools\srctools\property_parser.py", line 728, in __getitem__
  File "F:\Git\srctools\srctools\property_parser.py", line 477, in _get_value
srctools.property_parser.NoKeyError: No key pos1!

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\gameMan.py", line 1024, in build_instance_data
  File "F:\Git\srctools\srctools\property_parser.py", line 730, in __getitem__
IndexError: No key pos1!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\UI.py", line 851, in export_editoritems
  File "F:\Git\BEE2.4\src\gameMan.py", line 805, in export
  File "F:\Git\BEE2.4\src\gameMan.py", line 1036, in build_instance_data
ValueError: Bad EmbeddedVoxel data in item ITEM_BEE2_NEUROTOXIN_VENT!

**Comment by LautaroL20** [comment]
> Koyot3 said: "I'm currently running BEEMOD 4.37.0"

According to the log you have posted, the issue you were having is most likely fixed in the latest BEE2 release as I did not see anyone having problems while trying to export the Neurotoxin item to the game. So, please get the latest version of the application & packages and then if the issue still exists, let us know and we will re-open the issue.
