### ISSUE TITLE
bee2.4 keeps crashing everytime i try to configure signage

### ISSUE THREAD

**Issue by thedeathiscoming** [BEEmod/BEE2.4#1462]
it wont work, it leaves me with this error message 
Traceback (most recent call last):
  File "app\dragdrop.py", line 545, in _evt_hover_enter
  File "app\dragdrop.py", line 227, in _fire_callback
  File "app\signage_ui.py", line 207, in on_hover
  File "app\signage_ui.py", line 188, in hover_toggle
AttributeError: 'NoneType' object has no attribute 'prim_id'

**Comment by warmCabin** [comment]
To those who need a workaround: **just don't mouse over the empty slots.** They cause a null pointer exception (or whatever you call those in Python land) as the program tries to look up the mouseover info.
