### ISSUE TITLE
cannot download

### ISSUE THREAD

**Issue by aBronyPlays** [BEEmod/BEE2.4#1474]
its not even possible to download the whole thing. when i try to extract the final one it tells me i dont have permission. ive been using beemod 1.5 but it doesnt even have all the elements that exist in the game. maybe theres some other application that has them? i cant even open beemod 1.5 anymore. this is what comes up.

Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\BEE2_launch.pyw", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "F:\Git\BEE2.4\src\BEE2.py", line 110, in <module>
  File "F:\Git\BEE2.4\src\gameMan.py", line 1156, in init_trans
  File "F:\Git\BEE2.4\src\gameMan.py", line 1184, in load_trans
  File "F:\Git\srctools\srctools\property_parser.py", line 395, in parse
srctools.property_parser.KeyValError: End of text reached with remaining open sections.

File ended with at least one property that didn't have an ending "}".
Error occurred with file "basemodui.txt".

no idea what to do about it.

**Comment by Adrthegamedev** [comment]
Beemod 1.5 is severely out of date, it's old, and the whole program got basically rewritten and changed for the better nowadays, iirc. i suggest that you update to the newest version, Beemod2 4.38.1.

**Comment by Adrthegamedev** [comment]
wait, you were trying to do that. my bad.

**Comment by Adrthegamedev** [comment]
wait, no. The issue you are talking about is fixed by updating to the most latest version. You should get it from https://github.com/BEEmod/BEE2.4/releases/. Don't forget to get the items package too.

**Comment by Konclan** [comment]
Make sure you're downloading from the releases section and that you're installing them in a proper place. I suggest making a new folder in documents for BEEmod and extracting the application and packages to that folder.
https://github.com/BEEmod/BEE2.4/releases
https://github.com/BEEmod/BEE2-items/releases

**Comment by aBronyPlays** [comment]
i can extract all the folders except the BEE2_4.38.1_win folder. it keeps telling me the disk is full or i do not have write permission to the folder. i believe its the later because i can extract other folders without issue. is there a workaround for this?
