### ISSUE TITLE
linux issue

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2.4#1477]
i try to run (repo)/dist/BEE2/BEE2 and it gives me:
```python
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 25, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "app/__init__.py", line 2, in <module>
ModuleNotFoundError: No module named 'tkinter'
[12942] Failed to execute script BEE2_launch
```

**Comment by Zed-GH** [comment]
`ModuleNotFoundError: No module named 'tkinter'` would mean that, for whatever reason, you do not have Python's TKinter package. Generally TKinter comes with Python, at least as far as I know. You should be able to install TKinter by running `python3 -m pip install tk` in a terminal.

**Comment by TeamSpen210** [comment]
On Linux they tend to put Tkinter in an optional additional package, something like `python3-tkinter`.

**Comment by devomaa** [comment]
Ok.. i got somewhere, now i got a really badly resized window, it wont copy the error so I show you the log
```python3
[I] utils.setup_localisations(): Language: 'en_US'
[I] BEE2_launch.<module>(): Arguments: ['./BEE2']
[I] BEE2_launch.<module>(): Running "bee2", version pyinstaller --distpath ../di2.4.38.1:--workpath ../build_tmp compiler.spec
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 49, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "app/BEE2.py", line 5, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "app/gameMan.py", line 28, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "app/backup.py", line 14, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "loadScreen.py", line 15, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "loadScreen_daemon.py", line 11, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "app/img.py", line 7, in <module>
ImportError: cannot import name 'ImageTk' from 'PIL' (/home/me/BEE2.4/dist/BEE2/PIL/__init__.pyc)
[10319] Failed to execute script BEE2_launch
```

**Comment by TeamSpen210** [comment]
Looks like you also need Pillow, and its TK addon - something like `python-pil-tk`?

**Comment by devomaa** [comment]
that doesn't exist, time to use pypi's crappy search thingy

**Comment by haydenwalker980** [comment]
> i try to run (repo)/dist/BEE2/BEE2 and it gives me:
> 
> ```python
> Traceback (most recent call last):
>   File "BEE2_launch.pyw", line 25, in <module>
>   File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
>   File "app/__init__.py", line 2, in <module>
> ModuleNotFoundError: No module named 'tkinter'
> [12942] Failed to execute script BEE2_launch
> ```

Sorry for the bump but I am having the same issue. I've got `python3-tk` installed, along with Pillow. Ive tried recompiling multiple times and nothing
