### ISSUE TITLE
BEEmod2 Crash

### ISSUE THREAD

**Issue by Lolbinhos** [BEEmod/BEE2.4#1499]
```
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 49, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\BEE2.py", line 76, in <module>
  File "packages\__init__.py", line 552, in load_packages
  File "packages\item.py", line 479, in parse
  File "packages\item.py", line 762, in parse_item_folder
  File "editoritems.py", line 984, in parse_one
  File "editoritems.py", line 1103, in _parse_export_block
  File "editoritems.py", line 1340, in _parse_occupied_voxels
  File "srctools\_tokenizer.pyx", line 658, in srctools._tokenizer.BlockIter.__next__
srctools.tokenizer.TokenSyntaxError: Unexpected token BRACE_OPEN!
Error occurred on line 90, with file "items/slot_clean/editoritems.txt".
Traceback (most recent call last):
  File "app\sound.py", line 135, in ticker
  File "logging\__init__.py", line 1794, in info
  File "srctools\logger.py", line 92, in log
  File "logging\__init__.py", line 1577, in _log
  File "logging\__init__.py", line 1587, in handle
  File "logging\__init__.py", line 1649, in callHandlers
  File "logging\__init__.py", line 948, in handle
  File "logging\__init__.py", line 1182, in emit
  File "logging\__init__.py", line 1171, in _open
FileExistsError: [Errno 17] File exists: 'F:\\SteamLibrary\\steamapps\\common\\Portal 2\\Bee mod 2\\logs\\bee2.log'
```

**Comment by johndoe5828** [comment]
getting the same thing..

Traceback (most recent call last):
  File "BEE2_launch.pyw", line 49, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\BEE2.py", line 76, in <module>
  File "packages\__init__.py", line 552, in load_packages
  File "packages\item.py", line 479, in parse
  File "packages\item.py", line 762, in parse_item_folder
  File "editoritems.py", line 984, in parse_one
  File "editoritems.py", line 1103, in _parse_export_block
  File "editoritems.py", line 1340, in _parse_occupied_voxels
  File "srctools\_tokenizer.pyx", line 658, in srctools._tokenizer.BlockIter.__next__
srctools.tokenizer.TokenSyntaxError: Unexpected token BRACE_OPEN!
Error occurred on line 90, with file "items/slot_clean/editoritems.txt".
Traceback (most recent call last):
  File "app\sound.py", line 135, in ticker
  File "logging\__init__.py", line 1794, in info
  File "srctools\logger.py", line 92, in log
  File "logging\__init__.py", line 1577, in _log
  File "logging\__init__.py", line 1587, in handle
  File "logging\__init__.py", line 1649, in callHandlers
  File "logging\__init__.py", line 948, in handle
  File "logging\__init__.py", line 1182, in emit
  File "logging\__init__.py", line 1171, in _open
FileExistsError: [Errno 17] File exists: '***************************\\logs\\bee2.log'

**Comment by gootie3** [comment]
Just go to the beemod directory, go to the "logs" folder, and delete everything in it.

**Comment by TeamSpen210** [comment]
Actually it looks like you have an old copy of packages.

**Comment by LautaroL20** [comment]
> Actually it looks like you have an old copy of packages.

Most likely, yes. Also, the author made this issue while he were using old versions of the application and packages.
