### ISSUE TITLE
bee2 crash's when i switch from clean to BTS, old apreture 1980's and Portal 1

### ISSUE THREAD

**Issue by MarcusKubis9** [BEEmod/BEE2.4#1502]
Hello bee2 crash's when I switch from clean to BTS, old aperture 1980s and Portal 1

and using normal portal 2 pallet

and I have no UCP's installed

**Comment by MarcusKubis9** [comment]
any help would be great also I did try reinstalling

**Comment by Blaztix** [comment]
Same, from clean to BTS

I got the next error.

```
Traceback (most recent call last):
  File "app\selector_win.py", line 996, in save
  File "app\selector_win.py", line 1065, in do_callback
  File "app\UI.py", line 2022, in style_select_callback
  File "app\item_search.py", line 73, in rebuild_database
  File "app\UI.py", line 152, in get_tags
IndexError: list index out of range
```
