### ISSUE TITLE
Beemod causes "Failure To Compile"

### ISSUE THREAD

**Issue by papli0** [BEEmod/BEE2.4#1508]
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 49, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\BEE2.py", line 5, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\gameMan.py", line 31, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\optionWindow.py", line 17, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\contextWin.py", line 22, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\itemconfig.py", line 14, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\UI.py", line 25, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\item_search.py", line 8, in <module>
ImportError: DLL load failed while importing marisa_trie: The specified module could not be found.
Traceback (most recent call last):
  File "app\sound.py", line 135, in ticker
  File "logging\__init__.py", line 1794, in info
  File "srctools\logger.py", line 92, in log
  File "logging\__init__.py", line 1577, in _log
  File "logging\__init__.py", line 1587, in handle
  File "logging\__init__.py", line 1649, in callHandlers
  File "logging\__init__.py", line 948, in handle
  File "logging\__init__.py", line 1182, in emit
  File "logging\__init__.py", line 1171, in _open
FileExistsError: [Errno 17] File exists: 'C:\\Users\\ACER\\Desktop\\BeEmOdEE\\logs\\bee2.log'
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 49, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\BEE2.py", line 5, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\gameMan.py", line 31, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\optionWindow.py", line 17, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\contextWin.py", line 22, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\itemconfig.py", line 14, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\UI.py", line 25, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\item_search.py", line 8, in <module>
ImportError: DLL load failed while importing marisa_trie: The specified module could not be found.
Traceback (most recent call last):
  File "app\sound.py", line 135, in ticker
  File "logging\__init__.py", line 1794, in info
  File "srctools\logger.py", line 92, in log
  File "logging\__init__.py", line 1577, in _log
  File "logging\__init__.py", line 1587, in handle
  File "logging\__init__.py", line 1649, in callHandlers
  File "logging\__init__.py", line 948, in handle
  File "logging\__init__.py", line 1182, in emit
  File "logging\__init__.py", line 1171, in _open
FileExistsError: [Errno 17] File exists: 'C:\\Users\\ACER\\Desktop\\BeEmOdEE\\logs\\bee2.log'

I have no idea what this means

**Comment by LautaroL20** [comment]
This issue was created while using an outdated BEE2 version, so please get the latest version of the application & packages and then if the issue still exists, let us know and we will re-open the issue.
