### ISSUE TITLE
add windows 8 compatibility

### ISSUE THREAD

**Issue by thefurrywolf** [BEEmod/BEE2.4#1546]
**Description of the feature: make a windows 8 version**

**This should be implemented because: i thing beemob is useful and would love to use it on my windows 8.1 laptop**

**Additional information:if i try to open the latest version it gives me this error:**
Traceback (most recent call last):
  File "pyglet\media\codecs\wave.py", line 58, in __init__
  File "wave.py", line 509, in open
  File "wave.py", line 163, in __init__
  File "wave.py", line 130, in initfp
wave.Error: file does not start with RIFF id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app\sound.py", line 136, in ticker
  File "pyglet\media\__init__.py", line 140, in load
  File "pyglet\media\__init__.py", line 130, in load
  File "pyglet\media\codecs\wave.py", line 107, in decode
  File "pyglet\media\codecs\wave.py", line 60, in __init__
pyglet.media.codecs.wave.WAVEDecodeException: file does not start with RIFF id
**and this in logs:**
[I] sound.ticker(): Loading sound "swap" -> C:\Users\LocalAdmin\Downloads\BEE2_v4.39.2_win64\sounds\extrude.ogg

**Comment by TeamSpen210** [comment]
This error doesn't have anything to with Windows 8. Try running it again, if it doesn't work grab the 32 bit version.
