### ISSUE TITLE
BEE2 4.37+ versions always crashing

### ISSUE THREAD

**Issue by TPEcool** [BEEmod/BEE2.4#1559]
**BEE2 version: all after 4.38.0**

**Description of the bug: when I try to open ANY version of BEEmod after 4.38, it crashes because it didn't get enough permissions on a file that doesn't exist(C:\Program Files (x86)\Steam\steamapps\common\620\portal2_dlc2\tmp1)!**

**Steps to reproduce: I just try to open bee2 version above 4.37 (it has got compiler crash with fizzlers) and it crashes!**

**Additional information: the error is: Traceback (most recent call last):
  File "BEE2_launch.pyw", line 49, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "app\BEE2.py", line 69, in <module>
  File "app\gameMan.py", line 1431, in load
  File "app\gameMan.py", line 433, in edit_gameinfo
  File "srctools\__init__.py", line 444, in __enter__
  File "srctools\__init__.py", line 437, in make_tempfile
PermissionError: [Errno 13] Permission denied: 'C:/Program Files (x86)/Portal 2\\portal2_dlc2\\tmp_1'
**

**Comment by TPEcool** [comment]
i even tried reinstalling all versions a lot of times, that didn't work!

**Comment by LautaroL20** [comment]
What does mean "all after 4.38.0"? Anyone who are having issues with the Beemod interface needs to be very specific at mentioning which version he is using, otherwise we can not help solving the issue. You seem to have provided a log but without knowing the specific version of Beemod, that is useless. Also, we do not support issues that have not been reported using the latest Beemod release.

**Comment by FrozenDragon0** [comment]
@LautaroL20 It means every version after 4.38

**Comment by LautaroL20** [comment]
@FrozenDragon0 - That is useless, anyone who are having issues with the Beemod interface needs to be very specific at mentioning which version he is using, otherwise we can not help solving their issues...

**Comment by LautaroL20** [comment]
Closing because the author does not respond and he probably never will.
