### ISSUE TITLE
What does this BEE2 error mean and how can I fix it?

### ISSUE THREAD

**Issue by PieCreeper12** [BEEmod/BEE2.4#1566]
Traceback (most recent call last):
  File "app\UI.py", line 815, in export_editoritems
  File "app\gameMan.py", line 863, in export
  File "app\gameMan.py", line 571, in refresh_cache
PermissionError: [WinError 5] Access is denied: 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\bee2\\bee2.exe'

The version that I am using is 4.39.1.

**Comment by TeamSpen210** [comment]
Don't put BEEmod in `Portal 2/bee2/`.

**Comment by PieCreeper12** [comment]
Oh. I named my BEE2 folder "bee2".
