### ISSUE TITLE
BEE2 4.36.1 Crash

### ISSUE THREAD

**Issue by JeremiahWD** [BEEmod/BEE2.4#1579]
**BEE2 version:**
4.36.1

**Description of the bug:**
Whenever I go to launch the app, an error message comes up and closes. I have read the log, but not sure what it means. Could someone help me with this?

**Steps to reproduce:**
I have installed version BEE2 4.36.1 for Windows and the packages (version 4.36.0).

**Additional information:**
Here is the log information:

[D] BEE2.<module>(): Loading settings...
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\BEE2_launch.pyw", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "F:\Git\BEE2.4\src\BEE2.py", line 73, in <module>
  File "F:\Git\BEE2.4\src\gameMan.py", line 1415, in load
  File "F:\Git\BEE2.4\src\gameMan.py", line 437, in edit_gameinfo
  File "F:\Git\srctools\srctools\__init__.py", line 333, in __exit__
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2\\portal2_dlc2\\tmp_4' -> 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2\\portal2_dlc2\\gameinfo.txt'

**Comment by Luke18033** [comment]
You're using an old version, issues reported here need to be tested in the latest version of BEE2.

**Comment by JeremiahWD** [comment]
@Luke18033 Ok thanks. Could you give me a link to the latest version? I can't seem to find it sorry
