### ISSUE TITLE
Unknown volume key "Pos"!

### ISSUE THREAD

**Issue by gootie3** [BEEmod/BEE2.4#1584]
**BEE2 version:** 4.39.2

**Description of the bug:** BEE2 crashes on startup with this error. I'm using the 64 bit version of BEE2. (Windows 10 x64 Home OS, version 10.0.19042)

![Screenshot of the error](https://user-images.githubusercontent.com/83893433/117559377-feda1500-b041-11eb-9f31-05d20e6c033c.png)

Log: 
```
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 49, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\BEE2.py", line 76, in <module>
  File "packages\__init__.py", line 552, in load_packages
  File "packages\item.py", line 482, in parse
  File "packages\item.py", line 776, in parse_item_folder
  File "editoritems.py", line 984, in parse_one
  File "editoritems.py", line 1107, in _parse_export_block
  File "editoritems.py", line 1406, in _parse_embedded_voxels
srctools.tokenizer.TokenSyntaxError: Unknown volume key "Pos"!
Error occurred on line 65, with file "items/neuro_vent/editoritems.txt".

**Comment by LautaroL20** [comment]
That would indicate you have installed an outdated item packages or that you were trying to modify the configuration files from an item in a wrong way. Do you have installed version 4.39.1 of the item packages?

**Comment by LautaroL20** [comment]
Closing because the author doesn't respond.
