### ISSUE TITLE
Unable to compile BEE2.4 on Linux Mint (The program, not a map): TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by NinjaCheetah** [BEEmod/BEE2.4#1600]
When trying to compile BEE2.4 (commit `eba16f1`) on Linux Mint, the actual build step, `pyinstaller --distpath ../dist/64bit/ --workpath ../build_tmp BEE2.spec` fails with the error:
```
122 INFO: PyInstaller: 4.3
122 INFO: Python: 3.8.5
141 INFO: Platform: Linux-5.4.0-73-generic-x86_64-with-glibc2.29
144 INFO: UPX is not available.
Traceback (most recent call last):
  File "/home/ninjacheetah/.local/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/home/ninjacheetah/.local/lib/python3.8/site-packages/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/ninjacheetah/.local/lib/python3.8/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/ninjacheetah/.local/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/ninjacheetah/.local/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 684, in build
    exec(code, spec_namespace)
  File "BEE2.spec", line 4, in <module>
    import srctools
  File "/usr/local/lib/python3.8/dist-packages/srctools-1.2.0-py3.8-linux-x86_64.egg/srctools/__init__.py", line 533, in <module>
    from srctools.vtf import VTF
  File "/usr/local/lib/python3.8/dist-packages/srctools-1.2.0-py3.8-linux-x86_64.egg/srctools/vtf.py", line 82, in <module>
    ) -> tuple[int, int, int, int, int, int]:
TypeError: 'type' object is not subscriptable
```
I've double/triple checked the dependencies, and `srctools`, which seems to be the issue, installed just fine. I've seen other issues regarding BEE2.4 on Linux so clearly it should be working. I'm running Linux Mint 20.1 on x86_64.

**Comment by TeamSpen210** [comment]
This is my fault, some Python 3.9 only syntax slipped in here. You should be able to pull and get it to compile.
