### ISSUE TITLE
Bee2 crashes when trying to install UI.

### ISSUE THREAD

**Issue by YellowGamer12** [BEEmod/BEE2.4#1606]
I tried to install Bee2 but it just crashed on me.
Logs:
-----------------------------------------------------------------------------------------------
Traceback (most recent call last):
File "F:\Git\BEE2.4\src\BEE2_launch.pyw", line 50, in <module>
File "<frozen importlib._bootstrap>", line 961, in _find_and_load
File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
File "F:\Git\BEE2.4\src\BEE2.py", line 110, in <module>
File "F:\Git\BEE2.4\src\gameMan.py", line 1156, in init_trans
File "F:\Git\BEE2.4\src\gameMan.py", line 1184, in load_trans
File "F:\Git\srctools\srctools\property_parser.py", line 395, in parse
srctools.property_parser.KeyValError: End of text reached with remaining open sections.

File ended with at least one property that didn't have an ending "}".
Error occurred with file "basemodui.txt".
-----------------------------------------------------------------------------------------------
I have Windows 10 Home
And i tried to install Bee2 V.4.35.1

I followed a Steam guide perfectly i unzipped and combined packages with the Bee2_win.zip and opened the program. It told me to select portal-2.exe and then got this log error. So it couldn't launch and closed on me. I tried validating files and re-installing portal 2. Did the same with Bee2 and tried to re-follow guide. Note: i wasted time as i literally got this same log error.

Thx for reading!
Hope to get an reply soon!

With friendly regards,
ElectroGamer

**Comment by FrozenDragon0** [comment]
Was this Version 4.35 that you were trying to install?

**Comment by YellowGamer12** [comment]
> Was this Version 4.35 that you were trying to install?

Yeah 4.35.1

**Comment by FrozenDragon0** [comment]
@YellowGamer12 In that case you'll need to use V4.39 if you want to report issues. We no longer support older versions as they are outdated.

**Comment by Lieutenant-L-T-Smash** [comment]
@YellowGamer12 

This is partly Valve's fault as one of the game files is not properly formatted. Versions of BEE after 4.35 were made tolerant of this fault. If you want to keep using 4.35, you can fix it yourself. In your Portal 2 game folder, open \portal2_dlc2\resource\basemodui_english.txt and at the very end of the file add one extra line containing only a closing curly brace "}".
