### ISSUE TITLE
BEE2 crashes with error "KeyError: 'UnlockDefault'" on Linux

### ISSUE THREAD

**Issue by NinjaCheetah** [BEEmod/BEE2.4#1607]
**BEE2 version:** Commit `eba16f1`

**Description of the bug:**
BEE2 crashes right at the end of the loading screen with the error `KeyError: 'UnlockDefault'` (seems to be a TKinter Error).

**Steps to reproduce:**
- Compile the latest BEE2 commit on Linux
- Start the program and locate your Portal 2 executable
- Let it load
- Crash occurs when loading is almost finished

**Additional information:**
Console logs:
```
[E] __init__.tk_error(): Uncaught Exception:
Traceback (most recent call last):
  File "app/UI.py", line 1565, in flow_picker
KeyError: 'UnlockDefault'
Error in sys.excepthook:
Traceback (most recent call last):
  File "logging/__init__.py", line 950, in handle
  File "logging/__init__.py", line 1182, in emit
  File "logging/__init__.py", line 1172, in _open
FileExistsError: [Errno 17] File exists: '/home/ninjacheetah/BEEMOD/BEE2/logs/bee2.log'

Original exception was:
Traceback (most recent call last):
  File "app/img.py", line 78, in png
  File "srctools/filesys.py", line 165, in __getitem__
  File "srctools/filesys.py", line 288, in _get_file
FileNotFoundError: bee2/none_96.png

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "BEE2_launch.pyw", line 49, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "app/BEE2.py", line 109, in <module>
  File "app/UI.py", line 1902, in init_windows
  File "app/UI.py", line 1343, in init_option
  File "app/music_conf.py", line 130, in make_widgets
  File "app/selector_win.py", line 449, in __init__
  File "app/selector_win.py", line 290, in __init__
  File "app/selector_win.py", line 217, in get_icon
  File "app/img.py", line 80, in png
  File "logging/__init__.py", line 1800, in warning
  File "srctools/logger.py", line 101, in log
  File "logging/__init__.py", line 1577, in _log
  File "logging/__init__.py", line 1587, in handle
  File "logging/__init__.py", line 1649, in callHandlers
  File "logging/__init__.py", line 950, in handle
  File "logging/__init__.py", line 1182, in emit
  File "logging/__init__.py", line 1172, in _open
FileExistsError: [Errno 17] File exists: '/home/ninjacheetah/BEEMOD/BEE2/logs/bee2.log'
[25293] Failed to execute script BEE2_launch
```
**System Information:**
- Linux Mint 20.1
- Python 3.8.5

**Comment by xtechgithub** [comment]
I have the same error with Ubuntu MATE, also sadly have no idea how to fix.

**Comment by TeamSpen210** [comment]
Try the latest dev, I found and fixed this initialisation order issue.
