### ISSUE TITLE
Beemod crashes 95% of the time

### ISSUE THREAD

**Issue by InsaneDevil1** [BEEmod/BEE2.4#1615]
When i open up beemod, i get 2 errors that come up and when i close them beemod closes.
this actually also happens when i export, or it just likes to crash when i open some other items or change style, this just happens for random reasons but is fine the next time...
can i get any help? here are the crashes:

Traceback (most recent call last):
  File "BEE2_launch.pyw", line 49, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\BEE2.py", line 109, in <module>
  File "app\UI.py", line 2047, in init_windows
  File "BEE2_config.py", line 69, in read_settings
  File "BEE2_config.py", line 49, in apply_settings
  File "app\UI.py", line 468, in save_load_selector_win
  File "app\selector_win.py", line 1085, in sel_item_id
  File "app\selector_win.py", line 1065, in do_callback
  File "app\UI.py", line 2029, in style_select_callback
  File "app\CompilerPane.py", line 297, in set_corridors
  File "BEE2_config.py", line 170, in save_check
  File "BEE2_config.py", line 164, in save
  File "srctools\__init__.py", line 465, in __exit__
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\MW\\AppData\\Roaming\\BEEMOD2\\config\\tmp_174' -> 'C:\\Users\\MW\\AppData\\Roaming\\BEEMOD2\\config\\compile.cfg'
Traceback (most recent call last):
  File "app\sound.py", line 135, in ticker
  File "logging\__init__.py", line 1802, in info
  File "srctools\logger.py", line 92, in log
  File "logging\__init__.py", line 1585, in _log
  File "logging\__init__.py", line 1595, in handle
  File "logging\__init__.py", line 1657, in callHandlers
  File "logging\__init__.py", line 948, in handle
  File "logging\__init__.py", line 1182, in emit
  File "logging\__init__.py", line 1171, in _open
FileExistsError: [Errno 17] File exists: 'C:\\Users\\MW\\Downloads\\BEE2_v4.39.2_win64\\logs\\bee2.log'
 
 
 
 the second one is:
 
 
 Traceback (most recent call last):
  File "BEE2_launch.pyw", line 49, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\BEE2.py", line 109, in <module>
  File "app\UI.py", line 2047, in init_windows
  File "BEE2_config.py", line 69, in read_settings
  File "BEE2_config.py", line 49, in apply_settings
  File "app\UI.py", line 468, in save_load_selector_win
  File "app\selector_win.py", line 1085, in sel_item_id
  File "app\selector_win.py", line 1065, in do_callback
  File "app\UI.py", line 2029, in style_select_callback
  File "app\CompilerPane.py", line 297, in set_corridors
  File "BEE2_config.py", line 170, in save_check
  File "BEE2_config.py", line 164, in save
  File "srctools\__init__.py", line 465, in __exit__
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\MW\\AppData\\Roaming\\BEEMOD2\\config\\tmp_174' -> 'C:\\Users\\MW\\AppData\\Roaming\\BEEMOD2\\config\\compile.cfg'
Traceback (most recent call last):
  File "app\sound.py", line 135, in ticker
  File "logging\__init__.py", line 1802, in info
  File "srctools\logger.py", line 92, in log
  File "logging\__init__.py", line 1585, in _log
  File "logging\__init__.py", line 1595, in handle
  File "logging\__init__.py", line 1657, in callHandlers
  File "logging\__init__.py", line 948, in handle
  File "logging\__init__.py", line 1182, in emit
  File "logging\__init__.py", line 1171, in _open
FileExistsError: [Errno 17] File exists: 'C:\\Users\\MW\\Downloads\\BEE2_v4.39.2_win64\\logs\\bee2.log'

**Comment by InsaneDevil1** [comment]
if you want the entire log i can give it to you

**Comment by InsaneDevil1** [comment]
i also have no games open when i load it
