### ISSUE TITLE
"FileNotFoundError: No such file or directory" error on startup

### ISSUE THREAD

**Issue by xtechgithub** [BEEmod/BEE2.4#1624]
BEE2 version: v4.40.1 64bit

Description of the bug: BEEmod crashes immediately when it is started on Microsoft Windows 10

Steps to reproduce: Install BEE2, along with packages, as you normally would. Start the application.

Additional information:
```shell
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\BEE2.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\gameMan.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\optionWindow.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\contextWin.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\itemconfig.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\UI.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\CompilerPane.py", line 78, in <module>
  File "BEE2_config.py", line 180, in set_defaults
  File "BEE2_config.py", line 170, in save_check
  File "BEE2_config.py", line 163, in save
  File "contextlib.py", line 117, in __enter__
  File "atomicwrites\__init__.py", line 166, in _open
  File "atomicwrites\__init__.py", line 183, in get_fileobject
  File "tempfile.py", line 332, in mkstemp
  File "tempfile.py", line 251, in _mkstemp_inner
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Thomas\\AppData\\Roaming\\BEEMOD2\\config\\tmp581cx9fz'
```
After this error, it says "Failed to execute script BEE2_launch"

----

### Workaround
This error only affects first time launch. Here's how to fix it manually:
- Press WINDOWS+R or search Run in the start menu
- Type `%AppData%/BEEMOD2` and hit enter
- Make a new folder and name it "Config"

After that BEEmod will launch.

**Comment by TeamSpen210** [comment]
Does `C:\Users\Thomas\Roaming\BEEMOD2\config` actually exist? If not you might be able to create it to work around the issue.

**Comment by Starrysparklez** [comment]
I had the same problem and yes, creating this directory solved the problem. But after selecting the .exe file of the game and specifying the name, the application gives the following error on startup (a splash screen appears, and when the first progress bar reaches the end, this error message appears).
![iOyYAA5B7N](https://user-images.githubusercontent.com/50998351/124398103-154cd600-dd3e-11eb-8ede-0b9365709826.gif)

**Comment by Some-Username-Available** [comment]
Found a way to fix this without any coding.
1. Press WINDOWS+R
2. Enter %AppData%\BEEMOD2
3. Make a new folder and name it "config"
4. Make a .txt file and put it into config
5. Name the .txt "tmpbkj9c8e5"

**Comment by Konclan** [comment]
There is already a workaround listed in this issue, you only need the config folder.

**Comment by Luke18033** [comment]
Renamed so hopefully people will spot this more easily...

**Comment by Konclan** [comment]
Edited the issue so that the image of the log is text so it might be searched easier
