### ISSUE TITLE
BEEmod 4.40.1 Error: "ValueError: Duplicate package with id "TULEBY_ABSOLUTE_FIZZLER"!"

### ISSUE THREAD

**Issue by Glados-os** [BEEmod/BEE2.4#1626]
**BEE2 version:**
4.40.1

**Description of the bug:**
[INFO] utils.setup_localisations(): Language: 'en_US'
[DEBUG] utils.setup_localisations(): Language codes: ['en_US.ISO8859-1', 'en_US', 'en.ISO8859-1', 'en']
[INFO] BEE2_launch.<module>(): Arguments: ['C:\\Program Files (x86)\\Steam\\steamapps\\common\\Portal 2\\portal2_dlc2\\bees\\BEE2.exe']
[INFO] BEE2_launch.<module>(): Running "bee2", version 4.40.1:
[INFO] sound.load(): Loading sound "select" -> C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2_dlc2\bees\sounds\rollover.ogg
[WARNING] BEE2_config.load(): Config "C:\Users\Lolbi\AppData\Roaming\BEEMOD2\config\packages.cfg" not found! Using defaults...
[DEBUG] BEE2.<module>(): Starting loading screen...
[DEBUG] BEE2.<module>(): Loading settings...
[INFO] gameMan.scan_music_locs(): PS-Mel dir: c:\program files (x86)\steam\steamapps\common\Portal Stories Mel/portal_stories/pak01_dir.vpk
[INFO] BEE2.<module>(): Loading Packages...
[DEBUG] packages.find_packages(): Reading package "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2_dlc2\bees\packages\abs_fizz.bee_pack"
[DEBUG] packages.find_packages(): Reading package "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2_dlc2\bees\packages\abs_fizz.zip"
[ERROR] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\BEE2.py", line 74, in <module>
  File "packages\__init__.py", line 455, in load_packages
  File "packages\__init__.py", line 397, in find_packages
ValueError: Duplicate package with id "TULEBY_ABSOLUTE_FIZZLER"!
If you just updated the mod, delete any old files in packages/.
[INFO] BEE2_config.save(): Saving changes in config "C:\Users\Lolbi\AppData\Roaming\BEEMOD2\config\config.cfg"!

**Steps to reproduce:**
Tbh 'Tuleby_Absolute_fizzler' needs to be fixed

**Additional information:**

**Comment by Glados-os** [comment]
This what I keep getting when trying to open BEE2.exe
![image](https://user-images.githubusercontent.com/70824760/124518431-3263c200-dd9b-11eb-8e2b-3d741002a46a.png)
