### ISSUE TITLE
PackagePath is not iterable

### ISSUE THREAD

**Issue by zooz8882** [BEEmod/BEE2.4#1628]
Bee2 version:  Newest version, 4.40.1.

Description of bug: The application opens, begins loading and crashes half way through the 3rd bar and gives the error log.

Steps to reproduce: I am unsure how to reproduce this error.  No one else has had it to my knowledge.

Additional Information: 

Traceback (most recent call last):
  File "BEE2_launch.pyw", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\BEE2.py", line 108, in <module>
  File "app\UI.py", line 1919, in init_windows
  File "app\CompilerPane.py", line 893, in make_pane
  File "app\CompilerPane.py", line 505, in make_widgets
  File "app\CompilerPane.py", line 827, in make_map_widgets
  File "app\CompilerPane.py", line 239, in load_corridors
  File "utils.py", line 380, in parse
TypeError: argument of type 'PackagePath' is not iterable

**Comment by zooz8882** [comment]
I noticed the done tag was added, is this bug something that will be fixed in the next version?
