### ISSUE TITLE
Item Variant widget crashes if item isn't present 

### ISSUE THREAD

**Issue by NoodleMcSchnoodle** [BEEmod/BEE2.4#1632]
(this is my first time making a bug report here so bare with me)

**BEE2 version:**
4.40.2

**Description of the bug:**
I had disabled all packages planning to reneable the ones I needed due to having trouble exporting pallettes with certain styles (anything but clean) then the app crashed, and now I'm unable to uninstall it due to not being able to access the app itself.

**Expected behavior:**
Being able to run the program.

As said, I disabled all packages.

Traceback (most recent call last):
  File "app\itemconfig.py", line 441, in widget_item_variant
KeyError: 'ITEM_OBSERVATION_ROOM'

The error report I received is as follows:
Traceback (most recent call last):
 File "app\itemconfig.py", line 441, in wiedget_item_variant
 KeyError: 'ITEM_OBSERVATION_ROOM'
 
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "BEE2_launch.pyw", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\BEE2.py", line 108, in <module>
  File "app\UI.py", line 1915, in init_windows
  File "app\StyleVarPane.py", line 365, in make_pane
  File "app\itemconfig.py", line 327, in make_pane
  File "app\itemconfig.py", line 443, in widget_item_variant
ValueError: Unknown item "ITEM_OBSERVATION_ROOM"!

(UPDATED, now it's even more)

Traceback (most recent call last):
  File "BEE2_launch.pyw", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\BEE2.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\gameMan.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\optionWindow.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\contextWin.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\itemconfig.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\UI.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\CompilerPane.py", line 78, in <module>
  File "BEE2_config.py", line 180, in set_defaults
  File "BEE2_config.py", line 170, in save_check
  File "BEE2_config.py", line 163, in save
  File "contextlib.py", line 117, in __enter__
  File "atomicwrites\__init__.py", line 166, in _open
  File "atomicwrites\__init__.py", line 183, in get_fileobject
  File "tempfile.py", line 332, in mkstemp
  File "tempfile.py", line 251, in _mkstemp_inner
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\brode\\AppData\\Roaming\\BEEMOD2\\config\\tmpb1tivzgp'

(Afterwards it states that it "Failed to execute script BEE2_launch)
(I've been thinking removing Bee2 then reinstalling it would help but I can't access the application to do so)

**Comment by TeamSpen210** [comment]
What you can do is go to `%appdata%/BEEMOD/` and delete `instances.cfg`, to work around this. But definitely need error handling here.

**Comment by NoodleMcSchnoodle** [comment]
Sorry if I'm just being stupid, but I can't find the file in the aforementioned folder

**Comment by NoodleMcSchnoodle** [comment]
Now there's even more problems somehow

**Comment by TeamSpen210** [comment]
Create the config/ folder in BEEMOD, if it doesn't exist.

**Comment by NoodleMcSchnoodle** [comment]
It's working now, thanks!
