### ISSUE TITLE
When I launch BEE2, 2 errors appears. I don't know what to do

### ISSUE THREAD

**Issue by 7777EGOR7777** [BEEmod/BEE2.4#1646]
**BEE2 Version: 4.40.2 (64 bit)**

<details>
<summary>Error Log 1</summary>
The program cannot be started because there is no file on the computer api-ms-core-path-l1-1-0.dll. Try reinstalling the program.

<details>
<summary>Error Log 2</summary>
Error loading Python DLL 'H:\My folder\Programs\BEE2 for PORTAL2\python39.dll'.
LoadLibrary: The specified module was not found

**Comment by LautaroL20** [comment]
Closing because the author doesn't respond.

**Comment by 7777EGOR7777** [comment]
@LautaroL20 Sorry, I couldn't answer because I couldn't log in to my account. I tried to run the 32-bit version, the error "Failed to execute script pyi_rth_pkgres" appears.

**Comment by 7777EGOR7777** [comment]
I tried to run the 32-bit version, the error "Failed to execute script
pyi_rth_pkgres" appears.

вт, 17 авг. 2021 г. в 12:17, Konclan ***@***.***>:

**Comment by Konclan** [comment]
Are you using the latest version? Can you paste the full crash log?

**Comment by dsagfa** [comment]
> @LautaroL20 Sorry, I couldn't answer because I couldn't log in to my account. I tried to run the 32-bit version, the error "Failed to execute script pyi_rth_pkgres" appears.

Really? I got Traceback (most recent call last):
  File "BEE2_launch.pyw", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\BEE2.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\gameMan.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\optionWindow.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\contextWin.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\itemconfig.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\UI.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\CompilerPane.py", line 78, in <module>
  File "BEE2_config.py", line 180, in set_defaults
  File "BEE2_config.py", line 170, in save_check
  File "BEE2_config.py", line 163, in save
  File "contextlib.py", line 113, in __enter__
  File "atomicwrites\__init__.py", line 166, in _open
  File "atomicwrites\__init__.py", line 183, in get_fileobject
  File "tempfile.py", line 331, in mkstemp
  File "tempfile.py", line 250, in _mkstemp_inner
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\bradl\\AppData\\Roaming\\BEEMOD2\\config\\tmpqd7plvvw'

**Comment by CardsAndGamesYT** [comment]
How To Fix:

1.  Press WINDOWS+R
2.  Enter %AppData%\BEEMOD2
3. Make a new folder and name it Config

**Comment by 7777EGOR7777** [comment]
@Konclan Yes, I am using the latest version. I do not know where the error log is located, can you suborder it?

**Comment by Konclan** [comment]
There should be `/logs` in the BEE2 app folder. Can you also give us more information, like windows version, 32 or 64 bit, where you put the BEEmod app, etc.

**Comment by 7777EGOR7777** [comment]
@Konclan I did not find the error log, Windows 7 64-bit is installed on the computer, BEEmod is located in H:\My folder\PROGRAMS\BEE2, mod version-4.40.2, packages version-4.40.2, the weight of the folder with packages is 356,030,944 bytes, on the disk-359,452,672 bytes, it also contains 1175 files and 51 folders.

**Comment by Konclan** [comment]
Ah, as #1520 says the 64 bit version of BEEmod doesn't work on windows 7. Have you tried the 32 bit version?

**Comment by 7777EGOR7777** [comment]
@Konclan I tried to run the 32-bit version, the error "Failed to execute script pyi_rth_pkgres" appears.

**Comment by Luke18033** [comment]
Closing for now
