### ISSUE TITLE
Bee2 doesn't launch, throws out huge error

### ISSUE THREAD

**Issue by Maks7594** [BEEmod/BEE2.4#1648]
**BEE2 version: 4.40.2**

**Description of the bug: Bee2 crashes on startup**

**Expected behavior: Start up like normal, load everything etc.**

**Steps to reproduce: Launch bee2.exe**

Additional information: I use Windows 8.1. Also this is my error thing:
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\BEE2.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\gameMan.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\optionWindow.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\contextWin.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\itemconfig.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\UI.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\CompilerPane.py", line 78, in <module>
  File "BEE2_config.py", line 180, in set_defaults
  File "BEE2_config.py", line 170, in save_check
  File "BEE2_config.py", line 163, in save
  File "contextlib.py", line 117, in __enter__
  File "atomicwrites\__init__.py", line 166, in _open
  File "atomicwrites\__init__.py", line 183, in get_fileobject
  File "tempfile.py", line 332, in mkstemp
  File "tempfile.py", line 251, in _mkstemp_inner
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Maksy\\AppData\\Roaming\\BEEMOD2\\config\\tmp_68umt9n'

**Comment by LautaroL20** [comment]
This is a duplicate of: https://github.com/BEEmod/BEE2.4/issues/1624

However, this is now fixed in the next BEEmod release though.
