### ISSUE TITLE
k

### ISSUE THREAD

**Issue by dsagfa** [BEEmod/BEE2.4#1667]
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\BEE2.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\gameMan.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\optionWindow.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\contextWin.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\itemconfig.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\UI.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\CompilerPane.py", line 78, in <module>
  File "BEE2_config.py", line 180, in set_defaults
  File "BEE2_config.py", line 170, in save_check
  File "BEE2_config.py", line 163, in save
  File "contextlib.py", line 113, in __enter__
  File "atomicwrites\__init__.py", line 166, in _open
  File "atomicwrites\__init__.py", line 183, in get_fileobject
  File "tempfile.py", line 331, in mkstemp
  File "tempfile.py", line 250, in _mkstemp_inner
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\bradl\\AppData\\Roaming\\BEEMOD2\\config\\tmpcqklggtd'

**Comment by dsagfa** [comment]
> This is a duplicate of: #1624 the issue is even pinned, you must to pay more attention.

Yeah, you aren't helping.

**Comment by DarviL82** [comment]
Someone please ban this user for taking actions on this repo. Maybe @LautaroL20 ?

**Comment by Nyrif** [comment]
It's a duplicate of another issue, that's why it's closed. I've had this same problem and I at least started checking for duplicates. Duplicate issues just fill up the issues page, so you'll see 10 of the same rather than 10 different issues, making it harder to find people's reported bugs when it's all the same.

**Comment by Nyrif** [comment]
Oh yeah btw this issue is fixed by deleting the config folder. I had this issue. Calm down.

**Comment by CardsAndGamesYT** [comment]
> > This is a duplicate of: #1624 the issue is even pinned, you must to pay more attention.
> 
> Yeah, you aren't helping.
y o u    h a v e   b e e n   t o l d   h o w   t o   f i x   i t   l i k e   7   t i m e s

**Comment by CardsAndGamesYT** [comment]
a n d   h e    w a s    h e l p i n g
