### ISSUE TITLE
BEE2 initializer is not responding

### ISSUE THREAD

**Issue by Bollinha** [BEEmod/BEE2.4#1688]
at the exact moment I open the BEE2, it already stops responding and nothing loads. I don't know what else to do.

**Comment by FrozenDragon0** [comment]
Is there any error message or anything that appears? We can't exactly fix a problem without any error info or crash logs etc.

**Comment by Bollinha** [comment]
Traceback (most recent call last):
  File "bg_daemon.py", line 783, in check_queue
  File "bg_daemon.py", line 500, in op_set_length
  File "bg_daemon.py", line 483, in update_stage
ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tkinter\__init__.py", line 814, in callit
  File "bg_daemon.py", line 785, in check_queue
Exception: set_length

**Comment by Bollinha** [comment]
and the error says that the package was not found, even with the packages folder in the BEE2 folder

**Comment by seagemgames** [comment]
Are there any packages in the packages folder, or is it empty?

**Comment by Bollinha** [comment]
in the packages folder have:

items
music
pack
resources
skybox
styles
templates
voices
vpk
and a txt file called "info"

**Comment by Bollinha** [comment]
but dont have other folder named packages

**Comment by TeamSpen210** [comment]
Did you unzip all the packages or something?

**Comment by Bollinha** [comment]
no

**Comment by seagemgames** [comment]
You must have, those belong in the package zips...

**Comment by Konclan** [comment]
Closing due to lack of info/response

**Comment by Bollinha** [comment]
is the files from the packages folder or the packages folder? I extracted everything from the packages folder and I tried to start but it's giving an error again 

Traceback (most recent call last):
  File "BEE2_launch.pyw", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\BEE2.py", line 74, in <module>
  File "packages\__init__.py", line 505, in load_packages
  File "packages\item.py", line 495, in parse
  File "packages\item.py", line 789, in parse_item_folder
  File "editoritems.py", line 985, in parse_one
  File "editoritems.py", line 1108, in _parse_export_block
  File "editoritems.py", line 1408, in _parse_embedded_voxels
srctools.tokenizer.TokenSyntaxError: Unknown volume key "Pos"!
Error occurred on line 63, with file "BEE2_NEUROTOXIN:items/neuro_vent/editoritems.txt".

and failed to start the BEE2 script

**Comment by TeamSpen210** [comment]
The files in the packages folder
