### ISSUE TITLE
BEEmod crash: Error occured with file "basemodui.txt"

### ISSUE THREAD

**Issue by ScratchBotManager** [BEEmod/BEE2.4#1700]
### BEE2 Application Version

4.40.0

### BEE2 Package Version

4.40.0

### What operating system are you running on?

Windows 10 (64bit)

### Logs and Reports

```shell
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2.pyw", line 139, in <module>
  File "F:\Git\BEE2.4\src\gameMan.py", line 788, in init_trans
  File "F:\Git\srctools\srctools\property_parser.py", line 418, in parse
srctools.property_parser.KeyValError: End of text reached with remaining open sections.
Error occured with file "basemodui.txt"
```

### Additional information

idk what happened

**Comment by Luke18033** [comment]
Are you sure you're on 4.40? This error was fixed a long time ago.

**Comment by LautaroL20** [comment]
Closing because the issue's author doesn't respond.

**Comment by Luke18033** [comment]
This is a very old bug anyway...

**Comment by LautaroL20** [comment]
Yep.
