### ISSUE TITLE
BEE2.4 dev build breaks when launching BEE2.4.exe

### ISSUE THREAD

**Issue by Ponklu** [BEEmod/BEE2.4#1753]
### BEE2 Application Version

dev 64bit

### BEE2 Package Version

4.40.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

After compiling a dev build of BEE2.4 when running the exe file it says that there is no module named 'pygtrie'.

### Expected behavior

I expect that compiling a dev build of BEE2.4 can be broken but i don't expect it to break for a module.

### Steps to reproduce

1. Compile the latest version of BEE2.4.git
2. Run BEE2.4.exe and see that in BEE2_launch.pyw (and other files) are broken from a line having module.

### Logs and Reports

```shell
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 50, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "app\BEE2.py", line 5, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "app\gameMan.py", line 35, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "app\optionWindow.py", line 17, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "app\contextWin.py", line 20, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "app\itemconfig.py", line 17, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "app\UI.py", line 25, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "app\item_search.py", line 8, in <module>
ModuleNotFoundError: No module named 'pygtrie'
```

**Comment by TeamSpen210** [comment]
Did you install that module? Run `pip instal -r requirements.txt` to grab all the required ones.

**Comment by Ponklu** [comment]
After installing the missing module and rebuilding it fixed itself.
