### ISSUE TITLE
Crash while loading: zipfile reading not threadsafe 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#1756]
### BEE2 Application Version

RC2 32bit

### BEE2 Package Version

RC1

### What operating system are you running on?

Windows 7 (64bit)

### Logs and Reports

```shell
[ERROR] __init__.tk_error(): Uncaught Tk Exception:
Traceback (most recent call last):
  File "app\BEE2.py", line 85, in init_app
  File "packages\__init__.py", line 511, in load_packages
  File "trio\_core\_run.py", line 815, in __aexit__
  File "packages\template_brush.py", line 24, in parse_template
  File "trio\_threads.py", line 207, in to_thread_run_sync
  File "trio\_core\_traps.py", line 166, in wait_task_rescheduled
  File "outcome\_impl.py", line 138, in unwrap
  File "trio\_threads.py", line 157, in do_release_then_return_result
  File "outcome\_impl.py", line 138, in unwrap
  File "trio\_threads.py", line 170, in worker_fn
  File "packages\template_brush.py", line 56, in parse_template_fast
  File "zipfile.py", line 986, in read1
  File "zipfile.py", line 1030, in _read1
  File "zipfile.py", line 958, in _update_crc
zipfile.BadZipFile: Bad CRC-32 for file 'templates/stairs_squarebeams.vmf'
```

**Comment by LautaroL20** [comment]
This issue not only happens with the file "templates/stairs_squarebeams.vmf", but also with others such as: "templates/track_middle.vmf" and probably more...

**Comment by Laudanum-dev** [comment]
this issue occurs on windows 10 64-bit too. i think it can happen for any template file randomly.

experienced this issue myself on my not up-to-date dev build, but thought it was fixed shortly

**Comment by Luke18033** [comment]
Is this fixed now?

**Comment by TeamSpen210** [comment]
I added some code to patch the Python zip library to fix it, so yes.

**Comment by LautaroL20** [comment]
Fixed in RC3.
