### ISSUE TITLE
I can't install bee2

### ISSUE THREAD

**Issue by Bollinha** [BEEmod/BEE2.4#1769]
I can't install bee2 I've already extracted the packages and this error always appears:

Traceback (most recent call last):
  File "BEE2_launch.pyw", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\BEE2.py", line 74, in <module>
  File "packages\__init__.py", line 459, in load_packages
  File "packages\__init__.py", line 401, in find_packages
ValueError: Duplicate package with id "TULEBY_ABSOLUTE_FIZZLER"!
If you just updated the mod, delete any old files in packages/.

Failed to execute BEE2 script.

and I put the BEE2 folder inside portal 2 and this error continues to appear.

**Comment by LautaroL20** [comment]
Which BEEmod and packages version are you using? Did you also installed an UCP as well?

**Comment by Bollinha** [comment]
i am using version V.40.2 and packages are V.35.0.

what is a UCP?

**Comment by Luke18033** [comment]
You're not supposed to mix different package and app versions, why do people do that?

**Comment by Bollinha** [comment]
yes I just realized that the packages folder was in an older version.

**Comment by LautaroL20** [comment]
> Bollinha said: "i am using version V.40.2 and packages are V.35.0."

Never use different release versions of the Packages and Application, they always must be from the same Pre-Release Version because otherwise, issues like this can happens.

> Bollinha also said: "what is a UCP?"

UCP means: "User Created Packages", basically they are custom items made by the BEEmod community that you can add to the application. You can find them in the BEEmod discord server.

> Bollinha also said: "yes I just realized that the packages folder was in an older version."

No, the packages where in a newer version of BEEmod.
