### ISSUE TITLE
BEE2.4 compilation error in Linux

### ISSUE THREAD

**Issue by tim631** [BEEmod/BEE2.4#1772]
### BEE2 Application Version

commit 02767f3cf4 (2.4.41.0)

### BEE2 Package Version

commit fd5b449a (2.4.41-beta5)

### What operating system are you running on?

Linux

### Description of the bug

BEE2.4 doesn't compiling when i execute commands from README

### Expected behavior

I'm expecting successful compilation

### Steps to reproduce

Step 1. get commit 02767f3cf4 (2.4.41.0) version of BEE2.4
Step 2. get commit fd5b449ad9 (2.4.41-beta5) version of BEE2.4 packages
Step 3. go to BEE2.4/src
Step 4. execute "pyinstaller --distpath ../dist/64bit/ --workpath ../build_tmp compiler.spec"
Step 5. execute "pyinstaller --distpath ../dist/64bit/ --workpath ../build_tmp BEE2.spec"

### Logs and Reports

```shell
pyinstaller --distpath ../dist/64bit/ --workpath ../build_tmp compiler.spec
329 INFO: PyInstaller: 4.6
329 INFO: Python: 3.6.9
330 INFO: Platform: Linux-5.4.0-42-generic-x86_64-with-Ubuntu-18.04-bionic
333 INFO: UPX is not available.
Traceback (most recent call last):
  File "<string>", line 21, in walk_packages
  File "/usr/local/lib/python3.6/dist-packages/srctools/_class_resources/__init__.py", line 9, in <module>
    from srctools.packlist import FileType, PackList
  File "/usr/local/lib/python3.6/dist-packages/srctools/packlist.py", line 26, in <module>
    import srctools.logger
  File "/usr/local/lib/python3.6/dist-packages/srctools/logger.py", line 218, in <module>
    class NullStream(TextIO):
  File "/usr/local/lib/python3.6/dist-packages/srctools/logger.py", line 274, in NullStream
    def readlines(self, hint: int=-1) -> list[str]:
TypeError: 'type' object is not subscriptable
collect_submodules: failed to import 'srctools._class_resources'!
Traceback (most recent call last):
  File "<string>", line 21, in walk_packages
  File "/usr/local/lib/python3.6/dist-packages/srctools/bsp_transform/__init__.py", line 8, in <module>
    from srctools.logger import get_logger
  File "/usr/local/lib/python3.6/dist-packages/srctools/logger.py", line 218, in <module>
    class NullStream(TextIO):
  File "/usr/local/lib/python3.6/dist-packages/srctools/logger.py", line 274, in NullStream
    def readlines(self, hint: int=-1) -> list[str]:
TypeError: 'type' object is not subscriptable
collect_submodules: failed to import 'srctools.bsp_transform'!
Traceback (most recent call last):
  File "/home/tim/.local/bin/pyinstaller", line 11, in <module>
    sys.exit(run())
  File "/home/tim/.local/lib/python3.6/site-packages/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/tim/.local/lib/python3.6/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/tim/.local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/tim/.local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 684, in build
    exec(code, spec_namespace)
  File "compiler.spec", line 109, in <module>
    import utils
  File "/home/tim/Templates/portal_2/bee2/BEE2.4/src/utils.py", line 2
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined

************************************************************************************************


pyinstaller --distpath ../dist/64bit/ --workpath ../build_tmp BEE2.spec
328 INFO: PyInstaller: 4.6
328 INFO: Python: 3.6.9
329 INFO: Platform: Linux-5.4.0-42-generic-x86_64-with-Ubuntu-18.04-bionic
333 INFO: UPX is not available.
Traceback (most recent call last):
  File "/home/tim/.local/bin/pyinstaller", line 11, in <module>
    sys.exit(run())
  File "/home/tim/.local/lib/python3.6/site-packages/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/tim/.local/lib/python3.6/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/tim/.local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/tim/.local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 684, in build
    exec(code, spec_namespace)
  File "BEE2.spec", line 18, in <module>
    import utils
  File "/home/tim/Templates/portal_2/bee2/BEE2.4/src/utils.py", line 2
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

**Comment by TeamSpen210** [comment]
You'll need Python 3.8 or higher.

**Comment by tim631** [comment]
Thank you for information!
Sorry i've missed this information from README.

**Comment by tim631** [comment]
Ok, I compiled BEE2 but the application doesn't work.
log: 
***********************************
./BEE2 
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 26, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "app/__init__.py", line 2, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "tkinter/__init__.py", line 36, in <module>
ModuleNotFoundError: No module named '_tkinter'
[8479] Failed to execute script 'BEE2_launch' due to unhandled exception!
*************************************************************
I have python-tk installed, but I'm still having this error.

**Comment by haydenwalker980** [comment]
Recompile BEE2. If you followed instructions from the README you should remove the folders `build_tmp` and `dist`.

**Comment by haydenwalker980** [comment]
Also be advised that support for Linux isn't good and you will most likely have to make tweaks to some files. Even if you do get it running the app is littered with bugs.
