### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by zeon723** [BEEmod/BEE2.4#1787]
### BEE2 Application Version

4.41.1

### BEE2 Package Version

4.36.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

the neurotoxin_vent is giving me errors i think

### Expected behavior

to use beemod for portal 2

### Steps to reproduce

launch beemod

### Logs and Reports

```shell
Traceback (most recent call last):
  File "app\BEE2.py", line 85, in init_app
  File "packages\__init__.py", line 525, in load_packages
  File "trio\_core\_run.py", line 815, in __aexit__
  File "packages\__init__.py", line 661, in parse_object
  File "packages\item.py", line 493, in parse
  File "packages\item.py", line 779, in parse_item_folder
  File "editoritems.py", line 1017, in parse_one
  File "editoritems.py", line 1177, in _parse_export_block
  File "editoritems.py", line 1476, in _parse_embedded_voxels
srctools.tokenizer.TokenSyntaxError: Unknown volume key "Pos"!
Error occurred on line 65, with file "BEE2_NEUROTOXIN:items/neuro_vent/editoritems.txt".
```

**Comment by Luke18033** [comment]
You need to use the same app and package versions.

**Comment by zeon723** [comment]
i well try

**Comment by zeon723** [comment]
Thanks it works now
