### ISSUE TITLE
clean style goes into temp dictionary again even with a new device

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2.4#1791]
### BEE2 Application Version

4.41.0

### BEE2 Package Version

4.41.0

### Description of the bug

supposed to compile but something happens
![20220104170339_1](https://user-images.githubusercontent.com/63530071/148016303-ac1c8aa2-21e7-4eec-adc3-51fe05116556.jpg)

### Expected behavior

compiles

### Steps to reproduce

who knows how this happened
![20220104170339_1](https://user-images.githubusercontent.com/63530071/148016303-ac1c8aa2-21e7-4eec-adc3-51fe05116556.jpg)

### Logs and Reports

```shell
==== calling mapspawn.nut
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198235887676\autosave.p2c
Parent cvar in client.dll not allowed (r_shadowlod)
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Connection to Steam servers successful.
   VAC secure mode is activated.
Redownloading all lightmaps
Error: Operator stop_entry, unknown sound operator attribute input_start
Unknown command "cl_puzzlemaker_start_previewing"
=======================Trying to GivePlayerPortalgun
=======================Trying to UpgradePlayerPortalgun
Updating sound cache [8850 entries]
Found 8828 sound files on disk
Updated 0 out of 8828 cached files [332.153 msec]
-------
Scaling type: 7
-------
Error: Invalid SoundEntry hash -493561817 in operator play_entry
Error: Invalid SoundEntry hash -493561817 in operator play_entry
Error: Invalid SoundEntry hash -493561817 in operator play_entry
Error: Invalid SoundEntry hash -493561817 in operator play_entry
Error: Invalid SoundEntry hash -493561817 in operator play_entry
Error: Invalid SoundEntry hash -493561817 in operator play_entry
Error: Invalid SoundEntry hash -493561817 in operator play_entry
Error: Invalid SoundEntry hash -493561817 in operator play_entry
Error: Invalid SoundEntry hash -493561817 in operator play_entry
Error: Invalid SoundEntry hash -493561817 in operator play_entry
SAVEGAME:  827.1kb,  282.1kb used by 653 entities (puzzlemaker\76561198235887676\1641200401)
SAVEGAME:   48.3kb,   27.5kb used by 344 entities (puzzlemaker\76561198235887676\1641200401)
SAVEGAME:    1.0kb,    0.0kb used by   0 entities (puzzlemaker\76561198235887676\1641200401)
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
-------
Scaling type: 11
-------
puzzlemaker\76561198235887676\1641200401
Error: Invalid SoundEntry hash -493561817 in operator play_entry
Error: Invalid SoundEntry hash -493561817 in operator play_entry
Error: Invalid SoundEntry hash -493561817 in operator play_entry
Error: Invalid SoundEntry hash -493561817 in operator play_entry
Unknown command "cl_puzzlemaker_start_editing"
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198235887676\autosave.p2c
supersean08 unpaused the game
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (11,15,6)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 92 (ms)

VBSP failed.

[I] cond.core._get_cond_group(): No name for module "precomp.faithplate"!
[I] cond.core._get_cond_group(): No name for module "precomp.fizzler"!
[I] vbsp.main(): BEE2.4.41.0 64-bit VBSP hook initiallised, srctools v2.2.3.
[I] cond.core._get_cond_group(): No name for module "precomp.conditions.marker"!
[I] cond.core._get_cond_group(): No name for module "precomp.conditions.marker"!
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
[W] options.load(): Extra config options: {'voice_pack': 'BEE2_CAVE_80s'}
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 15 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (6 antlines)
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Entry to 1
[I] vbsp.mod_entryexit(): Setting SP Exit to 1
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (223 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[W] packing.pack_list(): Packlist "PACK_PLAYER_CLIP_GLASS" does not exist!
[E] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "compiler_launch.py", line 13, in <module>
  File "vbsp.py", line 1885, in main
  File "precomp\tiling.py", line 1624, in gen_tile_temp
  File "precomp\template_brush.py", line 633, in get_template
  File "precomp\template_brush.py", line 441, in _parse_template
  File "srctools\filesys.py", line 505, in __init__
  File "zipfile.py", line 1239, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/super/AppData/Local/Temp/Rar$EXa20824.40228/packages/clean_style.bee_pack'
[12368] Failed to execute script 'compiler_launch' due to unhandled exception!


[
```

### Additional information

using clean style
(is this fixable or do i have to use another windows account)

**Comment by TeamSpen210** [comment]
You need to extract the app and packages somewhere permanent, not run it directly from a zip (not sure how that even happened). Simply re-export and that’ll fix the issue.
