### ISSUE TITLE
Weird error! "FileNotFoundError: [WinError 2] Not found!"

### ISSUE THREAD

**Issue by RedMatrix1** [BEEmod/BEE2.4#1816]
### BEE2 Application Version

4.41.0 32Bit

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 7 (64bit)

### Logs and Reports

```shell
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 54, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "app\BEE2.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "app\gameMan.py", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "app\backup.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "loadScreen.py", line 241, in <module>
  File "multiprocessing\process.py", line 121, in start
  File "multiprocessing\context.py", line 224, in _Popen
  File "multiprocessing\context.py", line 327, in _Popen
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 81, in __init__
  File "multiprocessing\popen_spawn_win32.py", line 73, in __init__
FileNotFoundError: [WinError 2] Not found!
```

### Additional information

I can't even figure out how to fix it!

**Comment by RedMatrix1** [comment]
Oh, now it's clear... thanks!

**Comment by RedMatrix1** [comment]
I'll check tomorrow and report back

**Comment by RedMatrix1** [comment]
I have no antivirus at all!

**Comment by LautaroL20** [comment]
Are you sure that you do not even have Windows Defender installed in your OS?

**Comment by RedMatrix1** [comment]
Yes it is installed, but I don't know how to allow beemod files

**Comment by LautaroL20** [comment]
Well, you should add the folder where you have installed BEEmod to your antivirus exception list, otherwise you will get this kind of issues. You can do a google search about this.

**Comment by RedMatrix1** [comment]
Tried all the ways, nothing worked. Apparently you have to suffer with the "hammer" (

**Comment by TeamSpen210** [comment]
This is quite a strange error.

**Comment by RedMatrix1** [comment]
I'll try to install Linux and do something there, maybe Windows 7 professional is not suitable (

**Comment by LautaroL20** [comment]
I have Windows 7 and BEEmod works pretty fine for me, so this is not Win 7´s fault.

**Comment by RedMatrix1** [comment]
;(

**Comment by RedMatrix1** [comment]
But I'm the only one with this trouble
