### ISSUE TITLE
BEEMOD Will not run on Debian 11 due to missing `idlelib`

### ISSUE THREAD

**Issue by PugzAreCute** [BEEmod/BEE2.4#1831]
### BEE2 Application Version

Commit 5e07112bb9fd635dcd6a4ec4ee8b5ad8285a1f33

### BEE2 Package Version

'BEE2_v2.4.41.0_packages.zip'

### What operating system are you running on?

Linux

### Logs and Reports

```shell
Need implementation of utils.check_shift()!
[I] BEE2_launch.<module>(): Arguments: ['./BEE2']
[I] BEE2_launch.<module>(): Running "bee2", version 2.4.41.0.dev+5e07112b 64-bit:
[I] localisation.setup(): Language: 'en_IN'
[E] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "app/tk_tools.py", line 21, in <module>
ModuleNotFoundError: No module named 'idlelib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "BEE2_launch.pyw", line 54, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "app/BEE2.py", line 5, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "app/gameMan.py", line 36, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "app/backup.py", line 16, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "app/tk_tools.py", line 26, in <module>
ModuleNotFoundError: No module named 'idlelib'
Process bg_daemon:
Traceback (most recent call last):
  File "app/tk_tools.py", line 21, in <module>
ModuleNotFoundError: No module named 'idlelib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing/process.py", line 315, in _bootstrap
  File "multiprocessing/process.py", line 108, in run
  File "utils.py", line 160, in _run_bg_daemon
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "bg_daemon.py", line 12, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "app/tk_tools.py", line 26, in <module>
ModuleNotFoundError: No module named 'idlelib'
[I] BEE2_config.save(): Saving changes in config "/home/pugzarecute/.config/BEEMOD2/config/config.cfg"!
Traceback (most recent call last):
  File "app/tk_tools.py", line 21, in <module>
ModuleNotFoundError: No module named 'idlelib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "BEE2_launch.pyw", line 54, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "app/BEE2.py", line 5, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "app/gameMan.py", line 36, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "app/backup.py", line 16, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "app/tk_tools.py", line 26, in <module>
ModuleNotFoundError: No module named 'idlelib'
[19869] Failed to execute script 'BEE2_launch' due to unhandled exception!
```

### Additional information

Idle is installed.
Debian 11(bullseye) with kernel 5.10.0-14-amd64
Host is a Dell Inspiron 5000(Dont remember the exact model)
**I COMPILED bee using the compile guide**
A GUI Pops up, stating the same error

**Comment by TeamSpen210** [comment]
I should inline that, but you should be able to install IDLE to get a copy?

**Comment by PugzAreCute** [comment]
I haven't run idle yet so that may be it. I'll test it after I get a working keyboard

**Comment by PugzAreCute** [comment]
Still no luck :( Same bug, I ran idle and recompiled too

**Comment by PugzAreCute** [comment]
I have some more information:
Importing idlelib from python 3.9.2 cli: OK
Importing idlelib from python 2.7.18 CLI : Fail

My Build log: [build.log](https://github.com/BEEmod/BEE2.4/files/8645294/build.log)

**Comment by PugzAreCute** [comment]
Nope.

**Comment by shooter0106** [comment]
Same problem here

**Comment by shooter0106** [comment]
Solved by installing idle-python3.9 package and full rebuild with dist and venv deleting.

**Comment by PugzAreCute** [comment]
Thanks, Ill try it on a debian install today(then close issue)
