### ISSUE TITLE
what does this mean? 

### ISSUE THREAD

**Issue by machonessiebaby** [BEEmod/BEE2.4#1844]
### BEE2 Application Version

Version 4.41.0 64bit

### BEE2 Package Version

Version 4.41.0

### What operating system are you running on?

Windows 11. 64Bit

### Logs and Reports

```shell
Traceback (most recent call last):
  File "app\UI.py", line 1745, in init_windows
  File "configparser.py", line 1257, in __getitem__
KeyError: 'main_window_x'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app\BEE2.py", line 116, in init_app
  File "app\UI.py", line 1756, in init_windows
  File "tkinter\__init__.py", line 2044, in wm_geometry
_tkinter.TclError: bad geometry specifier "294+337"
```

### Additional information

im very unsure about what happened

**Comment by machonessiebaby** [comment]
nevermind it seems to have fixed itself
