### ISSUE TITLE
There was an error building the puzzle

### ISSUE THREAD

**Issue by GameWorldOfficial** [BEEmod/BEE2.4#1845]
### BEE2 Application Version

4.41.0 64bit

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

when trying to build the puzzle it does not build and says that "There was an error building the puzzle"

### Expected behavior

I expect the chamber to build and for it to load

### Steps to reproduce

Step 1. Use default Portal 2 Collapsed Palette and use the clean style with the suggested style settings
Step 2. Use the map I'm trying to make 
Step 3. Try to build and get the error

### Logs and Reports

```shell
in the console it says:

VBSP failed.

[W] BEE2_config.load(): Config "C:\Users\Ehren_zk3ueyp\AppData\Roaming\BEEMOD2\config\item_cust_configs.cfg" not found! Using defaults...
[I] cond.core._get_cond_group(): No name for module "precomp.faithplate"!
[I] cond.core._get_cond_group(): No name for module "precomp.fizzler"!
[W] BEE2_config.load(): Config "C:\Users\Ehren_zk3ueyp\AppData\Roaming\BEEMOD2\config\compile.cfg" not found! Using defaults...
[I] vbsp.main(): BEE2.4.41.0 32-bit VBSP hook initiallised, srctools v2.2.3.
[I] cond.core._get_cond_group(): No name for module "precomp.conditions.marker"!
[I] cond.core._get_cond_group(): No name for module "precomp.conditions.marker"!
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
[W] options.load(): Extra config options: {'voice_pack': 'BEE2_GLADOS_CLEAN'}
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (2 antlines)
[I] vbsp.mod_entryexit(): Using random SP Entry (7)
[I] vbsp.mod_entryexit(): Using random SP Exit (1)
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: True
[I] brushLoc.read_from_map(): Analysed map, filling air... (90 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[W] packing.pack_list(): Packlist "PACK_PLAYER_CLIP_GLASS" does not exist!
[E] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "compiler_launch.py", line 13, in <module>
  File "vbsp.py", line 1890, in main
  File "precomp\texturing.py", line 645, in setup
  File "srctools\game.py", line 115, in get_filesystem
  File "srctools\filesys.py", line 573, in __init__
  File "srctools\vpk.py", line 282, in __init__
  File "srctools\vpk.py", line 392, in load_dirfile
MemoryError
[33552] Failed to execute script 'compiler_launch' due to unhandled exception!
```

### Additional information

I'm using clean style

**Comment by GameWorldOfficial** [comment]
Has this been looked at? I can't use bee2.4 because of this when I uninstall bee2 and verify game files it works and I have no UCPs installed.

**Comment by GameWorldOfficial** [comment]
Fixed just needed to reinstall bee2 manually instead of with the installer

**Comment by LautaroL20** [comment]
> GameWorldOfficial Fixed just needed to reinstall bee2 manually instead of with the installer

BEE2.4 does not have any "installer"... Thats probably BEEmod 2.2.5 alpha.

**Comment by Konclan** [comment]
> > GameWorldOfficial Fixed just needed to reinstall bee2 manually instead of with the installer
> 
> BEE2.4 does not have any "installer"... Thats probably BEEmod 2.2.5 alpha.

Someone made a third party installer but it doesn’t work right. Not our fault.
