### ISSUE TITLE
Crash on startup (Linux)

### ISSUE THREAD

**Issue by mr2meowsYT** [BEEmod/BEE2.4#1904]
### BEE2 Application Version

4.42.0 64

### BEE2 Package Version

4.42.0

### What operating system are you running on?

Linux

### Logs and Reports

```shell
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 63, in <module>
  File "app\BEE2.py", line 224, in start_main
  File "trio\_core\_run.py", line 1995, in start_guest_run
  File "trio\_core\_run.py", line 1816, in setup_runner
  File "trio\_core\_io_windows.py", line 431, in __init__
  File "trio\_core\_io_windows.py", line 207, in _get_underlying_socket
  File "trio\_core\_windows_cffi.py", line 323, in raise_winerror
OSError: [WinError 10045] Windows Error 0x%X
```

**Comment by Luke18033** [comment]
Given you listed your OS as Linux but the error says "windows error", I'd assume you're trying to run it under Wine?
