### ISSUE TITLE
Unable to run with wine/proton on Steam Deck

### ISSUE THREAD

**Issue by Alomfavor** [BEEmod/BEE2.4#1910]
### BEE2 Application Version

Version 4.43.0

### BEE2 Package Version

Version 4.43.0

### What operating system are you running on?

Linux

### Logs and Reports

```shell
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 93, in <module>
  File "app\BEE2.py", line 195, in start_main
  File "trio\_core\_run.py", line 2074, in start_guest_run
  File "trio\_core\_run.py", line 1885, in setup_runner
  File "trio\_core\_io_windows.py", line 431, in __init__
  File "trio\_core\_io_windows.py", line 207, in _get_underlying_socket
  File "trio\_core\_windows_cffi.py", line 323, in raise_winerror
OSError: [WinError 10045] Windows Error 0x%X
```

### Additional information

I'm attempting to run the Bee2 executable using wine but keep getting this error. Any idea if this can be fixed? I'd love to be able to use Bee on the steam deck.

**Comment by Alomfavor** [comment]
dunno if this helps or complicates things but heres the full of whats going on in the terminal when trying to run the bee2 executable

Config "C:\users\deck\AppData\Roaming\BEEMOD2\config\packages.cfg" not found! Us
ing defaults...
[I] BEE2_launch.<module>(): Arguments: ['Z:\\home\\deck\\Desktop\\BEE2_v4.43.0_w
in64\\BEE2.exe']
[I] BEE2_launch.<module>(): Running "bee2", version 2.4.43.0 64-bit:
[I] localisation.setup(): Language: 'en_US'
[W] BEE2_config.load(): Config "C:\users\deck\AppData\Roaming\BEEMOD2\config\ite
m_configs.cfg" not found! Using defaults...
[W] BEE2_config.load(): Config "C:\users\deck\AppData\Roaming\BEEMOD2\config\ite
m_cust_configs.cfg" not found! Using defaults...
[W] BEE2_config.load(): Config "C:\users\deck\AppData\Roaming\BEEMOD2\config\gam
es.cfg" not found! Using defaults...
[E] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 93, in <module>
  File "app\BEE2.py", line 195, in start_main
  File "trio\_core\_run.py", line 2074, in start_guest_run
  File "trio\_core\_run.py", line 1885, in setup_runner
  File "trio\_core\_io_windows.py", line 431, in __init__
  File "trio\_core\_io_windows.py", line 207, in _get_underlying_socket
  File "trio\_core\_windows_cffi.py", line 323, in raise_winerror
OSError: [WinError 10045] Windows Error 0x%X
Config "C:\users\deck\AppData\Roaming\BEEMOD2\config\packages.cfg" not found! Us
ing defaults...
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 93, in <module>
  File "app\BEE2.py", line 195, in start_main
  File "trio\_core\_run.py", line 2074, in start_guest_run
  File "trio\_core\_run.py", line 1885, in setup_runner
  File "trio\_core\_io_windows.py", line 431, in __init__
  File "trio\_core\_io_windows.py", line 207, in _get_underlying_socket
  File "trio\_core\_windows_cffi.py", line 323, in raise_winerror
OSError: [WinError 10045] Windows Error 0x%X

**Comment by turtlegarden** [comment]
I'm also recieving this same error, but not on a Steam Deck:

![(error message present in beginning of issue)](https://github.com/BEEmod/BEE2.4/assets/52264162/58b846f2-f38b-4e7c-ac29-b75facb4ab27)

~~Sad it still doesn't work on linux, would be nice to be able to use BEE2 on linux...~~
Seems that [this](https://github.com/BEEmod/BEE2.4/blob/f2e4a629c4373ba283473fdbcbe469232fdf2de7/src/app/BEE2.py#LL195C1-L201C6) is causing the error, so it's probably a trio error. Poking around in trio based on the error message, I found [this function](https://github.com/python-trio/trio/blob/bec7cc61fade8ef858aae9a3df5d740945d87429/trio/_core/_io_windows.py#L189), which is probably the cause of the error. I'll try to find a solution to that socket error.
