### ISSUE TITLE
Issue when starting app

### ISSUE THREAD

**Issue by janKeje** [BEEmod/BEE2.4#1914]
### BEE2 Application Version

4.43.0

### BEE2 Package Version

4.35.0

### Description of the bug

Whenever i chose the portal folder in my steam folder, it wouldn't compile properly. And it would not work.

### Expected behavior

I expected it to show me the  inside of the application properly, showing all the testing elements and such
![image](https://user-images.githubusercontent.com/117609906/211691143-22beb688-da01-416c-b959-b033c6c59e05.png)

### Steps to reproduce

1. Open BEE2.exe
2. Select Portal 2 from steam common folder
3. Compile Faliure

### Logs and Reports

```shell
Traceback (most recent call last):
  File "app\BEE2.py", line 59, in init_app
  File "trio\_core\_run.py", line 850, in __aexit__
  File "packages\__init__.py", line 589, in load_packages
  File "trio\_core\_run.py", line 850, in __aexit__
  File "packages\__init__.py", line 599, in parse_type
  File "trio\_core\_run.py", line 850, in __aexit__
  File "packages\__init__.py", line 725, in parse_object
  File "packages\item.py", line 554, in parse
  File "trio\_core\_run.py", line 850, in __aexit__
  File "utils.py", line 509, in _task
  File "packages\item.py", line 862, in parse_item_folder
  File "trio\_core\_run.py", line 850, in __aexit__
  File "utils.py", line 509, in _task
  File "utils.py", line 503, in task
  File "trio\_threads.py", line 215, in to_thread_run_sync
  File "trio\_core\_traps.py", line 166, in wait_task_rescheduled
  File "outcome\_impl.py", line 138, in unwrap
  File "trio\_threads.py", line 161, in do_release_then_return_result
  File "outcome\_impl.py", line 138, in unwrap
  File "trio\_threads.py", line 175, in worker_fn
  File "packages\item.py", line 844, in _parse_items
  File "editoritems.py", line 1048, in parse_one
  File "editoritems.py", line 1202, in _parse_export_block
  File "editoritems.py", line 1503, in _parse_embedded_voxels
srctools.tokenizer.TokenSyntaxError: Unknown volume key "Pos"!
Error occurred on line 65, with file "BEE2_NEUROTOXIN:items/neuro_vent/editoritems.txt".
```

**Comment by FrozenDragon0** [comment]
Update your packages version, your current one is very out of date.
