### ISSUE TITLE
idk why this happens, i recently downloaded the mod

### ISSUE THREAD

**Issue by Emaaaaaaaaa** [BEEmod/BEE2.4#1944]
Traceback (most recent call last):
  File "app\BEE2.py", line 83, in init_app
  File "trio\_core\_run.py", line 850, in __aexit__
  File "app\UI.py", line 1708, in init_windows
  File "app\UI.py", line 1675, in style_select_callback
AssertionError: Style ID must be provided

**Comment by Emaaaaaaaaa** [comment]
i reinstalled and fixed xd
