### ISSUE TITLE
No module named 'hammeraddons'

### ISSUE THREAD

**Issue by marvin1099** [BEEmod/BEE2.4#1952]
### BEE2 Application Version

BEE2.43.0 64bit

### BEE2 Package Version

not shure

### What operating system are you running on?

Linux

### Description of the bug

so i ran on my arch linux box (garuda linux):

```
git clone --recurse-submodules https://github.com/BEEmod/BEE2.4.git
cd BEE2.4
git submodule update --init
cd src/
pyinstaller --distpath ../dist/64bit/ --workpath ../build_tmp compiler.spec
```

so far there were no errors
then i ran:
     ``pyinstaller --distpath ../dist/64bit/ --workpath ../build_tmp BEE2.spec``
this gave this output and failed, any idea thats up with that?
```
118 INFO: PyInstaller: 5.11.0
118 INFO: Python: 3.11.3
119 INFO: Platform: Linux-6.3.2-zen1-1-zen-x86_64-with-glibc2.37
120 INFO: UPX is not available.
263 INFO: vcs returned tag 2.4.43.0
264 INFO: tag2version returned version 2.4.43.0
264 INFO: next-version returned version 2.5.0
264 INFO: VCS state is 'distance-dirty'; formatting version
264 INFO: Final version: 2.4.43.0.dev+f2e4a629
Need implementation of utils.check_shift()!
Reading translations from source...
Done!
Updating translations:
> es
> fr
> ja
> pl
> ru
> zh_cn
Loading FGD database...
Traceback (most recent call last):
File "/usr/bin/pyinstaller", line 8, in <module>
sys.exit(_console_script_run())
^^^^^^^^^^^^^^^^^^^^^
File "/home/marvin/.local/lib/python3.11/site-packages/PyInstaller/__main__.py", line 194, in _console_script_run
run()
File "/home/marvin/.local/lib/python3.11/site-packages/PyInstaller/__main__.py", line 180, in run
run_build(pyi_config, spec_file, **vars(args))
File "/home/marvin/.local/lib/python3.11/site-packages/PyInstaller/__main__.py", line 61, in run_build
PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
File "/home/marvin/.local/lib/python3.11/site-packages/PyInstaller/building/build_main.py", line 1006, in main
build(specfile, distpath, workpath, clean_build)
File "/home/marvin/.local/lib/python3.11/site-packages/PyInstaller/building/build_main.py", line 928, in build
exec(code, spec_namespace)
File "BEE2.spec", line 154, in <module>
build_fgd()
File "BEE2.spec", line 122, in build_fgd
from hammeraddons import unify_fgd, __version__ as version
ModuleNotFoundError: No module named 'hammeraddons'
```
hopefully someone has some inside on this, thanks

### Expected behavior

I waned it to compile the BEEmod app  

### Steps to reproduce

Described in bug description

**Comment by TeamSpen210** [comment]
Turns out I messed up the code that adds `hammeraddons` to the path for it to load in `master`, but it's fixed in `dev`. Try compiling that instead.

**Comment by marvin1099** [comment]
I have tried to compile the dev, version and it worked just fine.
Thanks for the help
