### ISSUE TITLE
app won't open

### ISSUE THREAD

**Issue by thad4002** [BEEmod/BEE2.4#1960]
### BEE2 Application Version

4.43.0 32bit

### BEE2 Package Version

4.43.0

### What operating system are you running on?

Windows 7 (64bit)

### Logs and Reports

```shell
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 92, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "app\BEE2.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "app\gameMan.py", line 41, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "app\backup.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "loadScreen.py", line 259, in <module>
  File "multiprocessing\process.py", line 121, in start
  File "multiprocessing\context.py", line 224, in _Popen
  File "multiprocessing\context.py", line 327, in _Popen
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 72, in __init__
  File "multiprocessing\popen_spawn_win32.py", line 73, in __init__
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect
```

**Comment by Luke18033** [comment]
Where do you have it installed?

**Comment by thad4002** [comment]
C:\BEE2.4

**Comment by thad4002** [comment]
now it's this:
`Traceback (most recent call last):
  File "BEE2_launch.pyw", line 92, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "app\BEE2.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "app\gameMan.py", line 41, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "app\backup.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "loadScreen.py", line 259, in <module>
  File "multiprocessing\process.py", line 121, in start
  File "multiprocessing\context.py", line 224, in _Popen
  File "multiprocessing\context.py", line 327, in _Popen
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 72, in __init__
  File "multiprocessing\popen_spawn_win32.py", line 73, in __init__
FileNotFoundError: [WinError 2] The system cannot find the file specified
`

**Comment by TeamSpen210** [comment]
You might want to move it elsewhere, or change the security settings for `C:/BEE2/`. Stuff at the root of the drive defaults to rather restrictive settings, so it might not be able to access the things it needs to.

**Comment by thad4002** [comment]
i moved it to a new folder on my desktop, but it shows this message instead
![image](https://github.com/BEEmod/BEE2.4/assets/49796470/e93b76b7-e30f-4f23-b080-90836b69f90e)

**Comment by TeamSpen210** [comment]
The whole folder, or just the EXE? It needs the rest of the stuff to work.

**Comment by thad4002** [comment]
the whole folder
