### ISSUE TITLE
Beemod dosent open

### ISSUE THREAD

**Issue by eytangut** [BEEmod/BEE2.4#1962]
### BEE2 Application Version

4.43 64bit

### BEE2 Package Version

4.43

### What operating system are you running on?

windows

### Logs and Reports

```shell
when i open beemod i see the following error messege:
Traceback (most recent call last):
  File "app\BEE2.py", line 83, in init_app
  File "trio\_core\_run.py", line 850, in __aexit__
  File "app\UI.py", line 1708, in init_windows
  File "app\UI.py", line 1675, in style_select_callback
AssertionError: Style ID must be provided

if i try to click on something, i see another error:
Traceback (most recent call last):
  File "app\BEE2.py", line 83, in init_app
  File "trio\_core\_run.py", line 850, in __aexit__
  File "app\UI.py", line 1708, in init_windows
  File "app\UI.py", line 1675, in style_select_callback
AssertionError: Style ID must be provided
Traceback (most recent call last):
  File "trio\_core\_run.py", line 1291, in guest_tick
  File "outcome\_impl.py", line 113, in send
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app\paletteUI.py", line 77, in <lambda>
  File "app\__init__.py", line 137, in background_run
  File "trio\_core\_run.py", line 1038, in start_soon
AttributeError: 'RunContext' object has no attribute 'runner'
```

**Comment by TheProtoToaster** [comment]
download it again?

**Comment by TeamSpen210** [comment]
I've fixed this for the next release, but until then this seems to be a problem with the saved state. Try opening a Windows Explorer window, pasting `%APPDATA%/BEEMOD/` into the address bar, then renaming `config.vdf` to force that to reset to default values. Specifically you could alternatively manually set the `LastSelected` -> `Style` option to `BEE2_CLEAN`, which would also resolve it.
