### ISSUE TITLE
Cant download

### ISSUE THREAD

**Issue by tanoluciano** [BEEmod/BEE2.4#1989]
### BEE2 Application Version

4.43.0 64 bit

### BEE2 Package Version

4.43.0

### What operating system are you running on?

Windows 11

### Logs and Reports

```shell
Traceback (most recent call last):
  File "trio\_core\_run.py", line 850, in __aexit__
  File "app\localisation.py", line 401, in load_aux_langs
  File "trio\_core\_run.py", line 850, in __aexit__
  File "app\localisation.py", line 391, in game_lang
  File "trio\_path.py", line 62, in wrapper
  File "trio\_threads.py", line 215, in to_thread_run_sync
  File "trio\_core\_traps.py", line 166, in wait_task_rescheduled
  File "outcome\_impl.py", line 138, in unwrap
  File "trio\_threads.py", line 161, in do_release_then_return_result
  File "outcome\_impl.py", line 138, in unwrap
  File "trio\_threads.py", line 175, in worker_fn
  File "pathlib.py", line 1267, in read_text
  File "codecs.py", line 322, in decode
  File "encodings\utf_16.py", line 61, in _buffer_decode
UnicodeDecodeError: 'utf-16-le' codec can't decode bytes in position 21530-21531: illegal UTF-16 surrogate
```

### Additional information

Im in Windows 11 64 bit, here is a video (im spanish so sorry if english bad)

https://github.com/BEEmod/BEE2.4/assets/148599541/171231ca-7a1f-4e52-bb04-6f49d89b82ec

**Comment by TeamSpen210** [comment]
The cause of the issue here is that BEE’s trying to load Portal 2’s Spanish translation files, but failing because the files have various errors. Next version will handle this properly, but until then you could manually force it to run with English:

* Create a shortcut to BEE.exe.
* Open the properties, then in the first text box with the path to the EXE, add at the end ` lang=en_us` (with a space before it).

**Comment by tanoluciano** [comment]
Thanks mate.. Now im closing the issue 
NOW IM GOING TO PLAY MY FAVOURITE MOD :D
