### ISSUE TITLE
BEEmod crash: PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by CGYProd** [BEEmod/BEE2.4#1991]
### BEE2 Application Version

2.4.43.0

### BEE2 Package Version

2.4.43.0

### What operating system are you running on?

Windows 10 (64bit)

### Logs and Reports

```shell
Traceback (most recent call last):
  File "trio\_core\_run.py", line 850, in __aexit__
  File "app\UI.py", line 757, in export_editoritems
  File "app\gameMan.py", line 729, in export
  File "packages\editor_sound.py", line 31, in export
  File "app\gameMan.py", line 413, in add_editor_sounds
  File "srctools\__init__.py", line 481, in __enter__
  File "srctools\__init__.py", line 474, in make_tempfile
PermissionError: [Errno 13] Permission denied: 'c:\\program files\\portal 2\\portal2_dlc2\\scripts\\tmp_1'
```

### Additional information

Pls help me! :(
**I have an error when trying to export the palette to the game: 
Traceback (most recent call last):
  File "trio\_core\_run.py", line 850, in __aexit__
  File "app\UI.py", line 757, in export_editoritems
  File "app\gameMan.py", line 729, in export
  File "packages\editor_sound.py", line 31, in export
  File "app\gameMan.py", line 413, in add_editor_sounds
  File "srctools\__init__.py", line 481, in __enter__
  File "srctools\__init__.py", line 474, in make_tempfile
PermissionError: [Errno 13] Permission denied: 'c:\\program files\\portal 2\\portal2_dlc2\\scripts\\tmp_1'**

Tell me what to install/ remove or what to do at all?

**Comment by TeamSpen210** [comment]
Do you have the game open perhaps? Could also be security permission settings on your P2 folder, BEE might not be allowed to edit it

**Comment by CGYProd** [comment]
> Do you have the game open perhaps? Could also be security permission settings on your P2 folder, BEE might not be allowed to edit it

No, the game is closed, so maybe the problem is that "BEE might not be allowed to edit it". How to make sure that this is the problem, and get rid of it?

**Comment by vrad-exe** [comment]
Are you using a cracked copy of portal 2? The `steamapps` folder is noticeably missing from the game's install path...

**Comment by vrad-exe** [comment]
Closing due to no response
