### ISSUE TITLE
BEE2.4 ARCTIFACT BUILD 32 BIT: The application will crash on launch.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#1997]
### BEE2 Application Version

beemod2_210741c9d17f3ada014d665723b84a95bb8dc764_win32

### BEE2 Package Version

beemod2_a15f14901c413a13e624b750e33947724b9b04c9_packages

### What operating system are you running on?

Windows 7 (64bit)

### Logs and Reports

```shell
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 92, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "app\BEE2.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "app\music_conf.py", line 29, in <module>
  File "typing.py", line 261, in inner
  File "typing.py", line 886, in __class_getitem__
  File "typing.py", line 886, in <genexpr>
  File "typing.py", line 149, in _type_check
TypeError: Parameters to generic types must be types. Got Ellipsis.
```

### Additional information

Not sure if this only affects the 32 bit version or it also happens with the 64 bit as well...

**Comment by TeamSpen210** [comment]
Should now be fixed.

**Comment by LautaroL20** [comment]
It is fixed, but now I have found new bugs which Ill going to report in some minutes.
