### ISSUE TITLE
BEE2.4 ARTIFACT BUILD: The application will crash when uninstalling from selected game.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#1999]
### BEE2 Application Version

beemod2_6095b208c79342ae7ad43f2fbc4353ab1f2b4318_win32

### BEE2 Package Version

beemod2_a15f14901c413a13e624b750e33947724b9b04c9_packages

### What operating system are you running on?

Windows 7 (64bit)

### Logs and Reports

```shell
[ERROR] BEE2.done_callback(): Trio exited with exception
  + Exception Group Traceback (most recent call last):
  |   File "app\BEE2.py", line 174, in app_main
  |   File "trio\_core\_run.py", line 948, in __aexit__
  | trio.NonBaseMultiError: FileExistsError(17, 'No se puede crear un archivo que ya existe')
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "app\gameMan.py", line 1415, in remove_game
    |   File "app\gameMan.py", line 648, in clear_cache
    |   File "packages\style_vpk.py", line 114, in clear_files
    |   File "os.py", line 223, in makedirs
    | FileExistsError: [WinError 183] No se puede crear un archivo que ya existe: 'D:\\Steam\\Steamapps\\common\\Portal 2\\portal2_dlc3\\pak01_dir.vpk'
    +------------------------------------
[ERROR] __init__.tk_error(): Uncaught Tk Exception:
  + Exception Group Traceback (most recent call last):
  |   File "trio\_core\_run.py", line 948, in __aexit__
  | trio.NonBaseMultiError: FileExistsError(17, 'No se puede crear un archivo que ya existe')
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "app\gameMan.py", line 1415, in remove_game
    |   File "app\gameMan.py", line 648, in clear_cache
    |   File "packages\style_vpk.py", line 114, in clear_files
    |   File "os.py", line 223, in makedirs
    | FileExistsError: [WinError 183] No se puede crear un archivo que ya existe: 'D:\\Steam\\Steamapps\\common\\Portal 2\\portal2_dlc3\\pak01_dir.vpk'
    +------------------------------------
```

**Comment by LautaroL20** [comment]
This issue still happens as well as others.
