### ISSUE TITLE
BEE2.4 ARTIFACT BUILD: The application will crash when trying to export palette to the game (Probably related to issue: #1999 ?)

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#2000]
### BEE2 Application Version

beemod2_6095b208c79342ae7ad43f2fbc4353ab1f2b4318_win32

### BEE2 Package Version

beemod2_a15f14901c413a13e624b750e33947724b9b04c9_packages

### What operating system are you running on?

Windows 7 (64bit)

### Logs and Reports

```shell
[ERROR] BEE2.done_callback(): Trio exited with exception
  + Exception Group Traceback (most recent call last):
  |   File "app\BEE2.py", line 174, in app_main
  |   File "trio\_core\_run.py", line 948, in __aexit__
  | trio.NonBaseMultiError: FileExistsError(17, 'No se puede crear un archivo que ya existe')
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "app\UI.py", line 767, in export_editoritems
    |   File "app\gameMan.py", line 753, in export
    |   File "packages\style_vpk.py", line 166, in export
    |   File "packages\style_vpk.py", line 59, in find_folder
    |   File "pathlib.py", line 1359, in rename
    | FileExistsError: [WinError 183] No se puede crear un archivo que ya existe: 'D:\\Steam\\Steamapps\\common\\Portal 2\\portal2_dlc3\\pak01_dir.vpk' -> 'D:\\Steam\\
```

### Additional information

This issue started to happen after issue: #1999

**Comment by LautaroL20** [comment]
I have downloaded the latest arctifact stuff and this issue always happens, even if I recet the "packages cache", when exporting the pallete, always crash so I will need to wait for a fix.
