### ISSUE TITLE
BEE2.4 ARTIFACT BUILD: The application sometimes can crash when launching.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#2001]
Not all the time, but the app can crash when launching with the following error:

![Image](https://github.com/BEEmod/BEE2.4/assets/12244376/7ab1f090-f6ca-4778-8271-8ec7d305a40b)
_______________________________________

**Artifact app**: beemod2_6095b208c79342ae7ad43f2fbc4353ab1f2b4318_win32
**Artifact packages**: beemod2_a15f14901c413a13e624b750e33947724b9b04c9_packages

**Comment by LautaroL20** [comment]
Now I have tried to launch the public BEEmod release and I have experienced this crash as well:

```
Traceback (most recent call last):
  File "app\BEE2.py", line 116, in init_app
  File "app\UI.py", line 1812, in init_windows
  File "BEE2_config.py", line 77, in read_settings
  File "BEE2_config.py", line 57, in apply_settings
  File "app\selector_win.py", line 156, in load_handler
  File "app\selector_win.py", line 114, in parse
  File "app\selector_win.py", line 114, in <dictcomp>
  File "srctools\property_parser.py", line 494, in find_children
  File "srctools\property_parser.py", line 478, in find_all
  File "srctools\property_parser.py", line 754, in __iter__
ValueError: Can't iterate through Property('_version', '1') without children!
[INFO] UI.quit_application(): Shutting down application.
```

**Comment by TeamSpen210** [comment]
This traceback seems to suggest a real old version, are there any extra files in the install folder or something that it could be loading?

**Comment by LautaroL20** [comment]
> TeamSpen2010 said: "This traceback seems to suggest a real old version"

When this crash happened the first time, I was using the arctifact app and packages that are mentioned in this post desc.

**Comment by vrad-exe** [comment]
Does this work now if you download the latest build? Also I guess make sure to delete the previous build beforehand or install it to a different location to be sure there are no old files left over

**Comment by LautaroL20** [comment]
> vrad-exe said: "Does this work now if you download the latest build?"

This is my situation... unfortunately, some hardware pieces from my PC died recently, so until I replace these, will not be able to test anything. Right now I am using my phone which is trash btw, so I am not sure when I am going to be able to repair my PC... I think that when I finally get my PC ready, I will install Windows 10, because I must admit that Win 7 is definitelly dead (Steam, Python, new games, all this no longer has support right now) .
