### ISSUE TITLE
Linux Puzzlemake export problems

### ISSUE THREAD

**Issue by marvin1099** [BEEmod/BEE2.4#2004]
### BEE2 Application Version

2.4.43.0.dev+a2e7311d 64-bit

### BEE2 Package Version

BEE2_v4.43.0

### What operating system are you running on?

Arch Linux (Garuda Linux)

### Description of the bug

So when trying to build the puzzle in Linux it sends out a error that seems to be related to bee2

### Expected behavior

I expect the puzzle to build the puzzle

### Steps to reproduce

1. You build bee on linux
2. For that i created a python venv so i can install all reqirements (on linux you install python librarys in venv if they dont exist in the pacage manager)
3. If you get it to work run BEE2 file
4. Set your preset and export to game
5. Since the portal 2 puzzlemaker is broken in linux you also need to run "download_depot d 620 661 2854055004190207766" in the steam console and than copy the %depotfolder%/bin/linux32/filesystem_stdio.so to %portalforder%/bin/linux32/filesystem_stdio.so
6. Next create or open a puzzlemaker laver and click run 

### Logs and Reports

```shell
VRAD failed.

ERROR: ld.so: object '/mnt/Standart-Festplatte/Marvin/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/mnt/Standart-Festplatte/Marvin/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Need implementation of utils.check_shift()!
[I] vrad.main(): BEE2.4.43.0.dev+a2e7311d 64-bit VRAD hook initiallised, srctools v2.3.15, Hammer Addons v(unknown)
[I] vrad.main(): Map path is /mnt/Standart-Festplatte/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content/maps/preview.bsp
[I] vrad.main(): Loading Settings...
[I] vrad.main(): Reading BSP
[I] vrad.main(): Map status: is_peti=True, is_preview=True light_args=FAST
[I] vrad.main(): Done!
[I] vrad.main(): Reading soundscripts...
[W] packlist.load_soundscript_manifest(): Soundscript "scripts/game_sounds_music_A1.txt" does not exist!
[W] packlist.load_soundscript_manifest(): Soundscript "scripts/game_sounds_music_A2.txt" does not exist!
[W] packlist.load_soundscript_manifest(): Soundscript "scripts/game_sounds_music_A3.txt" does not exist!
[W] packlist.load_soundscript_manifest(): Soundscript "scripts/game_sounds_music_A4.txt" does not exist!
[W] packlist.load_soundscript_manifest(): Soundscript "scripts/game_sounds_BR_world.txt" does not exist!
[I] vrad.main(): Reading particles....
[I] vrad.main(): Loading transforms...
[E] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "compiler_launch.py", line 37, in <module>
  File "trio/_core/_run.py", line 2251, in run
  File "vrad.py", line 238, in main
  File "vrad.py", line 45, in load_transforms
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "transforms_stub.py", line 2, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "/mnt/Standart-Festplatte/Marvin/Downloads/Build-Bee2/BEE2.4/hammeraddons/transforms/geocable.py", line 25, in <module>
    from hammeraddons.mdl_compiler import ModelCompiler
ModuleNotFoundError: No module named 'hammeraddons.mdl_compiler'
[73552] Failed to execute script 'compiler_launch' due to unhandled exception!


GetCharRGBA - selected_face->glyph->bitmap.width is 0 for ch:32 Univers LT Std
```

### Additional information

The problem might be related to the venv environment not sure.
Any help is appreciated.

**Comment by TeamSpen210** [comment]
You could try removing `hammeraddons/transforms/geocable.py`, it's not required at all.

**Comment by marvin1099** [comment]
Oh I forgot that this has worked, so im going to close this issue.
