### ISSUE TITLE
Bee2 crashes on start

### ISSUE THREAD

**Issue by Wendy4224** [BEEmod/BEE2.4#2015]
### BEE2 Application Version

Version 4.44.1

### BEE2 Package Version

Version 2.4.44.0

### What operating system are you running on?

Windows 7 (64bit)

### Logs and Reports

```shell
Traceback (most recent call last):
  File "pyglet\media\codecs\wmf.py", line 836, in __init__
  File "_ctypes/callproc.c", line 998, in GetResult
OSError: [WinError -2147417850] Изменение режима для потока после его установки невозможно

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app\sound.py", line 233, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "pyglet\media\__init__.py", line 143, in <module>
  File "pyglet\media\codecs\__init__.py", line 97, in add_default_media_codecs
  File "pyglet\util.py", line 172, in add_decoders
  File "pyglet\media\codecs\wmf.py", line 892, in get_decoders
  File "pyglet\media\codecs\wmf.py", line 838, in __init__
  File "warnings.py", line 112, in _showwarnmsg
  File "warnings.py", line 30, in _showwarnmsg_impl
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 68-76: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1088, in emit
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 231-239: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "BEE2_launch.pyw", line 92, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "app\BEE2.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "app\sound.py", line 240, in <module>
  File "logging\__init__.py", line 1829, in exception
  File "srctools\logger.py", line 137, in log
  File "logging\__init__.py", line 1589, in _log
  File "logging\__init__.py", line 1599, in handle
  File "logging\__init__.py", line 1661, in callHandlers
  File "logging\__init__.py", line 954, in handle
  File "logging\__init__.py", line 1187, in emit
  File "logging\__init__.py", line 1093, in emit
  File "logging\__init__.py", line 1007, in handleError
  File "traceback.py", line 105, in print_exception
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 32-40: character maps to <undefined>
```

**Comment by vrad-exe** [comment]
Seems like this might have to do with your selected language? As a workaround you can try forcing the language to English by making a shortcut to `BEE2.exe` and adding a space followed by `bee2 lang=en` at the end of the target path, then running that.
