### ISSUE TITLE
Assistance Needed to Run Bee2 Mod for Portal 2 on Android via Termux-box Emulator

### ISSUE THREAD

**Issue by F1xTrack** [BEEmod/BEE2.4#2030]
### BEE2 Application Version

4.44.1 64bit

### BEE2 Package Version

2.4.44.0

### What operating system are you running on?

Other

### Logs and Reports

```shell
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 93, in <module>
  File "app\BEE2.py", line 195, in start_main
  File "trio\_core\_run.py", line 2074, in start_guest_run
  File "trio\_core\_run.py", line 1885, in setup_runner
  File "trio\_core\_io_windows.py", line 431, in init
  File "trio\_core\_io_windows.py", line 207, in _get_underlying_socket
  File "trio\_core\_windows_cffi.py", line 323, in raise_winerror
OSError: [WinError 10045] Windows Error 0x%X
```

### Additional information

I hope this message finds you well. I'm reaching out today as I require some assistance with a specific issue I'm facing while trying to run Bee2 Mod for Portal 2 on my Android device using Termux-box emulator and the embedded Wine 0.2 application which allows running .exe files.

The games and programs generally run well in this setup, but when I attempt to run Bee2 Mod for Portal 2, I encounter an error and the program fails to launch.
From my understanding, this seems to be a specific Windows error related to network operations which might be due to the emulation of Windows on Android and certain limitations that come with it.

I have tried checking my network settings, looking for any operations that might have been blocked, and updating my emulator and the Wine 0.2 application to the latest versions but to no avail.

If any of you could shed some light on this issue and possibly guide me towards a viable solution, I would greatly appreciate it. Maybe there are other emulators that could handle such network requests more efficiently, or perhaps there are workarounds in the current setup that I'm not aware of.

Just to add, I apologise if any part of this message is unclear as English is not my first language.

Once again, thank you in advance for any assistance provided.

**Comment by vrad-exe** [comment]
This looks like the same issue as #1992, it seems to break when running under Wine for some reason.
