### ISSUE TITLE
BEE2 crashes instantly when launching

### ISSUE THREAD

**Issue by rech2020** [BEEmod/BEE2.4#2037]
### BEE2 Application Version

4.44.1

### BEE2 Package Version

4.44.0

### What operating system are you running on?

Windows 7 (32bit)

### Logs and Reports

```shell
Failed to execute script 'pyi_rth_pkgres' due to unhandled exception:
DLL load failed while importing pyexpat: Не найден указанный модуль.

Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 200, in <module>
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 36, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "pkg_resources\__init__.py", line 32, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "plistlib.py", line 65, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "xml\parsers\expat.py", line 4, in <module>
ImportError: DLL load failed while importing pyexpat: Не найден указанный модуль.
```
```


### Additional information

i have python 3.8 (32-bit) installed but i don't think that changes anything

**Comment by TeamSpen210** [comment]
Where did you unzip the app? Anything else in that folder?

**Comment by rech2020** [comment]
I have unzipped it on disk F, the same disk steam is located on

**Comment by rech2020** [comment]
I have unzipped it on disk F, the same disk steam is located on

**Comment by rech2020** [comment]
and obviously i unzipped it into its own folder

**Comment by rech2020** [comment]
hello? anybody here?
