### ISSUE TITLE
Bee Mod Not Opening

### ISSUE THREAD

**Issue by OmegaFloweyAdmin** [BEEmod/BEE2.4#2047]
### BEE2 Application Version

4.44.1

### BEE2 Package Version

v4.40.0

### What operating system are you running on?

Other

### Description of the bug

It doesn't open, it just gives me an error message

### Expected behavior

I expect bee to open and run without error

### Steps to reproduce

Step 1. Get a Mac with [CrossOver](https://www.codeweavers.com/crossover)
Step 2. Download BeeMod2 and it's packages
Step 3. Run Bee2 with [CrossOver](https://www.codeweavers.com/crossover)

### Logs and Reports

```shell
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 93, in <module>
  File "app\BEE2.py", line 214, in start_main
  File "trio\_core\_run.py", line 2339, in start_guest_run
  File "trio\_core\_run.py", line 2133, in setup_runner
  File "trio\_core\_io_windows.py", line 456, in __init__
  File "trio\_core\_io_windows.py", line 325, in _get_underlying_socket
  File "trio\_core\_windows_cffi.py", line 534, in raise_winerror
OSError: [WinError 10045] Windows Error 0x%X
```

### Additional information

I'm Using a Mac Air M1 2020, and am running BeeMod2 with [CrossOver](https://www.codeweavers.com/crossover)

**Comment by Sirinchocolate** [comment]
Mac os hasn't been supported for a while now. You won't get any help from the devs.
