### ISSUE TITLE
BEEmod Crashes after typing in name of game (BadZipFile)

### ISSUE THREAD

**Issue by TylerTheGuy298** [BEEmod/BEE2.4#2049]
### BEE2 Application Version

4..44.1 64-bit

### BEE2 Package Version

4.44.0

### What operating system are you running on?

Windows 11

### Logs and Reports

```shell
+ Exception Group Traceback (most recent call last):
  |   File "trio\_core\_run.py", line 963, in __aexit__
  | trio.NonBaseMultiError: <MultiError: <MultiError: BadZipFile('File is not a zip file')>>
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "app\BEE2.py", line 173, in app_main
    |   File "app\BEE2.py", line 63, in init_app
    |   File "trio\_core\_run.py", line 963, in __aexit__
    | trio.NonBaseMultiError: <MultiError: BadZipFile('File is not a zip file')>
    +-+---------------- 1 ----------------
      | Exception Group Traceback (most recent call last):
      |   File "packages\__init__.py", line 576, in load_packages
      |   File "trio\_core\_run.py", line 963, in __aexit__
      | trio.NonBaseMultiError: BadZipFile('File is not a zip file')
      +-+---------------- 1 ----------------
        | Traceback (most recent call last):
        |   File "packages\__init__.py", line 493, in find_packages
        |   File "trio\_threads.py", line 400, in to_thread_run_sync
        |   File "outcome\_impl.py", line 213, in unwrap
        |   File "trio\_threads.py", line 327, in do_release_then_return_result
        |   File "outcome\_impl.py", line 213, in unwrap
        |   File "trio\_threads.py", line 346, in worker_fn
        |   File "srctools\filesys.py", line 563, in __init__
        |   File "zipfile.py", line 1302, in __init__
        |   File "zipfile.py", line 1369, in _RealGetContents
        | zipfile.BadZipFile: File is not a zip file
        +------------------------------------
```

### Additional information

I have tried uninstalling and reinstalling BEEmod.

**Comment by Sirinchocolate** [comment]
You need to unzip the zip files, into their .pack forms. And drop them in the packages folder.

This line only gets triggered with well, a bad zip file.

If you are using any user created/ 3rd party packages, I would reccomend not unzipping those in most cases. As the .pack extension rarely gets used by 3rd party/user created content.

**Comment by TylerTheGuy298** [comment]
There’s no zip files to unzip, and I have the normal  BEE2 packages already unzipped and in the packages folder, the only zip file I can find is a “base_library.zip” file I found but doesn’t have any connection to error.

**Comment by TylerTheGuy298** [comment]
I don’t want to close the issue

**Comment by Sirinchocolate** [comment]
It is giving multiple bad zip file errors. Did you copy the downloaded zip, into the packages folder. And unzip it from there, into there? In that case, please remove the still zipped downloaded packages folder. From said folder.

**Comment by TylerTheGuy298** [comment]
I unzipped the BEE2 packages folder and placed the contents into the packages folder of the application

**Comment by TylerTheGuy298** [comment]
I’ll try redownloading everything and redoing the steps.

**Comment by TylerTheGuy298** [comment]
It didn’t work.

**Comment by TeamSpen210** [comment]
Unfortunately it's kinda tricky to know which file is the issue here. Try removing all the packages, then adding them a few at a time until you hit the error (or see if it's just any of them).

**Comment by TylerTheGuy298** [comment]
Ok, I’ll try that when I wake up for school tomorrow

**Comment by TylerTheGuy298** [comment]
I tried it, I removed every package from the packages folder and still got the error

**Comment by TeamSpen210** [comment]
Can you post your full log file? It has to be finding a zip file somewhere.

**Comment by TylerTheGuy298** [comment]
Sure, give me a bit

**Comment by TylerTheGuy298** [comment]
Heres the log file: 
[bee2.5.log](https://github.com/BEEmod/BEE2.4/files/15281944/bee2.5.log)

**Comment by TeamSpen210** [comment]
That's a weird spot for Portal 2 to be installed. Where exactly is the packages folder you're sure is empty? Did you change the location in the config file (`C:\Users\sigma\AppData\Roaming\BEEMOD2\config\config.cfg`)?

**Comment by TylerTheGuy298** [comment]
I have not changed the location the .cfg location and the location of my packages folder is in the same folder as the .exe and other files, and the reason why portal 2 is in a weird location is because the Windows 11 computer isn’t mine, I borrowed it from my brother and just dragged my Portal 2 installation onto a external drive, if I need to I can download steam and download portal 2 that way.

**Comment by vrad-exe** [comment]
Closing due to lack of info
