### ISSUE TITLE
Export does not handle no voicelines correctly

### ISSUE THREAD

**Issue by Henonicks** [BEEmod/BEE2.4#2054]
### BEE2 Application Version

4.45.2 x64

### BEE2 Package Version

4.45.0

### What operating system are you running on?

Windows 10 (64bit)

### Logs and Reports

```shell
VBSP failed.

[I] compiler_launch.<module>(): Arguments: ['d:/stem/steamapps/common/Portal 2/bin/vbsp.exe', '-entity_limit', '1750', '-game', 'd:/stem/steamapps/common/Portal 2/portal2/', 'd:/stem/steamapps/common/Portal 2/sdk_content\\maps/preview.vmf']
[I] compiler_launch.<module>(): Running "vbsp", version 2.4.45.2 64-bit:
[I] vbsp.main(): BEE2.4.45.2 64-bit VBSP hook initiallised, srctools v2.3.17.dev5+823ca80.dirty.2024.04.17.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "d:/stem/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "d:/stem/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[I] vbsp.load_map(): Parsing Map...
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] barriers.parse_conf(): Parsed 3 barrier types, 2 frame types, and 5 hole types.
[I] vbsp.load_settings(): Settings Loaded!
[E] logger.except_handler(): Uncaught Exception:
  + Exception Group Traceback (most recent call last):
  |   File "compiler_launch.py", line 56, in <module>
  |   File "trio\_core\_run.py", line 2303, in run
  |   File "vbsp.py", line 1623, in main
  |   File "trio\_core\_run.py", line 963, in __aexit__
  | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "utils.py", line 662, in _task
    |   File "precomp\voice_line.py", line 61, in load
    |   File "trio\_path.py", line 38, in wrapper
    |   File "trio\_threads.py", line 471, in to_thread_run_sync
    |   File "outcome\_impl.py", line 213, in unwrap
    |   File "trio\_threads.py", line 397, in do_release_then_return_result
    |   File "outcome\_impl.py", line 213, in unwrap
    |   File "trio\_threads.py", line 416, in worker_fn
    |   File "trio\_path.py", line 57, in wrapper
    |   File "pathlib.py", line 1019, in read_bytes
    |   File "pathlib.py", line 1013, in open
    | FileNotFoundError: [Errno 2] No such file or directory: 'bee2\\voice.bin'
    +------------------------------------
[17896] Failed to execute script 'compiler_launch' due to unhandled exception
```

### Additional information

Style: `Clean`
Voice: `None`
Skybox: `Sphere Interior`
Elev. vid.: `Turrets: Ambush`
Corridor: any
Palette: default

Portal 2 installed into `d:\stem\steamapps\common\Portal 2\`

**Comment by Henonicks** [comment]
XD okay, I'll try that tomorrow. What did you add that broke it though?

**Comment by TeamSpen210** [comment]
I rewrote the system that parses the configuration and then adds it to a map, because it was really fragile. The code that parsed it for the voiceline editor in the app and the compiler part was totally different, now it all is the same.

**Comment by Henonicks** [comment]
It works! Exported with the GLaDOS (Clean) voice and it now builds.

**Comment by PixelPerfectGitHub** [comment]
It's just that I really do not want to add voicelines to my chambers.
