### ISSUE TITLE
I can't playtest any test chamber

### ISSUE THREAD

**Issue by PixelPerfectGitHub** [BEEmod/BEE2.4#2070]
### BEE2 Application Version

4.45.2 64bit

### BEE2 Package Version

4.45.0 

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Whenever I try to load and playtest a chamber, I get an error saying "There was an error building the puzzle". Even a completely unedited chamber won't be able to load, as well as without any style change.

### Expected behavior

I expect to be able to load a chamber and actually test it.

### Steps to reproduce

Step 1: Load an unedited test chamber.
Step 2: It says "There was an error building the puzzle"

### Logs and Reports

```shell
VBSP failed.

[I] compiler_launch.<module>(): Arguments: ['G:/SteamLibrary/steamapps/common/Portal 2/bin/vbsp.exe', '-entity_limit', '1750', '-game', 'G:/SteamLibrary/steamapps/common/Portal 2/portal2/', 'G:/SteamLibrary/steamapps/common/Portal 2/sdk_content\\maps/preview.vmf']
[I] compiler_launch.<module>(): Running "vbsp", version 2.4.45.2 64-bit:
[I] vbsp.main(): BEE2.4.45.2 64-bit VBSP hook initiallised, srctools v2.3.17.dev5+823ca80.dirty.2024.04.17.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "G:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "G:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[I] vbsp.load_map(): Parsing Map...
[W] texturing.load_config(): Could not parse texture generator type "bullsye.white.floor"!
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
[W] options.load(): Extra config options: {'glass_scale': '0.15', 'staticpan': 'instances/BEE2/clean/static_panel/'}
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] barriers.parse_conf(): Parsed 3 barrier types, 2 frame types, and 5 hole types.
[I] vbsp.load_settings(): Settings Loaded!
[E] logger.except_handler(): Uncaught Exception:
  + Exception Group Traceback (most recent call last):
  |   File "compiler_launch.py", line 56, in <module>
  |   File "trio\_core\_run.py", line 2303, in run
  |   File "vbsp.py", line 1623, in main
  |   File "trio\_core\_run.py", line 963, in __aexit__
  | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "utils.py", line 662, in _task
    |   File "precomp\voice_line.py", line 61, in load
    |   File "trio\_path.py", line 38, in wrapper
    |   File "trio\_threads.py", line 471, in to_thread_run_sync
    |   File "outcome\_impl.py", line 213, in unwrap
    |   File "trio\_threads.py", line 397, in do_release_then_return_result
    |   File "outcome\_impl.py", line 213, in unwrap
    |   File "trio\_threads.py", line 416, in worker_fn
    |   File "trio\_path.py", line 57, in wrapper
    |   File "pathlib.py", line 1019, in read_bytes
    |   File "pathlib.py", line 1013, in open
    | FileNotFoundError: [Errno 2] No such file or directory: 'bee2\\voice.bin'
    +------------------------------------
[8740] Failed to execute script 'compiler_launch' due to unhandled exception!
```

**Comment by TeamSpen210** [comment]
See #2054, you have to pick a voiceline set right now.

**Comment by PixelPerfectGitHub** [comment]
It's just that I really don't wanna have to add voicelines to my test chambers. They just don't add anything to my chambers and it's all dialogue you've heard before anyway.

**Comment by PixelPerfectGitHub** [comment]
What previous version could I go to so I don't have to use them?

**Comment by vrad-exe** [comment]
You can just select any voice pack, open the config menu (little gear icon next to the selector button), and uncheck every line
