### ISSUE TITLE
There was an error building the puzzle

### ISSUE THREAD

**Issue by Jazz63540** [BEEmod/BEE2.4#2076]
### BEE2 Application Version

BEE2_v4.45.2_win64

### BEE2 Package Version

BEE2_v4.45.0_packages

### What operating system are you running on?

Windows 11

### Description of the bug

As the title says, whenever I try to build a puzzle, I get the error message 'There was an error building this puzzle'. This happens even when I haven't made any changes to the default puzzlemaker map.

### Expected behavior

The puzzle should build normally without issue.

### Steps to reproduce

I installed BEE2.4 by following the instructions provided, and this issue presented itself.

### Logs and Reports

```shell
VBSP failed.

[I] compiler_launch.<module>(): Arguments: ['d:/program files/steam/steamapps/common/portal 2/bin/vbsp.exe', '-entity_limit', '1750', '-game', 'd:/program files/steam/steamapps/common/portal 2/portal2/', 'd:/program files/steam/steamapps/common/portal 2/sdk_content\\maps/preview.vmf']
[I] compiler_launch.<module>(): Running "vbsp", version 2.4.45.2 64-bit:
[I] vbsp.main(): BEE2.4.45.2 64-bit VBSP hook initiallised, srctools v2.3.17.dev5+823ca80.dirty.2024.04.17.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "d:/program files/steam/steamapps/common/portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "d:/program files/steam/steamapps/common/portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[I] vbsp.load_map(): Parsing Map...
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] barriers.parse_conf(): Parsed 3 barrier types, 2 frame types, and 5 hole types.
[I] vbsp.load_settings(): Settings Loaded!
[E] logger.except_handler(): Uncaught Exception:
  + Exception Group Traceback (most recent call last):
  |   File "compiler_launch.py", line 56, in <module>
  |   File "trio\_core\_run.py", line 2303, in run
  |   File "vbsp.py", line 1623, in main
  |   File "trio\_core\_run.py", line 963, in __aexit__
  | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "utils.py", line 662, in _task
    |   File "precomp\voice_line.py", line 61, in load
    |   File "trio\_path.py", line 38, in wrapper
    |   File "trio\_threads.py", line 471, in to_thread_run_sync
    |   File "outcome\_impl.py", line 213, in unwrap
    |   File "trio\_threads.py", line 397, in do_release_then_return_result
    |   File "outcome\_impl.py", line 213, in unwrap
    |   File "trio\_threads.py", line 416, in worker_fn
    |   File "trio\_path.py", line 57, in wrapper
    |   File "pathlib.py", line 1019, in read_bytes
    |   File "pathlib.py", line 1013, in open
    | FileNotFoundError: [Errno 2] No such file or directory: 'bee2\\voice.bin'
    +------------------------------------
[31152] Failed to execute script 'compiler_launch' due to unhandled exception!
```

### Additional information

Clean style was used, with no changes made to the palette, and no changes were made to the default puzzlemaker map.

**Comment by TeamSpen210** [comment]
See #2054.
