### ISSUE TITLE
(dev) Crash on startup if previously selected music no longer exists

### ISSUE THREAD

**Issue by vrad-exe** [BEEmod/BEE2.4#2080]
```
[WARNING] packages.obj_by_id(): Unknown Music "BMMC_HAZARDOUSENVIRONMENTS"!
[ERROR] core.done_callback(): Trio exited with exception
  + Exception Group Traceback (most recent call last):
  |   File "ui_tk\core.py", line 135, in app_main
  |   File "trio\_core\_run.py", line 959, in __aexit__
  | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "app\music_conf.py", line 295, in make_widgets
    |   File "app\music_conf.py", line 79, in set_suggested
    |   File "packages\__init__.py", line 756, in obj_by_id
    | KeyError: 'bmmc_hazardousenvironments'
    +------------------------------------

```

Probably applies to styles etc. too

**Comment by vrad-exe** [comment]
Got a different error after removing the saved music from the config
```
  + Exception Group Traceback (most recent call last):
  |   File "ui_tk\core.py", line 135, in app_main
  |   File "trio\_core\_run.py", line 959, in __aexit__
  | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "app\UI.py", line 870, in init_windows
    | AttributeError: 'NoneType' object has no attribute 'has_video'
    +------------------------------------
```

**Comment by vrad-exe** [comment]
What about the second error I posted, that looks related to styles

**Comment by TeamSpen210** [comment]
I actually fixed that already, just hadn't pushed. Confused me when looking at the lines to identify the problem...
