### ISSUE TITLE
not a directory error when launching bee2 for the first time

### ISSUE THREAD

**Issue by guranu** [BEEmod/BEE2.4#2094]
### BEE2 Application Version

2.4.45.2.dev+959e0852 64-bit

### BEE2 Package Version

4.45.0

### What operating system are you running on?

Linux

### Description of the bug

Hello, i installed bee2 for the very first time and i get a NotADirectory error after selecting a path to portal2_linux the issue is it's trying to find gameinfo.txt in a file that dosen't have it (e.g. portal2.ico).
![Снимок экрана_2024-12-20_22-05-41](https://github.com/user-attachments/assets/b9c4c64b-0620-4dde-8a6d-fabeac3112eb)

### Expected behavior

To launch bee2 on my linux machine

### Steps to reproduce

1. launch bee2
2. Select the portal2_linux executable

### Logs and Reports

```shell
[INFO] BEE2_launch.<module>(): Arguments: ['/home/laret/Загрузки/beemod2_fa65188112e383a9dd9c2dfbe1598b826747bfdb_linux64/bee2_64/BEE2']
[INFO] BEE2_launch.<module>(): Running "bee2", version 2.4.45.2.dev+959e0852 64-bit:
[INFO] localisation.setup(): Language: 'ru_RU'
[DEBUG] localisation.setup(): Language codes: ['ru_ru', 'ru']
[DEBUG] core.start_main(): Starting Trio loop.
[DEBUG] core.app_main(): Opening nursery...
[DEBUG] core.init_app(): Starting loading screen...
[DEBUG] core.init_app(): Loading settings...
[DEBUG] loadScreen._listen_to_process(): Logger response: Daemon2Load_MainSetCompact(compact=True)
[ERROR] core.done_callback(): Trio exited with exception
  + Exception Group Traceback (most recent call last):
  |   File "ui_tk/core.py", line 136, in app_main
  |   File "trio/_core/_run.py", line 1039, in __aexit__
  | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "ui_tk/core.py", line 150, in app_main
    |   File "ui_tk/core.py", line 58, in init_app
    |   File "app/gameMan.py", line 343, in load
    |   File "app/gameMan.py", line 369, in add_game
    |   File "app/gameMan.py", line 279, in find_steam_info
    |   File "trio/_file_io.py", line 467, in open_file
    |   File "trio/_threads.py", line 443, in to_thread_run_sync
    |   File "outcome/_impl.py", line 213, in unwrap
    |   File "trio/_threads.py", line 369, in do_release_then_return_result
    |   File "outcome/_impl.py", line 213, in unwrap
    |   File "trio/_threads.py", line 388, in worker_fn
    | NotADirectoryError: [Errno 20] Not a directory: '/home/laret/.local/share/Steam/steamapps/common/Portal 2/portal2.ico/gameinfo.txt'
    +------------------------------------
```

**Comment by guranu** [comment]
Hello? Are you seeing this issue?
