### ISSUE TITLE
BEE2 doesn't open instead of giving an error when

### ISSUE THREAD

**Issue by Endernice61** [BEEmod/BEE2.4#2096]
### BEE2 Application Version

2.4.45.2 64-bit

### BEE2 Package Version

4.45.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Having a ucp with an info.txt that has a mistake in it causes BEE2 to not open. It does describe the error in the logs

### Expected behavior

BEE2 would display an error message and then crash gracefully once the user closes the error dialogue

### Steps to reproduce

[mistake.zip](https://github.com/user-attachments/files/18223289/mistake.zip)
Put the file attached in the packages folder and attempt to open BEE2

### Logs and Reports

```shell
[INFO] BEE2_launch.<module>(): Arguments: ['C:\\Program Files (x86)\\Steam\\steamapps\\common\\BEE2 2\\BEE2.exe']
[INFO] BEE2_launch.<module>(): Running "bee2", version 2.4.45.2 64-bit:
[INFO] localisation.setup(): Language: 'en'
[DEBUG] localisation.setup(): Language codes: ['en']
[DEBUG] sound.<module>(): Appending "C:\Program Files (x86)\Steam\steamapps\common\BEE2 2\bin" to $PATH.
[DEBUG] core.start_main(): Starting Trio loop.
[DEBUG] core.app_main(): Opening nursery...
[DEBUG] core.init_app(): Starting loading screen...
[DEBUG] core.init_app(): Loading settings...
[INFO] gameMan.load(): Load game: Game(name='PORTAL 2', steamID='620', root='C:/Program Files (x86)/Steam/steamapps/common/Portal 2', mod_times={}, exported_style=None, unmarked_dlc3_vpk=False)
[INFO] core.init_app(): Loading Packages...
[DEBUG] packages.find_packages(): Reading package "packages\abs_fizz.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\aneonen_misc.zip"
[DEBUG] packages.find_packages(): Reading package "packages\antlines.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\Axos_Fizzlers.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\barrier_hole.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\barrier_variants.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\beemod.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\blocks.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\bumbleball.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\buttons.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\catwalk.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\checkpoint.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\clean_style.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\conveyor.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\cube_bomb.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\cube_cleaner.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\cube_color.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\deathfizzler.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\destruction_target.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\dis_beams.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\ditch.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\Dogs-Extra-Signage.zip"
[DEBUG] packages.find_packages(): Reading package "packages\elevator_videos.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\entry_exit.zip"
[DEBUG] packages.find_packages(): Reading package "packages\fizzler_out_relay.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\fr_fizzlers.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\futbol.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\geometry.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\hazards.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\hmw.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\hovering_harrys_stuff.zip"
[DEBUG] packages.find_packages(): Reading package "packages\Konclan-Items-1.0.1.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\lifeform_sensor.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\light_tiles.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\logic.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\mistake.zip"
[ERROR] core.done_callback(): Trio exited with exception
  + Exception Group Traceback (most recent call last):
  |   File "ui_tk\core.py", line 247, in app_main
  |   File "trio\_core\_run.py", line 963, in __aexit__
  | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "ui_tk\core.py", line 255, in app_main
    |   File "ui_tk\core.py", line 79, in init_app
    |   File "utils.py", line 692, in run_as_task
    |   File "trio\_core\_run.py", line 963, in __aexit__
    | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
    +-+---------------- 1 ----------------
      | Exception Group Traceback (most recent call last):
      |   File "packages\__init__.py", line 610, in load_packages
      |   File "trio\_core\_run.py", line 963, in __aexit__
      | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
      +-+---------------- 1 ----------------
        | Exception Group Traceback (most recent call last):
        |   File "utils.py", line 662, in _task
        |   File "packages\__init__.py", line 531, in find_packages
        |   File "trio\_core\_run.py", line 963, in __aexit__
        | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
        +-+---------------- 1 ----------------
          | Traceback (most recent call last):
          |   File "packages\__init__.py", line 560, in find_packages
          |   File "trio\_threads.py", line 471, in to_thread_run_sync
          |   File "outcome\_impl.py", line 213, in unwrap
          |   File "trio\_threads.py", line 397, in do_release_then_return_result
          |   File "outcome\_impl.py", line 213, in unwrap
          |   File "trio\_threads.py", line 416, in worker_fn
          |   File "srctools\filesys.py", line 171, in read_kv1
          |   File "srctools\keyvalues.py", line 506, in parse
          | srctools.keyvalues.KeyValError: Block opening ("{") required, but hit EOF!
          | A "name" line was located at the end of the file, which needs a {} block to follow.
          | Error occurred with file "packages\mistake.zip:info.txt".
          +------------------------------------
```

**Comment by TeamSpen210** [comment]
Thanks, added an error for this case.
