### ISSUE TITLE
BEE2 App fails to launtch and gives me this ERROR

### ISSUE THREAD

**Issue by Stringfire8517** [BEEmod/BEE2.4#2097]
### BEE2 Application Version

BEE2.4 v4.45.2 64bit

### BEE2 Package Version

BEE2.4 v4.45.2 64bit

### What operating system are you running on?

Linux

### Logs and Reports

```shell
[INFO] BEE2_launch.<module>(): Arguments: ['/home/daniel/BEE2.4/dist/64bit/BEE2/BEE2']
[INFO] BEE2_launch.<module>(): Running "bee2", version 2.4.45.2.dev+fa651881 64-bit:
[WARNING] BEE2_config.load(): Config "/home/daniel/.config/BEEMOD2/config/config.cfg" not found! Using defaults...
[INFO] BEE2_config.save(): Saving changes in config "/home/daniel/.config/BEEMOD2/config/config.cfg"!
[INFO] localisation.setup(): Language: 'en_US'
[DEBUG] localisation.setup(): Language codes: ['en_us', 'en']
[ERROR] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "BEE2_launch.py", line 88, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "app/backup.py", line 26, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "ui_tk/tk_tools.py", line 24, in <module>
ModuleNotFoundError: No module named 'idlelib'
```

### Additional information

I was using the guide that was linked to this repository.
I was using the main and not the Dev version
I'm running Kubuntu 24.10.

**Comment by TeamSpen210** [comment]
You'll need to install the python-idle package , since I use one thing from there.

**Comment by Stringfire8517** [comment]
ok i will try that

**Comment by Stringfire8517** [comment]
It gave me the same error and I tried to run tk_tools.py in idle and it gave me this error: 
Traceback (most recent call last):
  File "/usr/lib/python3.10/idlelib/run.py", line 578, in runcode
    exec(code, self.locals)
  File "/home/daniel/BEE2.4/src/ui_tk/tk_tools.py", line 29, in <module>
    from app import ICO_PATH, background_run
ModuleNotFoundError: No module named 'app'

**Comment by TeamSpen210** [comment]
If running that from source you need to pass "bee2" as a parameter.

**Comment by Stringfire8517** [comment]
ok i will try that

**Comment by Stringfire8517** [comment]
IT WORKS... except:
No compiler files were found in 
"/home/daniel/BEE2.4/compiler".

**Comment by TeamSpen210** [comment]
Sounds like you didn't build the compiler.

**Comment by vrad-exe** [comment]
If you're still experiencing this issue, please post the compile output from the developer console (big block of red text) after getting the compile error, we can't determine anything from the generic error message shown in the UI.

**Comment by vrad-exe** [comment]
Closing due to inactivity
