### ISSUE TITLE
Hammer compile error

### ISSUE THREAD

**Issue by SPAHI4** [BEEmod/BEE2.4#433]
```
-------------------------------------------------------------------------------
Running command: cd "E:\Games\Steam\steamapps\common\Portal 2\bin"
-------------------------------------------------------------------------------


-------------------------------------------------------------------------------
Running command: "E:\Games\Steam\steamapps\common\Portal 2\bin\vbsp.exe" -game "E:\Games\Steam\steamapps\common\Portal 2\portal2" "E:\Games\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\mp_coop_trip_3_1.vmf"
-------------------------------------------------------------------------------

[INFO] vbsp.main(): BEE2.4.0pr23 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "E:\Games\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\mp_coop_trip_3_1.vmf"
[INFO] vbsp.main(): New path: "E:\Games\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\styled\mp_coop_trip_3_1.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[WARNING] vbsp.main(): Hammer map detected! skipping conversion..
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "E:\Games\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "E:\Games\Steam\steamapps\common\Portal 2\portal2" "E:\Games\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\mp_coop_trip_3_1.vmf"
[INFO] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Aug 26 2015)
 | 4 threads
 | materialPath: E:\Games\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading E:\Games\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\mp_coop_trip_3_1.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | fixing up env_cubemap materials on brush sides...
 | ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
 | **** leaked ****
 | Entity func_noportal_volume (771.00 496.00 144.00) leaked!
 |
 | FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (5664.0 5120.0 456.0)
 | Leaf 0 contents:
 | Leaf 1 contents: CONTENTS_SOLID
 | viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID
 | This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID
 | Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID
 | Candidate brush IDs:
 |
 |
 | FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (5180.0 5120.0 456.0)
 | Leaf 0 contents:
 | Leaf 1 contents: CONTENTS_SOLID
 | viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID
 | This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID
 | Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID
 | Candidate brush IDs:
 |
 |
 | FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (5168.0 5120.0 456.0)
 | Leaf 0 contents:
 | Leaf 1 contents: CONTENTS_SOLID
 | viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID
 | This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID
 | Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID
 | Candidate brush IDs:
 |
 |
 | FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (5136.0 5120.0 456.0)
 | Leaf 0 contents:
 | Leaf 1 contents: CONTENTS_SOLID
 | viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID
 | This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID
 | Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID
 | Candidate brush IDs:
 |
 |
 | FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (5156.0 5120.0 456.0)
 | Leaf 0 contents:
 | Leaf 1 contents: CONTENTS_SOLID
 | viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID
 | This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID
 | Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID
 | Candidate brush IDs:
 |
 |
 | FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (6144.0 4608.0 456.0)
 | Leaf 0 contents:
 | Leaf 1 contents: CONTENTS_SOLID
 | viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID
 | This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID
 | Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID
 | Candidate brush IDs:
 |
 |
 | FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (4608.0 6144.0 456.0)
 | Leaf 0 contents:
 | Leaf 1 contents: CONTENTS_SOLID
 | viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID
 | This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID
 | Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID
 | Candidate brush IDs:
 |
 |
 | FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (5120.0 5632.0 456.0)
 | Leaf 0 contents:
 | Leaf 1 contents: CONTENTS_SOLID
 | viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID
 | This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID
 | Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID
 | Candidate brush IDs:
 |
 | *** Suppressing further FindPortalSide errors.... ***
 | Processing areas...done (0)
 | Building Faces...done (0)
 | Chop Details...done (0)
 | Find Visible Detail Sides...
 | Merged 3002 detail faces...done (0)
 | Merging details...done (1)
 | FixTjuncs...
 | PruneNodes...
 | WriteBSP...
 | done (0)
 | WARNING: node without a volume
 | Finding displacement neighbors...
 | Finding lightmap sample positions...
 | Displacement Alpha : 0...1...2...3...4...5...6...7...8...9...10
 | Building Physics collision data...
 | done (1) (1317949 bytes)
 | Static prop models/anim_wp/framework/squarebeam_off_2x2.mdl outside the map (832.00, 192.00, 904.00)
 | Static prop models/anim_wp/framework/squarebeam_off_2x2.mdl outside the map (704.00, 200.00, 900.00)
 | Static prop models/anim_wp/framework/squarebeam_off_2x2.mdl outside the map (960.00, 192.00, 904.00)
 | Static prop models/anim_wp/framework/squarebeam_off_2x2.mdl outside the map (1088.00, 192.00, 904.00)
 | Static prop models/anim_wp/framework/squarebeam_off_2x2.mdl outside the map (1088.00, 320.00, 904.00)
 | Static prop models/anim_wp/framework/squarebeam_off_2x2.mdl outside the map (960.00, 320.00, 904.00)
 | Static prop models/anim_wp/framework/squarebeam_off_2x2.mdl outside the map (832.00, 320.00, 904.00)
 | Static prop models/anim_wp/framework/squarebeam_off_2x2.mdl outside the map (832.00, 448.00, 904.00)
 | Static prop models/anim_wp/framework/squarebeam_off_2x2.mdl outside the map (1088.00, 448.00, 904.00)
 | Static prop models/anim_wp/framework/squarebeam_off_2x2.mdl outside the map (832.00, 576.00, 904.00)
 | Static prop models/anim_wp/framework/squarebeam_off_2x2.mdl outside the map (960.00, 576.00, 904.00)
 | Static prop models/anim_wp/framework/squarebeam_off_2x2.mdl outside the map (1088.00, 576.00, 904.00)
 | Static prop models/props_foliage/vine_cluster_hanging04_dry_alphatest.mdl outside the map (816.00, 176.00, 1032.00)
 | Static prop models/BEE2/catwalk/overgrown/hanging_walkway_end_cap.mdl outside the map (2624.00, 96.00, 130.00)
 | Placing detail props : 0...1...2...3...4...5...6...7...8...9...10
 | Water found with no water_lod_control entity, creating a default one.
 | Compacting texture/material tables...
 | Reduced 6295 texinfos to 1900
 | Reduced 124 texdatas to 109 (4083 bytes to 3617)
 | Writing E:\Games\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\mp_coop_trip_3_1.bsp
 |
 | nummapplanes:     ( 11738 / 65536 )
 | nummapbrushes:    (  3644 /  8192 )
 | nummapbrushsides: ( 29107 / 65536 )
 | num_map_overlays: (   115 /   512 )
 | nummodels:        (   187 /  1024 )
 | num_entities:     (   909 / 16384 )
 |
 | 6 seconds elapsed
 |_

[INFO] vbsp.run_vbsp(): VBSP Done!
[INFO] vbsp.make_vrad_config(): Generating VRAD config...
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3647, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 3245, in make_vrad_config
AttributeError: 'NoneType' object has no attribute 'get_bool'
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3647, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 3245, in make_vrad_config
AttributeError: 'NoneType' object has no attribute 'get_bool'
Finished. Press a key to close.
```

**Comment by TeamSpen210** [comment]
Go to Hammer options, and in the Build Programs tab change VBSP and VRAD to the _original exes. That will prevent the compilers from doing anything.

**Comment by SPAHI4** [comment]
Thanks.
I also add needed packed files with BspZip.
But now there is a texture bug
![image](https://cloud.githubusercontent.com/assets/1670998/20628918/e99132aa-b339-11e6-9edf-28bf12bdeb95.png)
It was before when I tested my published workshop maps alone by copying them in the maps folder from maps/workshop/<id>, but now this bug happens in all cases.

**Comment by SPAHI4** [comment]
Now all fine. I dont know whats going on.
