### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by prrg** [BEEmod/BEE2.4#476]
I installed all the dependencies (using Linux) but when I try to build "compile_BEE2.py", it gives me this error:

`Traceback (most recent call last):
  File "compile_BEE2.py", line 4, in <module>
    import utils
  File "/home/prrg/Downloads/bee2/BEE2/src/utils.py", line 97
    def add_mousewheel(target, *frames, orient='y'):
                                             ^
SyntaxError: invalid syntax
`

Any help?

**Comment by LautaroL20** [comment]
Currently, there is not a Linux compatible version of Bee 2.4. 
Windows 7 - 10  / MaxOsX only ATM.

**Comment by Luke18033** [comment]
You could try downloading from the [`linux` branch](https://github.com/BEEmod/BEE2.4/tree/linux), but that's really outdated and I'm not sure if it even works.

**Comment by TeamSpen210** [comment]
It sounds like you might have Python 2, not python 3. It should mostly work on Linux, I just don't have a computer with Linux Portal 2 installed to make sure it all works properly and compiles.

**Comment by prrg** [comment]
Ok, so I tried installing it using "python3 <> build" and not "python <> build". It seems to work this way but then it asks me to type the BEE2 version and I'm not sure how to answer this. Typing "2.4" gives this:

`TypeError: __init__() got an unexpected keyword argument 'compress'
`

**Comment by Luke18033** [comment]
For the BEE2 version, you put something like Pr24-dev or Pr23. I got that error once on Windows, but I can't remember what caused it...

**Comment by TeamSpen210** [comment]
Checkout the `dev` branch, I fixed that issue. Also you'll need to `pip install srctools`.

**Comment by Luke18033** [comment]
I didn't think you could `pip install srctools`. I thought you had to clone the TeamSpen210/srctools repo.

**Comment by prrg** [comment]
Okay so at least now it finished installing. Running BEE2 gives an error message however. The compiler showed a bunch of 'missing dependencies' so I guess it is related to that. There were at least 12 of those so it might take a while to do it all. Will update if I run into more problems/get it working.

**Comment by TheDarkBomber** [comment]
This should be reopened, and have the `Bug` label instead of the `invalid` label.

**Comment by TeamSpen210** [comment]
Many of the missing dependencies are intentional, I block it from including some things that are technically imported in the code, but only in unused areas.

**Comment by prrg** [comment]
Ok, so I only had to install `python3-tk`

But now, I got this gigantic error.

`Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/cx_Freeze/initscripts/__startup__.py", line 12, in <module>
    __import__(name + "__init__")
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/cx_Freeze/initscripts/Console.py", line 24, in <module>
    exec(code, m.__dict__)
  File "BEE2.pyw", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/prrg/Downloads/bee2.4.24-dev/BEE2.4-dev/src/UI.py", line 10, in <module>
    from query_dialogs import ask_string
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/prrg/Downloads/bee2.4.24-dev/BEE2.4-dev/src/query_dialogs.py", line 2, in <module>
    from loadScreen import surpress_screens
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/prrg/Downloads/bee2.4.24-dev/BEE2.4-dev/src/loadScreen.py", line 12, in <module>
    import img
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/prrg/Downloads/bee2.4.24-dev/BEE2.4-dev/src/img.py", line 203, in <module>
    img_error = png('BEE2/error', error=BLACK_64)
  File "/home/prrg/Downloads/bee2.4.24-dev/BEE2.4-dev/src/img.py", line 80, in png
    return error or img_error
NameError: name 'img_error' is not defined`

I can only recognize the last line, and I can't think of anything I can do on img.py to define "img_error" (even though it is apparently already defined in the bottom of the file). Not sure what is going on.

**Comment by TeamSpen210** [comment]
The issue would be that it can't find the error images, in images/BEE2/, so it tries to return that image. What directory are you in when running?

**Comment by prrg** [comment]
In build_BEE2/bin, where the BEE2 file is. I got it working by just copying the entire images folder from the source code/original BEE2 folder to build_BEE2. Back to install missing dependencies now.

**Comment by TeamSpen210** [comment]
Oh, yes you need all the folders and files in the source folder, except `src/` and `dev/`. You also need the packages. To install dependencies, `pip3 install pyglet pillow markdown srctools` should get them all.

**Comment by TeamSpen210** [comment]
You need to compile the compiler files (vbsp/vrad), but you can run the bee2 application from source.

**Comment by prrg** [comment]
Ok, I installed all the dependencies (already had pyglet, markdown and srctools; had to separately install pillow though; and cx_Freeze, to run the compiler before) and copied all the folders. Now I'm getting this:


```
  File "/home/prrg/Downloads/bee2.4.24-dev/BEE2.4-dev/src/voiceEditor.py", line 52, in <module>
    win.iconbitmap('../BEE2.ico')
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1719, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "../BEE2.ico" not defined
```

At first I thought it was just a case of case-sensitiveness that worked in Windows but not in Linux so I changed bee2.ico to BEE2.ico but it still isn't really working. BEE2.ico is supposed to be on "bin", isn't it?

**Comment by TheDarkBomber** [comment]
No, it's supposed to be outside the `bin` folder.

**Comment by TeamSpen210** [comment]
Bin should only contain the stuff `cx_freeze` includes. It's the same as the repro layout, but replacing `src` with `bin`. Or run `BEE2.pyw` directly.

**Comment by prrg** [comment]
The compiler is creating a bee2.ico file on "bin" though... copied it to the build_BEE2. Now I'm getting this.

`ImportError: No module named 'PIL._tkinter_finder'`

Which is strange since I already installer Tkinter... unless this is a different thing entirely

**Comment by TheDarkBomber** [comment]
Just move it **outside** the `bin` folder. Nothing more, nothing less.

**Comment by prrg** [comment]
I'm out of ideas now.

```
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: No module named 'PIL._tkinter_finder'
[...]
  File "/home/prrg/.local/lib/python3.5/site-packages/PIL/ImageTk.py", line 181, in paste
    tk.call("PyImagingPhoto", self.__photo, block.id)
_tkinter.TclError: invalid command name "PyImagingPhoto"
[...]
  File "/home/prrg/Downloads/bee2.4.24-dev/BEE2.4-dev/src/img.py", line 169, in color_square
    return cached_squares[key]
KeyError: (0.0, 0.0, 0.0, 64)
[...]
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: No module named 'PIL._tkinter_finder'
[...]
  File "/home/prrg/.local/lib/python3.5/site-packages/PIL/ImageTk.py", line 181, in paste
    tk.call("PyImagingPhoto", self.__photo, block.id)
_tkinter.TclError: invalid command name "PyImagingPhoto"
[...]
  File "/home/prrg/Downloads/bee2.4.24-dev/BEE2.4-dev/src/img.py", line 169, in color_square
    return cached_squares[key]
KeyError: (0.0, 0.0, 0.0, 64)
```

4 out of the 6 errors are tkinter related, and that's because I don't know what is up with the KeyErrors, 'cause they might as well also be tkinter related. I've installed, reinstalled. upgraded in all kinds of ways and it still does not go away.

@TheDarkBomber - I don't think it will make any difference, but I removed the BEE2.ico from bin.

**Comment by TeamSpen210** [comment]
Those KeyErrors are indeed related, I have the app cache all imagery, so that's it not finding a copy already loaded and trying to make a new one (then failing). The issue would be with your copy of pillow / tkinter not being compatible or something like that.

**Comment by prrg** [comment]
God dammit. Will purge everything python-related and see if it works then. My HD is pretty bloated so it is indeed likely my copy is problematic.

**Comment by TeamSpen210** [comment]
I am using Python 3.4, not 3.5, although that shouldn't cause any problems (as long as you have the right libraries).

**Comment by prrg** [comment]
Ok, so, I tried to be lazy in deleting the thousands of python stuff in my computer used the command "apt-get purge". That was a bad idea, since it started murdering every program in my computer for some reason. But NOW that I have a clean slate because I reformatted the computer, I guess it worked out fine for the purpose it was used.

Anyways. Unfortunately I can't launch it just yet, but we're down from 6 errors to only 1 error so that's pretty nice. Last error STILL is that hateful ImageTk though... Here's the Traceback:
```
  File "/usr/local/lib/python3.5/dist-packages/cx_Freeze/initscripts/__startup__.py", line 12, in <module>
    __import__(name + "__init__")
  File "/usr/local/lib/python3.5/dist-packages/cx_Freeze/initscripts/Console.py", line 24, in <module>
    exec(code, m.__dict__)
  File "BEE2.pyw", line 50, in <module>
  File "/home/prrg/git/BEE2.4/src/UI.py", line 10, in <module>
    from query_dialogs import ask_string
  File "/home/prrg/git/BEE2.4/src/query_dialogs.py", line 2, in <module>
    from loadScreen import surpress_screens
  File "/home/prrg/git/BEE2.4/src/loadScreen.py", line 12, in <module>
    import img
  File "/home/prrg/git/BEE2.4/src/img.py", line 7, in <module>
    from PIL import ImageTk, Image, ImageDraw
ImportError: cannot import name 'ImageTk'
```

**Comment by TeamSpen210** [comment]
Make sure you have Tkinter installed before you install pillow. Maybe try the `python-imaging` `apt` package if you're using PIP, or vice versa?

**Comment by prrg** [comment]
Ok, so I was confusing things, ImageTk is actually another thing. I just installed so much stuff today that I forgot about it. Anyway, after installing ImageTk and Markdown (which I installed before but didn't work for some reason...?) Tkinter (python3-tk?) was actually one of the first things I installed, but ImageTk (python-pip.imagetk) is a separate package.

So here we go again...
`  File "/usr/lib/python3.5/tkinter/__init__.py", line 1719, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "../BEE2.ico" not defined
`
Last time the error just disappeared after I moved BEE2.ico to the bin folder but I already did that now so yeah.

**Comment by TeamSpen210** [comment]
ImageTK is the support in PIL/pillow for tkinter. Tkinter is the UI package for widgets and whatnot, PIL is the imaging library which allows reading images other than GIFs (tkinter is kinda old)..

**Comment by prrg** [comment]
Is there any possible reason tkinter might not be able to recognize a file?

**Comment by prrg** [comment]
I DID IT
Kinda of a "forced my way through" resolution but whatever. Removing the lines related to the icon in "optionWindow" and "voiceEditor" made the thing finally work!!!!

But then it asked me for my portal 2 folder and I was cruelly reminded that I don't even have Steam installed yet.

**Comment by prrg** [comment]
I don't know if there is anything to discuss (or fix, since you still can't run it on linux without modifying those two archives), but I will leave this open just in case.

**Comment by TeamSpen210** [comment]
I'll fix up that code and prevent it from doing the icons in Linux (I don't think they'd work anyway). Was there anything else you changed?

**Comment by prrg** [comment]
Nah, literally just removed the lines that mentioned them.

**Comment by TeamSpen210** [comment]
I just committed that change to the repro (9a3cc68) in a more suitable way.

**Comment by prrg** [comment]
Update: After installing Portal 2 and moving on through the first few windows I had another crash related to the .ico. Had to remove mentions of the icon in query_update. I don't know if there will be any more instances of this.

**Comment by prrg** [comment]
Last Update: I replaced all my src files with the ones from the newest commit. Almost everything went smoothly but selectorWin.py still returns a TclError related to BEE2.ico. Had to remove it to proceed.
