### ISSUE TITLE
There was an error building the puzzle

### ISSUE THREAD

**Issue by EnchGA** [BEEmod/BEE2.4#493]
I got a problem when i want to test my map. After that i got "There was an error building the puzzle". Please help me...

P.S. I disabled antivirus and restarted BEE2.

And yeah i got bad english because i'm from russia.

**Comment by ZRezlon** [comment]
Which Style are you using? If you were using the Overgrown Style, then change the entrance to 3: White Left and the Exit to 3: Floor BTS. It should work then.

**Comment by LautaroL20** [comment]
Well, i saw many times people reporting this issue but they must understand it is not very helpful making a post with the clasical message of "there was an error building the puzzle" and thats all that people writtes on their description´s issue...... What stile did you use? Wich test elements do you placed on the editor?

@ZRezlon - That bug is older than my great grandparents right now and its fixed with the PRL24.

**Comment by EnchGA** [comment]
I'm using Clean style

**Comment by LautaroL20** [comment]
Wich items did you use into the puzzlemaker editor?

**Comment by EnchGA** [comment]
[https://puu.sh/tuLXc/779ad07063.png](url) @LautaroL20

**Comment by LautaroL20** [comment]
@EnchGA - Ennable the developer console from Portal 2 and then compile your map, once it fails to compile, copy the full console message, here.

**Comment by EnchGA** [comment]
@LautaroL20 

==== calling mapspawn.nut
Requested non-existent write path LOCAL!
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
ΞNCHGΔ unpaused the game
ΞNCHGΔ unpaused the game
ΞNCHGΔ unpaused the game
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF D:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 72 (ms)

VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr24 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "D:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "D:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3535, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 300, in load_settings
  File "F:\Git\srctools\srctools\property_parser.py", line 303, in parse
  File "C:\Python34\lib\encodings\ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 6337: ordinal not in range(128)
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3535, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 300, in load_settings
  File "F:\Git\srctools\srctools\property_parser.py", line 303, in parse
  File "C:\Python34\lib\encodings\ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 6337: ordinal not in range(128)

**Comment by LautaroL20** [comment]
Well, from what i can see the bug is entirely related to the Bee2.4´s Compiler, and the only person who can deduct all these rare lines to figure out whats going on its @TeamSpen210

**Comment by TeamSpen210** [comment]
This implies one of the config files has some unusual characters, which is breaking something.

**Comment by LautaroL20** [comment]
@EnchGA - Well, i have tested all the items from the default "BEEmod Palette" and i was able to compile pretty normal. Are you using the latest beemod version PRL24?

**Comment by EnchGA** [comment]
@LautaroL20 idk but i downloaded files from this site

**Comment by TeamSpen210** [comment]
Where is the location of the BEE2.4 folder? Try moving it to somewhere like the drive root.

**Comment by EnchGA** [comment]
@TeamSpen210 
C:\Users\Александр\Desktop\bee2 mod

(i think cyrillic's fault)

**Comment by TeamSpen210** [comment]
Should be resolved for the next release, but just put the folder somewhere higher up for now.

**Comment by EnchGA** [comment]
@TeamSpen210 okay

**Comment by petersohn** [comment]
I get the same error message. Possibly a different problem though. I have the following error message on the console:

```

VBSP failed.

ERROR: ld.so: object '/home/peet/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'
Current thread 0x00007f0bd7fbec40 (most recent call first):
```

**Comment by TeamSpen210** [comment]
Different issue - Python basically can't find its internal modules, so it can't load up the encoding database.

**Comment by petersohn** [comment]
Then it's probably related to #517. I ran BEE2 from the python interpreter because the compiled version failed to load libjpeg.
