### ISSUE TITLE
Development Version error

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#505]
The compile goes fine, but when I try to launch BEE2.4, this error appears at the end of Extracting Images:
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
    __import__(name + "__init__")
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
    exec(code, m.__dict__)
  File "BEE2.pyw", line 125, in <module>
  File "C:\Users\Luke18033\Documents\GitHub\BEE2.4\src\packageLoader.py", line 461, in load_packages
    log_missing_styles,
  File "C:\Users\Luke18033\Documents\GitHub\BEE2.4\src\packageLoader.py", line 636, in setup_style_tree
    '<{}:{}.{}>'.format(item.id, vers['id'], sty_id)
  File "C:\Users\Luke18033\Documents\GitHub\BEE2.4\src\packageLoader.py", line 813, in modify
    for prop in vbsp_config.iter_tree():
AttributeError: 'Property' object has no attribute 'iter_tree'
```

**Comment by TeamSpen210** [comment]
Update srctools.
