### ISSUE TITLE
Won't Play Sample Music

### ISSUE THREAD

**Issue by Alfe5** [BEEmod/BEE2.4#508]
After selecting the Wheatly voice in Bee2, the music sample button just refuses to work. No idea what causes this.

**Comment by LautaroL20** [comment]
@Alfe5 - Get Pre-release 27 (Packages & Application) since this is most likely fixed now. Also, to ensure everything will work fine, you will have to do the following once installed:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!

**Comment by QuentinMarical** [comment]
When I try to play music
---------------------------
BEE2 Error!
---------------------------
An error occurred: 
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\sound.py", line 200, in play_sample
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\media\__init__.py", line 1429, in load
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\media\__init__.py", line 1405, in load
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\media\avbin.py", line 238, in __init__
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\media\avbin.py", line 196, in f
OSError: exception: access violation reading 0x00000000


This has been copied to the clipboard.
---------------------------
OK   
---------------------------
