### ISSUE TITLE
ModuleNotFoundError: No module named 'idlelib.WidgetRedirector'

### ISSUE THREAD

**Issue by petersohn** [BEEmod/BEE2.4#513]
I cannot start BEE2 because it complains about a missing module `idlelib.WidgetRedirector`.

```
 % ./bin/BEE2
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 12, in <module>
    __import__(name + "__init__")
  File "/usr/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 24, in <module>
    exec(code, m.__dict__)
  File "BEE2.pyw", line 35, in <module>
  File "/local/peet/install/portal/BEE2.4-2.4.0pr24/src/tk_tools.py", line 12, in <module>
    from idlelib.WidgetRedirector import WidgetRedirector
ModuleNotFoundError: No module named 'idlelib.WidgetRedirector'
```

I am on Arch Linux and have Python 3.6. As it turns out,  `idlelib.WidgetRedirector` can be imported under Python 2, but not under Python 3. However, trying to use Python 2 fails on installation because of a syntax error.

**Comment by TeamSpen210** [comment]
Use the dev branch, I found this issue yesterday - it was renamed in Python 3.6.

**Comment by petersohn** [comment]
I cannot compile on the dev branch. I get the following error message:

```
 % python compile_BEE2.py build
Reading translations... Done!
Translations:
en.mo
Traceback (most recent call last):
  File "compile_BEE2.py", line 43, in <module>
    get_localisation('kV-oMlhZPJEJoYPI5EQ6HaqeAc1zQ73G')
  File "compile_BEE2.py", line 38, in get_localisation
    with zip_file.open(file) as src, open('../i18n/' + filename, 'wb') as dest:
FileNotFoundError: [Errno 2] No such file or directory: '../i18n/en.mo'
```

Actually, there isn't any `i18n` directory anywhere in the repo.

**Comment by TeamSpen210** [comment]
Make one and it'll fix itself. Whoops.
