### ISSUE TITLE
Compiler fails after trying to access C:\\Users\ncrecc

### ISSUE THREAD

**Issue by ncrecc** [BEEmod/BEE2.4#526]
```
VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr24 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'use_screenshot': '1'}
[WARNING] BEE2_config.load(): Config "C:\Users
 |_crecc\Downloads\BEE2.4_pr24_win (1)\config/compile.cfg" not found! Using defaults...

[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.mod_entryexit(): Using random SP Exit (3)
[INFO] vbsp.mod_entryexit(): Using random SP Entry (5)
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: True
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (12 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[WARNING] instanceLocs._resolve(): "item_bee2_fizzler_out_relay" not a valid item!
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] vbsp.set_elev_videos(): Elevator type: RAND
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[WARNING] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.add_voice(): 0 Mid quotes
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] cond.core.check_all(): Map has attributes: ['spawn_dual', 'turret', 'deadly']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=3052, misses=303, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'multiversecave': True, 'bee_show_trigger': False, 'nomidvoices': False, 'doorcameras': True, 'rexcubepelletfizzle': False, 'funnelallowswitchedlights': True, 'allowgoomist': True, 'restartonexit': True, 'fixfizzlerbump': False, 'unlockdefault': False}
[INFO] cond.core.check_all(): Global instances: {'instances/BEE2/clean/global_ents.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: False
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.change_trig(): Editing Triggers...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/video_splitter_rand.nut"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Aug 26 2015)
 | 4 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | fixing up env_cubemap materials on brush sides...
 | ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
 | ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
 | Processing areas...done (0)
 | Building Faces...done (0)
 | Chop Details...done (0)
 | Find Visible Detail Sides...
 | Merged 416 detail faces...done (0)
 | Merging details...done (0)
 | FixTjuncs...
 | PruneNodes...
 | WriteBSP...
 | done (1)
 | writing C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.prt...Building visibility clusters...
 | done (0)
 | Finding displacement neighbors...
 | Finding lightmap sample positions...
 | Displacement Alpha : 0...1...2...3...4...5...6...7...8...9...10
 | Building Physics collision data...
 | done (0) (457879 bytes)
 | Placing detail props : 0...1...2...3...4...5...6...7...8...9...10
 | Compacting texture/material tables...
 | Reduced 2697 texinfos to 463
 | Reduced 48 texdatas to 43 (1354 bytes to 1212)
 | Writing C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.bsp
 | 
 | nummapplanes:     (  8514 / 65536 )
 | nummapbrushes:    (  1249 /  8192 )
 | nummapbrushsides: ( 10813 / 65536 )
 | num_map_overlays: (     2 /   512 )
 | nummodels:        (    31 /  1024 )
 | num_entities:     (   272 / 16384 )
 | 
 | 4 seconds elapsed
 | CDynamicFunction: Loading library 'Kernel32.dll' (75320000)
 | CDynamicFunction: Lookup of 'TryEnterCriticalSection' in 'Kernel32.dll': 77E4C8B0
 | CDynamicFunction: Closing library 'Kernel32.dll' (75320000)
 |_

[INFO] vbsp.run_vbsp(): VBSP Done!
[INFO] vbsp.process_vbsp_log(): Retrieved counts: {'entity': ('272', '16384'), 'brush': ('1249', '8192'), 'overlay': ('2', '512')}
[INFO] BEE2_config.save(): Saving changes in config "C:\Users
 |_crecc\Downloads\BEE2.4_pr24_win (1)\config/compile.cfg"!

[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3573, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 3331, in run_vbsp
  File "F:\Git\BEE2.4\src\vbsp.py", line 3392, in process_vbsp_log
  File "F:\Git\BEE2.4\src\BEE2_config.py", line 54, in save
  File "F:\Git\srctools\srctools\__init__.py", line 270, in __enter__
  File "F:\Git\srctools\srctools\__init__.py", line 261, in make_tempfile
  File "C:\Python34\lib\os.py", line 227, in makedirs
  File "C:\Python34\lib\os.py", line 227, in makedirs
  File "C:\Python34\lib\os.py", line 227, in makedirs
  File "C:\Python34\lib\os.py", line 237, in makedirs
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\ncrecc'
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3573, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 3331, in run_vbsp
  File "F:\Git\BEE2.4\src\vbsp.py", line 3392, in process_vbsp_log
  File "F:\Git\BEE2.4\src\BEE2_config.py", line 54, in save
  File "F:\Git\srctools\srctools\__init__.py", line 270, in __enter__
  File "F:\Git\srctools\srctools\__init__.py", line 261, in make_tempfile
  File "C:\Python34\lib\os.py", line 227, in makedirs
  File "C:\Python34\lib\os.py", line 227, in makedirs
  File "C:\Python34\lib\os.py", line 227, in makedirs
  File "C:\Python34\lib\os.py", line 237, in makedirs
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\ncrecc'
```

**Comment by LautaroL20** [comment]
@ncrecc - Did you unzip the Beemod installation files into the Portal 2 folder?

**Comment by ncrecc** [comment]
All I did was unzip it into Downloads, unzip the packages folder into it (both the same version), and run bee2.exe. I didn't manually put or unzip anything into the Portal 2 folder. Here's what the folder looks like after trying to compile it once:
![](http://image.prntscr.com/image/15a8e6fe0122497cbb86d76f3a1e4d71.png)

**Comment by TeamSpen210** [comment]
What is your user folder called? Try putting it at the root of your C drive.

**Comment by ncrecc** [comment]
My user folder is called ncrecc, at C:\Users\ncrecc
I'm not sure what you mean by putting it at the root- you mean just taking it out of C:\Users and putting it right in C:\ ? It sounds kind of dangerous.

**Comment by TeamSpen210** [comment]
It must be the `\\` actually. There isn't anything dangerous about the root. OH. I know why, it's a problem with the `\n` in the folder path. Just move it so that's not in the name.
