### ISSUE TITLE
BEE2 Loading Crash

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2.4#545]
This is using BEE2.4 public release and the BEE2 items Dev.
The BEE2 crashes during loading, when it finishes loading Images, and then throws this error:
---------------------------
BEE2 Error!
---------------------------
An error occurred: 
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2.pyw", line 125, in <module>
  File "F:\Git\BEE2.4\src\packageLoader.py", line 459, in load_packages
  File "F:\Git\BEE2.4\src\packageLoader.py", line 619, in setup_style_tree
Exception: No base for "ITEM_DRAW_BRIDGE", in "BEE2_1960s" style.

It looks to me like something's wrong with the 1960's drawbridge.

**Comment by Endermage77** [comment]
Actually, this looks like a duplicate of #544, sorry about that.
I'll see if reinstalling BEE2 fixes this.

**Comment by TeamSpen210** [comment]
Nope actually, it's that it needs new code to load right.

**Comment by Endermage77** [comment]
Oh. Then how do I fix this?

**Comment by Luke18033** [comment]
You fix it by getting the application dev version.
