### ISSUE TITLE
Another BEE2 Image Loading Error: P1 SP Tspen Checkpoint?

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2.4#549]
Same as the first, slightly worse, and now for another verse:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2.pyw", line 125, in <module>
  File "F:\Git\BEE2.4\src\packageLoader.py", line 459, in load_packages
  File "F:\Git\BEE2.4\src\packageLoader.py", line 619, in setup_style_tree
Exception: No base for "ITEM_TSPEN_SP_CHECKPOINT", in "BEE2_PORTAL_1" style.

I don't even know what item it's referring to here.

**Comment by Luke18033** [comment]
Stop trying to use the items dev version with the app release version. See #544, this error doesn't exist anymore. The SP checkpoint is the Chamberlock.
