### ISSUE TITLE
Beemod causes "Failure To Compile"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#551]
VBSP failed.

Traceback (most recent call last):
  File "C:\Users\Lautaro\AppData\Local\Programs\Python\Python36\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
    __import__(name + "__init__")
  File "C:\Users\Lautaro\AppData\Local\Programs\Python\Python36\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
    exec(code, m.__dict__)
  File "vbsp_launch.py", line 5, in <module>
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\vbsp.py", line 4, in <module>
    LOGGER = utils.init_logging('bee2/vbsp.log')
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\utils.py", line 781, in init_logging
    from logging import handlers
  File "C:\Users\Lautaro\AppData\Local\Programs\Python\Python36\lib\logging\handlers.py", line 26, in <module>
    import logging, socket, os, pickle, struct, time, re
  File "C:\Users\Lautaro\AppData\Local\Programs\Python\Python36\lib\socket.py", line 52, in <module>
    import os, sys, io, selectors
ModuleNotFoundError: No module named 'selectors'

**Comment by LautaroL20** [comment]
Uhmmm, was this even fixed for the dev version? I dont see the commit anywhere....

**Comment by TeamSpen210** [comment]
Ah, my logic was a bit mixed up.

**Comment by LautaroL20** [comment]
Ok, issue solved now.
