### ISSUE TITLE
Development Version showing error at launch

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#560]
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
    __import__(name + "__init__")
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
    exec(code, m.__dict__)
  File "BEE2_launch.pyw", line 3, in <module>
  File "C:\Python34\lib\multiprocessing\context.py", line 148, in freeze_support
    freeze_support()
  File "C:\Python34\lib\multiprocessing\spawn.py", line 74, in freeze_support
    spawn_main(**kwds)
  File "C:\Python34\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Python34\lib\multiprocessing\spawn.py", line 119, in _main
    return self._bootstrap()
  File "C:\Python34\lib\multiprocessing\process.py", line 273, in _bootstrap
    sys.stdout.flush()
AttributeError: 'NoneType' object has no attribute 'flush'
```

BEE2.4 launches as normal, and nothing is broken as far as I can tell.

**Comment by TeamSpen210** [comment]
Copy the traceback please, I can't know where it originated from.

**Comment by Luke18033** [comment]
Updated original post.

**Comment by Luke18033** [comment]
Bump

**Comment by TeamSpen210** [comment]
This would be to do with the loading splash screen, which I assume isn't appearing.

**Comment by Luke18033** [comment]
The splash screen is appearing...

**Comment by Luke18033** [comment]
Well, you seem to have fixed this.
