### ISSUE TITLE
"There was an error building the puzzle"

### ISSUE THREAD

**Issue by Sariiger** [BEEmod/BEE2.4#562]
Well, the title says everything, I copied the log after the error:

VRAD failed.

[INFO] vrad.main(): BEE2 VRAD hook started!
[INFO] vrad.main(): Map path is F:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\preview.bsp
[INFO] vrad.load_config(): Loading Settings...
[INFO] vrad.load_config(): Config Loaded!
[INFO] vrad.main(): Final status: is_peti=True, edit_args=True
[INFO] vrad.pack_content(): Files to pack:
[INFO] vrad.pack_content():  # "scripts/vscripts/bee2/video_splitter_specific.nut"
[INFO] vrad.pack_content(): Injected files:
[INFO] vrad.pack_content():  # "scripts/vscripts/BEE2/auto_run.nut"
[INFO] vrad.pack_content(): Packing Files!
[INFO] vrad.pack_content(): Injecting "scripts/vscripts/BEE2/auto_run.nut" into packfile.
[INFO] vrad.pack_content(): Packing complete!
[INFO] vrad.mod_screenshots(): Using automatic screenshot!
[INFO] vrad.mod_screenshots(): Chosen "..\portal2\screenshots\preview0006.jpg"
[INFO] vrad.mod_screenshots(): Map Playtested: False
[INFO] vrad.mod_screenshots(): Cleaning up screenshots...
--- Logging error ---
Traceback (most recent call last):
  File "C:\Python34\lib\logging\__init__.py", line 980, in emit
UnicodeEncodeError: 'ascii' codec can't encode character '\xe1' in position 1058: ordinal not in range(128)
Call stack:
  File "F:\Git\BEE2.4\src\utils.py", line 771, in except_handler
  File "C:\Python34\lib\logging\__init__.py", line 1414, in _log
  File "C:\Python34\lib\logging\__init__.py", line 1424, in handle
  File "C:\Python34\lib\logging\__init__.py", line 1486, in callHandlers
  File "C:\Python34\lib\logging\__init__.py", line 853, in handle
  File "C:\Python34\lib\logging\handlers.py", line 73, in emit
  File "C:\Python34\lib\logging\__init__.py", line 1046, in emit
  File "C:\Python34\lib\logging\__init__.py", line 984, in emit
Message: 'Uncaught Exception:'
Arguments: ()
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vrad.py", line 992, in <module>
  File "vrad.py", line 977, in main
  File "vrad.py", line 841, in mod_screenshots
PermissionError: [WinError 5] A hozz\xe1f\xe9r\xe9s denied: '..\\portal2\\screenshots\\config'
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vrad.py", line 992, in <module>
  File "vrad.py", line 977, in main
  File "vrad.py", line 841, in mod_screenshots
PermissionError: [WinError 5] A hozz\xe1f\xe9r\xe9s denied: '..\\portal2\\screenshots\\config'

**Comment by TeamSpen210** [comment]
Delete the `config`  folder in `F:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\screenshots\`.

**Comment by Sariiger** [comment]
Thank you so much! It worked! :D
