### ISSUE TITLE
Instant Crash???

### ISSUE THREAD

**Issue by Arynn24** [BEEmod/BEE2.4#603]
Using BEE2 on Windows 10.
It opens a loading screen for a millisecond, but the opens a error log saying this:

---------------------------
BEE2 Error!
---------------------------
An error occurred: 
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2_launch.pyw", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "F:\Git\BEE2.4\src\BEE2.py", line 79, in <module>
  File "F:\Git\BEE2.4\src\gameMan.py", line 985, in load
AttributeError: 'SplashScreen' object has no attribute 'withdraw'

**Comment by ZombiePwner1** [comment]
@Arynn24 Replace the prl 25 config files with prl 24

**Comment by TeamSpen210** [comment]
Redownload.

**Comment by LautaroL20** [comment]
@Arynn24 - Get Pre-release 27 (Packages & Application). Also, to ensure everything will work fine, you will have to do the following once installed:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
