### ISSUE TITLE
Overgrown Style causes "Failure To Compile"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#666]
```
Lautaro unpaused the game
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF E:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (9,6,5)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 119 (ms)

VBSP failed.

[INFO] cond.core.x(): No name for module "voiceLine"!
[INFO] vbsp.main(): BEE VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "E:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "E:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'voice_pack': 'BEE2_ANNOUNCER_APOC'}
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/over/items/rex/pellet_dest/head.vmf', 'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/over/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/over/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/over/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/over/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/over/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/over/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/over/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/over/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/over/items/rex/pellet_dest/static_4.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/over/items/rex/pellet_dest/head.vmf', 'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/over/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/over/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/over/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/over/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/over/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/over/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/over/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/over/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/over/items/rex/pellet_dest/static_4.vmf'})
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 1
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 1
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: True
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (22 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[INFO] cond.fizzler.fizzler_out_relay(): Fizzler data: {'marker_inst': [], 'pos_to_name': {}, 'fizz_by_name': {}, 'model': 'instances/bee2/over/items/tdb/csfi_model.vmf', 'base': 'instances/bee2/clean/items/tdb/csfi_base.vmf', 'fizz_id': 'item_tdb_csfi', 'fizz_bases': {'instances/bee2/over/items/fizz/base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/paint_fizz/base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/fr/csf_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/fr/fdf_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/fr/mif_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/death_fizz/base.vmf': ItemConnections(in_act=('branch_fizz', 'ToggleTest'), in_deact=('branch_las', 'ToggleTest'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/physler/base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/rex/pellet_field_base.vmf': ItemConnections(in_act=(None, ''), in_deact=(None, ''), out_act=('out', 'OnUser2'), out_deact=('out', 'OnUser1')), 'instances/bee2/clean/items/tdb/csfi_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, ''))}, 'fizz_models': {'instances/bee2/over/items/death_fizz_model.vmf', 'instances/bee2/over/items/fr/csf_model.vmf', 'instances/bee2/over/items/fizz/model.vmf', 'instances/bee2/over/items/paint_fizz/model.vmf', 'instances/bee2/over/items/fr/fdf_model.vmf', 'i[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[ERROR] cond.core.check_all(): Error in <BEE2_OVERGROWN>/items/obs_room:
Traceback (most recent call last):
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\conditions\__init__.py", line 483, in check_all
    condition.test(inst)
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\conditions\__init__.py", line 304, in test
    should_del = self.test_result(inst, res)
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\conditions\__init__.py", line 293, in test_result
    return func(VMF, inst, res)
  File "<string>", line 1, in <lambda>
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\conditions\__init__.py", line 1288, in res_switch
    Condition.test_result(inst, res)
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\conditions\__init__.py", line 293, in test_result
    return func(VMF, inst, res)
  File "<string>", line 1, in <lambda>
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\conditions\randomise.py", line 109, in res_random
    choice,
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\conditions\__init__.py", line 293, in test_result
    return func(VMF, inst, res)
  File "<string>", line 1, in <lambda>
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\conditions\addInstance.py", line 82, in res_add_overlay_inst
    angle = res['angles', inst['angles', '0 0 0']]
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\srctools\srctools\property_parser.py", line 620, in __getitem__
    raise ValueError("Can't index a Property without children!")
ValueError: Can't index a Property without children!

**Comment by TeamSpen210** [comment]
I forgot to push a thing.

**Comment by TeamSpen210** [comment]
I made it so you can do `"AddOverlay" "blah/blah.vmf"`, since that was getting annoying.
