### ISSUE TITLE
Load nothing from config

### ISSUE THREAD

**Issue by ClassicOldSong** [BEEmod/BEE2.4#681]
```
VBSP failed.

[INFO] vbsp.main(): BEE VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "/Users/yukino/Library/Application Support/Steam/steamapps/common/Portal 2/sdk_content/maps/preview.vmf"
[INFO] vbsp.main(): New path: "/Users/yukino/Library/Application Support/Steam/steamapps/common/Portal 2/sdk_content/maps/styled/preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'bottomless_pit': '0', 'use_screenshot': '1', 'voice_pack': 'BEE2_GLADOS_CLEAN'}
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[INFO] cond.cubes.parse_conf(): Parsed 0 cube types, 0 dropper types and 0 addons.
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "/usr/local/opt/pyenv/versions/3.6.1/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
    module.run()
  File "/usr/local/opt/pyenv/versions/3.6.1/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
    exec(code, m.__dict__)
  File "vbsp_launch.py", line 7, in <module>
  File "/Users/yukino/Works/BEE2.4/src/vbsp.py", line 3652, in main
    load_settings()
  File "/Users/yukino/Works/BEE2.4/src/vbsp.py", line 378, in load_settings
    conditions.cubes.parse_conf(conf)
  File "/Users/yukino/Works/BEE2.4/src/conditions/cubes.py", line 460, in parse_conf
    raise Exception('Cube type "{}" is missing!'.format(cube_id))
Exception: Cube type "VALVE_CUBE_STANDARD" is missing!
Traceback (most recent call last):
  File "/usr/local/opt/pyenv/versions/3.6.1/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
    module.run()
  File "/usr/local/opt/pyenv/versions/3.6.1/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
    exec(code, m.__dict__)
  File "vbsp_launch.py", line 7, in <module>
  File "/Users/yukino/Works/BEE2.4/src/vbsp.py", line 3652, in main
    load_settings()
  File "/Users/yukino/Works/BEE2.4/src/vbsp.py", line 378, in load_settings
    conditions.cubes.parse_conf(conf)
  File "/Users/yukino/Works/BEE2.4/src/conditions/cubes.py", line 460, in parse_conf
    raise Exception('Cube type "{}" is missing!'.format(cube_id))
Exception: Cube type "VALVE_CUBE_STANDARD" is missing!
```

BEE2 was directly run from .py file, while vbsp is built. Could not load any cubes from config.

**Comment by TeamSpen210** [comment]
You need the dev packages too.
