### ISSUE TITLE
Strange error when using normal (weighted) buttons in Portal 2 Editor

### ISSUE THREAD

**Issue by GameSlayar** [BEEmod/BEE2.4#687]
Getting strange error when even _trying_ to use a normal weighted button. First time using BEEMOD (2.4, pre-release 26 with p-r 25 resources)

Hopefully I haven't done anything wrong myself, please inform me if I do.

![Portal 2 Editor Screenshot](https://a.yiff.moe/nxaysj.jpg)

## Log from Dev Console:

```

VBSP failed.
 
[INFO] cond.core.x(): No name for module "voiceLine"!
[INFO] vbsp.main(): BEE2.4.0pr26 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "G:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "G:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'bottomless_pit': '0', 'use_screenshot': '1', 'voice_pack': 'BEE2_GLADOS_CLEAN'}
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 1
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 2
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (12 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[INFO] cond.fizzler.fizzler_out_relay(): Fizzler data: {'marker_inst': [], 'pos_to_name': {}, 'fizz_by_name': {}, 'model': 'instances/bee2/clean/items/tdb/csfi_model.vmf', 'base': 'instances/bee2/clean/items/tdb/csfi_base.vmf', 'fizz_id': 'item_tdb_csfi', 'fizz_bases': {'instances/bee2/clean/items/barrier_hazard_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/paint_fizz/base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/fr/csf_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/fr/fdf_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/fr/mif_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/death_fizz/base.vmf': ItemConnections(in_act=('branch_fizz', 'ToggleTest'), in_deact=('branch_las', 'ToggleTest'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/physler/base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/rex/pellet_field_base.vmf': ItemConnections(in_act=(None, ''), in_deact=(None, ''), out_act=('out', 'OnUser2'), out_deact=('out', 'OnUser1')), 'instances/bee2/clean/items/tdb/csfi_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, ''))}, 'fizz_models': {'instances/bee2/clean/items/death_fizz/model.vmf', 'instances/bee2/clean/items/rex/pellet_field_model.vmf', 'instances/bee2/clean/items/fr/mif_model.vmf', 'instances/bee2/clean/items/paint_fizz/model.vmf', 'instances/bee2/clea[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[ERROR] cond.core.check_all(): Error in <VALVE_BUTTONS>/items/floor:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 483, in check_all
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 304, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 293, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\brushes.py", line 673, in res_import_template
  File "F:\Git\BEE2.4\src\template_brush.py", line 629, in retexture_template
  File "F:\Git\srctools\srctools\vmf.py", line 1470, in normal
  File "F:\Git\srctools\srctools\vec.py", line 886, in norm
  File "F:\Git\srctools\srctools\vec.py", line 772, in mag
ValueError: math domain error
```

**Comment by LautaroL20** [comment]
I might know what is causing you from getting those weird issues, and it is when you were using past Bee2´s releases, those resouces are still in the Portal 2 sub-folders, and since the latest PRL26 does not have the ability to overwritte old resources anymore, the app its now using them. 

The solution to this annoyance:  

You will have to manually delete the following folders from Portal 2: bee2 (located at "Portal 2\sdk_content\maps\instances"), bin and bee2 (located in the main Portal 2 folder). After this, launch Bee PRL26 and make it to export the full resources. Now you should not get those weird issues anymore.

If this did not work, let me know and ill re-open this post.

**Comment by TeamSpen210** [comment]
This is a different error - something's seriously wrong with a vector value.

**Comment by Luke18033** [comment]
I had this same issue a few weeks ago, while tryng to recreate one of my old puzzles. I ended up switching to using BEE2.2 with the BEE1 palette and vanilla compilers (so BEE1 basically).

**Comment by Luke18033** [comment]
Would this be a BEE2-items issue or is it a problem with the compiler?

**Comment by TeamSpen210** [comment]
Something wrong with the compiler, and an items issue.

**Comment by LautaroL20** [comment]
@TeamSpen210 - Did you found the cause of this?
