### ISSUE TITLE
Traceback error when clicking on anything?

### ISSUE THREAD

**Issue by EXPAttack** [BEEmod/BEE2.4#689]
I've never used github nor do i know anything about coding, but whenever I click on an item in the UI to switch out for the pallete I get a traceback error.
```
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\UI.py", line 945, in drag_start
  File "F:\Git\BEE2.4\src\sound.py", line 86, in fx
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\media\__init__.py", line 473, in play
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\media\__init__.py", line 1012, in play
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\media\__init__.py", line 993, in _set_playing
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\media\__init__.py", line 1083, in _create_audio_player
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\media\drivers\directsound\__init__.py", line 502, in create_audio_player
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\media\drivers\directsound\__init__.py", line 184, in __init__
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\com.py", line 125, in <lambda>
  File "_ctypes/callproc.c", line 918, in GetResult
OSError: [WinError -2005073917] Windows Error 0x887d0003
```

At the bottom I see OSError so i wonder if it has anything to do with my OS? Please help! (User friendly guide pls ;D)

**Comment by EXPAttack** [comment]
oh yeah and i can use presets and everything and loading portal2 after exporting works perfectly fine, so that's cool. but then theres this issue. running as admin didnt fix either.

**Comment by TeamSpen210** [comment]
Go to options and turn off the sound effects. I'm not sure exactly why that happens, but that'll stop the crash.

**Comment by EXPAttack** [comment]
thanks!

**Comment by Luke18033** [comment]
It's still a bug which needs to be fixed.

**Comment by TeamSpen210** [comment]
Probably not.
