### ISSUE TITLE
Bee2 is not working.I clicked on it and it said

### ISSUE THREAD

**Issue by FriskRD** [BEEmod/BEE2.4#690]
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2.pyw", line 125, in <module>
  File "F:\Git\BEE2.4\src\packageLoader.py", line 407, in load_packages
  File "F:\Git\BEE2.4\src\packageLoader.py", line 2664, in parse
  File "F:\Git\BEE2.4\src\packageLoader.py", line 2575, in __init__
NotImplementedError
 

i just clicked it and then it loaded until it said this.can you help me?

**Comment by TeamSpen210** [comment]
Which version are you using?

**Comment by FriskRD** [comment]
the latest one

**Comment by FriskRD** [comment]
sorry but i have problems with the internet

**Comment by FriskRD** [comment]
Is there any way to fix it?

**Comment by TeamSpen210** [comment]
This doesn't look like the current version. Which exactly is it?

**Comment by TeamSpen210** [comment]
Open up `logs/BEE2.log` and check the start if you don't know.

**Comment by FriskRD** [comment]
it is pr-24

**Comment by Maroki06** [comment]
i have the same problem

**Comment by FriskRD** [comment]
So... Can it be fixed or not?

**Comment by Luke18033** [comment]
It probably already has been fixed, you just need to use the latest version.

**Comment by LautaroL20** [comment]
@FriskRD @Maroki06 - Get Pre-Release 27 (Packages & Application), since this is most likely fixed now, however once you installed the latest version, you will have to do the following:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
