### ISSUE TITLE
Unable to install BEE2_pr24

### ISSUE THREAD

**Issue by Maroki06** [BEEmod/BEE2.4#695]
**When I choose the game executable, the "installing window" (with theese packages, music etc. loading bars) an error shows up. Here is the log (I censored the name for privacy):**

[INFO] utils.setup_localisations(): Language: 'pl_PL'
[DEBUG] utils.setup_localisations(): Language codes: ['pl_PL.ISO8859-2', 'pl_PL', 'pl.ISO8859-2', 'pl']
[WARNING] utils.setup_localisations(): Can't find translation for codes: ['pl_PL.ISO8859-2', 'pl_PL', 'pl.ISO8859-2', 'pl']!
[WARNING] BEE2_config.load(): Config "../config\packages.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\games.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\compile.cfg" not found! Using defaults...
[INFO] BEE2_config.save(): Saving changes in config "../config\compile.cfg"!
[WARNING] BEE2_config.load(): Config "../config\item_configs.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\config.cfg" not found! Using defaults...
[INFO] BEE2_config.save(): Saving changes in config "../config\config.cfg"!
[DEBUG] gameMan.edit_gameinfo(): Adding gameinfo hook to D:/SteamLibrary/steamapps/common/Portal 2\portal2_dlc2\gameinfo.txt
[DEBUG] gameMan.edit_gameinfo(): Adding gameinfo hook to D:/SteamLibrary/steamapps/common/Portal 2\portal2_dlc1\gameinfo.txt
[DEBUG] gameMan.edit_gameinfo(): Adding gameinfo hook to D:/SteamLibrary/steamapps/common/Portal 2\portal2\gameinfo.txt
[INFO] BEE2_config.save(): Saving changes in config "../config\games.cfg"!
[INFO] BEE2.<module>(): Loading Packages...
[DEBUG] packageLoader.find_packages(): Reading package "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\apTag"
[DEBUG] packageLoader.find_packages(): Checking subdir "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\apTag" for packages...
[DEBUG] packageLoader.find_packages(): Reading package "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\apTag\tagItems"
[DEBUG] packageLoader.find_packages(): Reading package "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\apTag\tagMusic"
[DEBUG] packageLoader.find_packages(): Reading package "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\apTag\tagVO"
[DEBUG] packageLoader.find_packages(): Reading package "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\bee1"
[DEBUG] packageLoader.find_packages(): Checking subdir "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\bee1" for packages...
[DEBUG] packageLoader.find_packages(): Reading package "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\bee1\beemod"
[DEBUG] packageLoader.find_packages(): Reading package "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\bee1\pellets"
[INFO] BEE2_config.save(): Saving changes in config "../config\config.cfg"!
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\FakeZip.py", line 57, in open
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\CENSORED\\Downloads\\BEE2.4_pr24_win\\packages\\bee1\\info.txt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\packageLoader.py", line 281, in find_packages
  File "F:\Git\BEE2.4\src\FakeZip.py", line 59, in open
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2.pyw", line 125, in <module>
  File "F:\Git\BEE2.4\src\packageLoader.py", line 350, in load_packages
  File "F:\Git\BEE2.4\src\packageLoader.py", line 286, in find_packages
  File "F:\Git\BEE2.4\src\packageLoader.py", line 293, in find_packages
  File "F:\Git\srctools\srctools\property_parser.py", line 303, in parse
  File "C:\Python34\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 701: character maps to <undefined>
[INFO] utils.setup_localisations(): Language: 'pl_PL'
[DEBUG] utils.setup_localisations(): Language codes: ['pl_PL.ISO8859-2', 'pl_PL', 'pl.ISO8859-2', 'pl']
[WARNING] utils.setup_localisations(): Can't find translation for codes: ['pl_PL.ISO8859-2', 'pl_PL', 'pl.ISO8859-2', 'pl']!
[WARNING] BEE2_config.load(): Config "../config\packages.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\item_configs.cfg" not found! Using defaults...
[INFO] BEE2.<module>(): Loading Packages...
[DEBUG] packageLoader.find_packages(): Reading package "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\apTag"
[DEBUG] packageLoader.find_packages(): Checking subdir "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\apTag" for packages...
[DEBUG] packageLoader.find_packages(): Reading package "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\apTag\tagItems"
[DEBUG] packageLoader.find_packages(): Reading package "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\apTag\tagMusic"
[DEBUG] packageLoader.find_packages(): Reading package "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\apTag\tagVO"
[DEBUG] packageLoader.find_packages(): Reading package "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\bee1"
[DEBUG] packageLoader.find_packages(): Checking subdir "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\bee1" for packages...
[DEBUG] packageLoader.find_packages(): Reading package "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\bee1\beemod"
[DEBUG] packageLoader.find_packages(): Reading package "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\bee1\pellets"
[INFO] BEE2_config.save(): Saving changes in config "../config\config.cfg"!
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\FakeZip.py", line 57, in open
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\CENSORED\\Downloads\\BEE2.4_pr24_win\\packages\\bee1\\info.txt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\packageLoader.py", line 281, in find_packages
  File "F:\Git\BEE2.4\src\FakeZip.py", line 59, in open
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2.pyw", line 125, in <module>
  File "F:\Git\BEE2.4\src\packageLoader.py", line 350, in load_packages
  File "F:\Git\BEE2.4\src\packageLoader.py", line 286, in find_packages
  File "F:\Git\BEE2.4\src\packageLoader.py", line 293, in find_packages
  File "F:\Git\srctools\srctools\property_parser.py", line 303, in parse
  File "C:\Python34\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 701: character maps to <undefined>
[INFO] utils.setup_localisations(): Language: 'pl_PL'
[DEBUG] utils.setup_localisations(): Language codes: ['pl_PL.ISO8859-2', 'pl_PL', 'pl.ISO8859-2', 'pl']
[WARNING] utils.setup_localisations(): Can't find translation for codes: ['pl_PL.ISO8859-2', 'pl_PL', 'pl.ISO8859-2', 'pl']!
[WARNING] BEE2_config.load(): Config "../config\packages.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\item_configs.cfg" not found! Using defaults...
[INFO] BEE2.<module>(): Loading Packages...
[DEBUG] packageLoader.find_packages(): Reading package "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\apTag"
[DEBUG] packageLoader.find_packages(): Checking subdir "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\apTag" for packages...
[DEBUG] packageLoader.find_packages(): Reading package "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\apTag\tagItems"
[DEBUG] packageLoader.find_packages(): Reading package "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\apTag\tagMusic"
[DEBUG] packageLoader.find_packages(): Reading package "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\apTag\tagVO"
[DEBUG] packageLoader.find_packages(): Reading package "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\bee1"
[DEBUG] packageLoader.find_packages(): Checking subdir "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\bee1" for packages...
[DEBUG] packageLoader.find_packages(): Reading package "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\bee1\beemod"
[DEBUG] packageLoader.find_packages(): Reading package "c:\Users\CENSORED\Downloads\BEE2.4_pr24_win\packages\bee1\pellets"
[INFO] BEE2_config.save(): Saving changes in config "../config\config.cfg"!
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\FakeZip.py", line 57, in open
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\CENSORED\\Downloads\\BEE2.4_pr24_win\\packages\\bee1\\info.txt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\packageLoader.py", line 281, in find_packages
  File "F:\Git\BEE2.4\src\FakeZip.py", line 59, in open
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2.pyw", line 125, in <module>
  File "F:\Git\BEE2.4\src\packageLoader.py", line 350, in load_packages
  File "F:\Git\BEE2.4\src\packageLoader.py", line 286, in find_packages
  File "F:\Git\BEE2.4\src\packageLoader.py", line 293, in find_packages
  File "F:\Git\srctools\srctools\property_parser.py", line 303, in parse
  File "C:\Python34\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 701: character maps to <undefined>
[INFO] utils.setup_localisations(): Language: 'pl_PL'
[DEBUG] utils.setup_localisations(): Language codes: ['pl_PL.ISO8859-2', 'pl_PL', 'pl.ISO8859-2', 'pl']
[WARNING] utils.setup_localisations(): Can't find translation for codes: ['pl_PL.ISO8859-2', 'pl_PL', 'pl.ISO8859-2', 'pl']!
[WARNING] BEE2_config.load(): Config "../config\packages.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\item_configs.cfg" not found! Using defaults...
[INFO] BEE2.<module>(): Loading Packages...
[DEBUG] packageLoader.find_packages(): Reading package "d:\BEE2\packages\apTag"
[DEBUG] packageLoader.find_packages(): Checking subdir "d:\BEE2\packages\apTag" for packages...
[DEBUG] packageLoader.find_packages(): Reading package "d:\BEE2\packages\apTag\tagItems"
[DEBUG] packageLoader.find_packages(): Reading package "d:\BEE2\packages\apTag\tagMusic"
[DEBUG] packageLoader.find_packages(): Reading package "d:\BEE2\packages\apTag\tagVO"
[DEBUG] packageLoader.find_packages(): Reading package "d:\BEE2\packages\bee1"
[DEBUG] packageLoader.find_packages(): Checking subdir "d:\BEE2\packages\bee1" for packages...
[DEBUG] packageLoader.find_packages(): Reading package "d:\BEE2\packages\bee1\beemod"
[DEBUG] packageLoader.find_packages(): Reading package "d:\BEE2\packages\bee1\pellets"
[INFO] BEE2_config.save(): Saving changes in config "../config\config.cfg"!
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\FakeZip.py", line 57, in open
FileNotFoundError: [Errno 2] No such file or directory: 'd:\\BEE2\\packages\\bee1\\info.txt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\packageLoader.py", line 281, in find_packages
  File "F:\Git\BEE2.4\src\FakeZip.py", line 59, in open
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2.pyw", line 125, in <module>
  File "F:\Git\BEE2.4\src\packageLoader.py", line 350, in load_packages
  File "F:\Git\BEE2.4\src\packageLoader.py", line 286, in find_packages
  File "F:\Git\BEE2.4\src\packageLoader.py", line 293, in find_packages
  File "F:\Git\srctools\srctools\property_parser.py", line 303, in parse
  File "C:\Python34\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 701: character maps to <undefined>

**Comment by TeamSpen210** [comment]
Use the zipped packages.

**Comment by Maroki06** [comment]
@TeamSpen210 what? what do you mean?

**Comment by LautaroL20** [comment]
Make sure you download compatible versions, if you are using the outdated PRL24, make sure to also download their correct packages version for it, here is the packages page: https://github.com/BEEmod/BEE2-items/releases
