### ISSUE TITLE
Bee2 Error How i Fix?

### ISSUE THREAD

**Issue by Gogoyle50** [BEEmod/BEE2.4#701]
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2.pyw", line 125, in <module>
  File "F:\Git\BEE2.4\src\packageLoader.py", line 407, in load_packages
  File "F:\Git\BEE2.4\src\packageLoader.py", line 2664, in parse
  File "F:\Git\BEE2.4\src\packageLoader.py", line 2575, in __init__
NotImplementedError

**Comment by LautaroL20** [comment]
Please people, when you post an issue, be as more detailed as possible.... Example: Which Style, items were you using, the Pre-release version, and if in the past you were using older beemod versions. Otherwise we can not help any of you.
