### ISSUE TITLE
Help, BeeMod doenst work properly

### ISSUE THREAD

**Issue by randomperson4** [BEEmod/BEE2.4#723]
When i create a map it says "There was an error creating the puzzle."

i have this error in the console 

VBSP failed.

[INFO] cond.core.x(): No name for module "voiceLine"!
[INFO] vbsp.main(): BEE2.4.0pr26 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp.load_settings(): Error: No vbsp_config file!
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3578, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 359, in load_settings
  File "F:\Git\BEE2.4\src\template_brush.py", line 309, in load_templates
FileNotFoundError: [Errno 2] No such file or directory: 'bee2/templates.vmf'
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3578, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 359, in load_settings
  File "F:\Git\BEE2.4\src\template_brush.py", line 309, in load_templates
FileNotFoundError: [Errno 2] No such file or directory: 'bee2/templates.vmf'

**Comment by LautaroL20** [comment]
This clearly seems to be an issue caused by the game for using old resources from past Beemod releases, to solving this annoyance, you will have to do the following:

1. Open Beemod and click on File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> Yes.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and installed the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7 - 10.

5. Click on File ----> Options ----> Development, and now uncheck the option "Preserve Game Directories".

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!

**Comment by randomperson4** [comment]
Thanks, its working now! 👍🏼

**Comment by LautaroL20** [comment]
Good to know, this proves me that my premade text for these scenarios is useful!

**Comment by Luke18033** [comment]
GitHub actually has a way to create a "saved reply", are you using that?

**Comment by LautaroL20** [comment]
No, i just maked a .txt file contaning the premade reply. I did not know that Github had such feature, how does it work?

**Comment by Luke18033** [comment]
Go to your settings, there should be a "Saved Replies" tab on the left. Once you've made a saved reply you can insert it by using the arrow button at the top of the comment input box.
