### ISSUE TITLE
Can't change polarity of funnel.

### ISSUE THREAD

**Issue by CrashGit** [BEEmod/BEE2.4#743]
So I went back to an old map I made in the past with beeMod and it wouldn't compile giving this error at the end of the red text: 

`ValueError: Excursion Funnel "tb1323624" has inputs, but no valid types!`

When I removed the connection to the funnel, it compiled just fine but made the puzzle impossible obviously. I tried all the button types to no avail. Also tried deleting the funnel and putting a new one in. 

Full error in console:

```
VBSP failed.

[INFO] cond.core.x(): No name for module "voiceLine"!
[INFO] vbsp.main(): BEE2.4.0p425 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'bottomless_pit': '0', 'use_screenshot': '1', 'voice_pack': 'BEE2_WHEATLEY'}
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3587, in main
  File "F:\Git\BEE2.4\src\connections.py", line 314, in calc_connections
ValueError: Excursion Funnel "tb1323624" has inputs, but no valid types!
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3587, in main
  File "F:\Git\BEE2.4\src\connections.py", line 314, in calc_connections
ValueError: Excursion Funnel "tb1323624" has inputs, but no valid types!



```

**Comment by TeamSpen210** [comment]
`[INFO] vbsp.main(): BEE2.4.0p425 VBSP hook initiallised.`

Get PR26.
