### ISSUE TITLE
Issue Starting Up

### ISSUE THREAD

**Issue by cheezkid26** [BEEmod/BEE2.4#798]
BEE2.4 is not starting properly. It opens up the startup window, and shows the image and loading progress, but does not load. It says:
Packages: (0/0)
Loading Objects: (0/???)
Loading Images: (0/???)
Initializing UI: (0/15)
And it stays like that.                                                                    
An error window also pops up, saying something about files in lines? I don't know. I'd copy and paste the log but it crashes and doesn't let me copy anything. 
I use Windows 10, and before anyone says anything about that being the issue, my laptop runs Windows 10, and it works just fine on that. Maybe it's my new PC, I don't know.
Anyone know anything about this?

**Comment by TeamSpen210** [comment]
Open up `BEE2/logs/BEE2.error.log`, and copy-paste from there.

**Comment by cheezkid26** [comment]
Alright. Here's the log: 
[WARNING] BEE2_config.load(): Config "../config\packages.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\item_cust_configs.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\games.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\compile.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\item_configs.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\config.cfg" not found! Using defaults...
[ERROR] selectorWin.__init__(): No items for window "Select Skyboxes"!
[ERROR] selectorWin.__init__(): No items for window "Select Style"!
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2_launch.pyw", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "F:\Git\BEE2.4\src\BEE2.py", line 105, in <module>
  File "F:\Git\BEE2.4\src\UI.py", line 697, in load_packages
KeyError: 'BEE2_CLEAN'
[WARNING] BEE2_config.load(): Config "../config\packages.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\item_cust_configs.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\item_configs.cfg" not found! Using defaults...
[ERROR] selectorWin.__init__(): No items for window "Select Skyboxes"!
[ERROR] selectorWin.__init__(): No items for window "Select Style"!
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2_launch.pyw", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "F:\Git\BEE2.4\src\BEE2.py", line 105, in <module>
  File "F:\Git\BEE2.4\src\UI.py", line 697, in load_packages
KeyError: 'BEE2_CLEAN'
[WARNING] BEE2_config.load(): Config "../config\packages.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\item_cust_configs.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\item_configs.cfg" not found! Using defaults...
[ERROR] selectorWin.__init__(): No items for window "Select Skyboxes"!
[ERROR] selectorWin.__init__(): No items for window "Select Style"!
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2_launch.pyw", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "F:\Git\BEE2.4\src\BEE2.py", line 105, in <module>
  File "F:\Git\BEE2.4\src\UI.py", line 697, in load_packages
KeyError: 'BEE2_CLEAN'
[WARNING] BEE2_config.load(): Config "../config\packages.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\item_cust_configs.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\item_configs.cfg" not found! Using defaults...
[ERROR] selectorWin.__init__(): No items for window "Select Skyboxes"!
[ERROR] selectorWin.__init__(): No items for window "Select Style"!
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2_launch.pyw", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "F:\Git\BEE2.4\src\BEE2.py", line 105, in <module>
  File "F:\Git\BEE2.4\src\UI.py", line 697, in load_packages
KeyError: 'BEE2_CLEAN'
[WARNING] BEE2_config.load(): Config "../config\packages.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\item_cust_configs.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\item_configs.cfg" not found! Using defaults...
[ERROR] selectorWin.__init__(): No items for window "Select Skyboxes"!
[ERROR] selectorWin.__init__(): No items for window "Select Style"!
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2_launch.pyw", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "F:\Git\BEE2.4\src\BEE2.py", line 105, in <module>
  File "F:\Git\BEE2.4\src\UI.py", line 697, in load_packages
KeyError: 'BEE2_CLEAN'
[WARNING] BEE2_config.load(): Config "../config\packages.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\item_cust_configs.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\item_configs.cfg" not found! Using defaults...
[ERROR] selectorWin.__init__(): No items for window "Select Skyboxes"!
[ERROR] selectorWin.__init__(): No items for window "Select Style"!
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2_launch.pyw", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "F:\Git\BEE2.4\src\BEE2.py", line 105, in <module>
  File "F:\Git\BEE2.4\src\UI.py", line 697, in load_packages
KeyError: 'BEE2_CLEAN'

Thanks for the quick response!

**Comment by TeamSpen210** [comment]
Have you downloaded the packages?

**Comment by cheezkid26** [comment]
Yes, and it launched. However, the last three times I did, they didn't work.
Thanks for the help!
