### ISSUE TITLE
Bee Mod 2.4 compiling error!

### ISSUE THREAD

**Issue by troublemaker139** [BEEmod/BEE2.4#805]
Before installing Beemod portal 2 editor worked fine and once i installed beemod compile errors started

Here is the dev console log:

troublemaker139 unpaused the game
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,7,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 76 (ms)

VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr27 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'voice_pack': 'BEE2_CAVE_50s'}
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_piston_platform> (Valid: {'piston_bottom_0': 'instances/bee2/50s/items/pist_plat/plat_0.vmf', 'piston_bottom_1': 'instances/bee2/50s/items/pist_plat/plat_1.vmf', 'piston_bottom_2': 'instances/bee2/50s/items/pist_plat/plat_2.vmf', 'piston_bottom_3': 'instances/bee2/50s/items/pist_plat/plat_3.vmf', 'piston_static_0': 'instances/bee2/50s/items/pist_plat/static_0.vmf', 'piston_static_1': 'instances/bee2/50s/items/pist_plat/static_1.vmf', 'piston_static_2': 'instances/bee2/50s/items/pist_plat/static_2.vmf', 'piston_static_3': 'instances/bee2/50s/items/pist_plat/static_3.vmf', 'piston_static_4': 'instances/bee2/50s/items/pist_plat/static_4.vmf', 'piston_logic_0': 'instances/bee2/logic/piston/logic_0.vmf', 'piston_logic_1': 'instances/bee2/logic/piston/logic_1.vmf', 'piston_logic_2': 'instances/bee2/logic/piston/logic_2.vmf', 'piston_logic_3': 'instances/bee2/logic/piston/logic_3.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_piston_platform> (Valid: {'piston_bottom_0': 'instances/bee2/50s/items/pist_plat/plat_0.vmf', 'piston_bottom_1': 'instances/bee2/50s/items/pist_plat/plat_1.vmf', 'piston_bottom_2': 'instances/bee2/50s/items/pist_plat/plat_2.vmf', 'piston_bottom_3': 'instances/bee2/50s/items/pist_plat/plat_3.vmf', 'piston_static_0': 'instances/bee2/50s/items/pist_plat/static_0.vmf', 'piston_static_1': 'instances/bee2/50s/items/pist_plat/static_1.vmf', 'piston_static_2': 'instances/bee2/50s/items/pist_plat/static_2.vmf', 'piston_static_3': 'instances/bee2/50s/items/pist_plat/static_3.vmf', 'piston_static_4': 'instances/bee2/50s/items/pist_plat/static_4.vmf', 'piston_logic_0': 'instances/bee2/logic/piston/logic_0.vmf', 'piston_logic_1': 'instances/bee2/logic/piston/logic_1.vmf', 'piston_logic_2': 'instances/bee2/logic/piston/logic_2.vmf', 'piston_logic_3': 'instances/bee2/logic/piston/logic_3.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/50s/items/rex/pellet_dest/head.vmf', 'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/50s/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/50s/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/50s/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/50s/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/50s/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/50s/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/50s/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/50s/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/50s/items/rex/pellet_dest/static_4.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/50s/items/rex/pellet_dest/head.vmf', 'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/50s/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/50s/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/50s/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/50s/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/50s/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/50s/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/50s/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/50s/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/50s/items/rex/pellet_dest/static_4.vmf'})
[INFO] cond.cubes.parse_conf(): Parsed 0 cube types, 0 dropper types and 0 addons.
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3698, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 335, in load_settings
  File "F:\Git\BEE2.4\src\conditions\cubes.py", line 537, in parse_conf
Exception: Cube type "VALVE_CUBE_STANDARD" is missing!
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3698, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 335, in load_settings
  File "F:\Git\BEE2.4\src\conditions\cubes.py", line 537, in parse_conf
Exception: Cube type "VALVE_CUBE_STANDARD" is missing!

troublemaker139 unpaused the game
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198175471417\autosave.p2c
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,7,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 79 (ms)

VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr27 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'voice_pack': 'BEE2_CAVE_50s'}
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_piston_platform> (Valid: {'piston_bottom_0': 'instances/bee2/50s/items/pist_plat/plat_0.vmf', 'piston_bottom_1': 'instances/bee2/50s/items/pist_plat/plat_1.vmf', 'piston_bottom_2': 'instances/bee2/50s/items/pist_plat/plat_2.vmf', 'piston_bottom_3': 'instances/bee2/50s/items/pist_plat/plat_3.vmf', 'piston_static_0': 'instances/bee2/50s/items/pist_plat/static_0.vmf', 'piston_static_1': 'instances/bee2/50s/items/pist_plat/static_1.vmf', 'piston_static_2': 'instances/bee2/50s/items/pist_plat/static_2.vmf', 'piston_static_3': 'instances/bee2/50s/items/pist_plat/static_3.vmf', 'piston_static_4': 'instances/bee2/50s/items/pist_plat/static_4.vmf', 'piston_logic_0': 'instances/bee2/logic/piston/logic_0.vmf', 'piston_logic_1': 'instances/bee2/logic/piston/logic_1.vmf', 'piston_logic_2': 'instances/bee2/logic/piston/logic_2.vmf', 'piston_logic_3': 'instances/bee2/logic/piston/logic_3.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_piston_platform> (Valid: {'piston_bottom_0': 'instances/bee2/50s/items/pist_plat/plat_0.vmf', 'piston_bottom_1': 'instances/bee2/50s/items/pist_plat/plat_1.vmf', 'piston_bottom_2': 'instances/bee2/50s/items/pist_plat/plat_2.vmf', 'piston_bottom_3': 'instances/bee2/50s/items/pist_plat/plat_3.vmf', 'piston_static_0': 'instances/bee2/50s/items/pist_plat/static_0.vmf', 'piston_static_1': 'instances/bee2/50s/items/pist_plat/static_1.vmf', 'piston_static_2': 'instances/bee2/50s/items/pist_plat/static_2.vmf', 'piston_static_3': 'instances/bee2/50s/items/pist_plat/static_3.vmf', 'piston_static_4': 'instances/bee2/50s/items/pist_plat/static_4.vmf', 'piston_logic_0': 'instances/bee2/logic/piston/logic_0.vmf', 'piston_logic_1': 'instances/bee2/logic/piston/logic_1.vmf', 'piston_logic_2': 'instances/bee2/logic/piston/logic_2.vmf', 'piston_logic_3': 'instances/bee2/logic/piston/logic_3.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/50s/items/rex/pellet_dest/head.vmf', 'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/50s/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/50s/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/50s/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/50s/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/50s/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/50s/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/50s/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/50s/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/50s/items/rex/pellet_dest/static_4.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/50s/items/rex/pellet_dest/head.vmf', 'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/50s/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/50s/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/50s/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/50s/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/50s/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/50s/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/50s/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/50s/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/50s/items/rex/pellet_dest/static_4.vmf'})
[INFO] cond.cubes.parse_conf(): Parsed 0 cube types, 0 dropper types and 0 addons.
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3698, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 335, in load_settings
  File "F:\Git\BEE2.4\src\conditions\cubes.py", line 537, in parse_conf
Exception: Cube type "VALVE_CUBE_STANDARD" is missing!
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3698, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 335, in load_settings
  File "F:\Git\BEE2.4\src\conditions\cubes.py", line 537, in parse_conf
Exception: Cube type "VALVE_CUBE_STANDARD" is missing!

troublemaker139 unpaused the game

**Comment by troublemaker139** [comment]
Please someone help i want to make maps! And Hammer is just annoying!

**Comment by TeamSpen210** [comment]
Somehow you've loaded configs which don't contain definitions for the cubes. That's a problem. Are you using the correct (latest) packages release?

**Comment by troublemaker139** [comment]
Im pretty sure, ill double check

**Comment by troublemaker139** [comment]
Im using the Pre-Release 27 with the Pre-Release 25 (Packages)

Is that Right?

**Comment by TeamSpen210** [comment]
No, you need the Pr27 packages. That's your problem, I changed things which make earlier versions incompatible.

**Comment by CaliMari** [comment]
In Code > Scroll Down > Item Packages

**Comment by troublemaker139** [comment]
Alright, I found it! Thank You!

**Comment by CaliMari** [comment]
You are welcome!
