### ISSUE TITLE
VRAD something

### ISSUE THREAD

**Issue by troublemaker139** [BEEmod/BEE2.4#810]
VRAD failed.

[INFO] vrad.main(): BEE2 VRAD hook started!
[INFO] vrad.main(): Map path is C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\preview.bsp
[INFO] vrad.load_config(): Loading Settings...
[INFO] vrad.load_config(): Config Loaded!
[INFO] vrad.main(): Final status: is_peti=True, edit_args=True
[INFO] vrad.main(): Reading BSP
[INFO] vrad.main(): Done!
[INFO] vrad.gen_sound_manifest(): Written new soundscripts_manifest..
[INFO] vrad.pack_content(): Files to pack:
[INFO] vrad.pack_content():  # "materials/bee2/50s/indicator_broken_1.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/50s/indicator_broken_2.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/50s/indicator_norm_1.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/50s/indicator_norm_2.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/fizz/fizz_side.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/fizz_sides/side_color_1a3366.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/grate_player_clip.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/underground_woodwall003c.vmt"
[INFO] vrad.pack_content():  # "models/bee2/props_underground/dropper_fix.mdl"
[INFO] vrad.pack_content():  # "sound/music/sp_a3_speed_ramp_b1.wav"
[INFO] vrad.pack_content():  # "sound/music/sp_a3_speed_ramp_c1.wav"
[INFO] vrad.pack_content():  # "sound/music/sp_a3_speed_ramp_c2.wav"
[INFO] vrad.pack_content():  # "sound/music/sp_a3_speed_ramp_c3.wav"
[INFO] vrad.pack_content(): Potential additional files:
[INFO] vrad.pack_content(): Injected files:
[INFO] vrad.pack_content():  # "scripts/game_sounds_manifest.txt"
[INFO] vrad.pack_content():  # "scripts/BEE2_generated_music.txt"
[INFO] vrad.pack_content():  # "scripts/vscripts/bee2/auto_run.nut"
[INFO] vrad.pack_content(): Packing Files!
[WARNING] vrad.pack_file(): "bee2/sound/music/sp_a3_speed_ramp_c3.wav" not found! (May be OK if not custom)
[WARNING] vrad.pack_file(): "bee2/sound/music/sp_a3_speed_ramp_b1.wav" not found! (May be OK if not custom)
[WARNING] vrad.pack_file(): "bee2/sound/music/sp_a3_speed_ramp_c1.wav" not found! (May be OK if not custom)
[WARNING] vrad.pack_file(): "bee2/sound/music/sp_a3_speed_ramp_c2.wav" not found! (May be OK if not custom)
[INFO] vrad.pack_content(): Injecting "scripts/game_sounds_manifest.txt" into packfile.
[INFO] vrad.pack_content(): Injecting "scripts/BEE2_generated_music.txt" into packfile.
[INFO] vrad.pack_content(): Injecting "scripts/vscripts/bee2/auto_run.nut" into packfile.
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vrad.py", line 1002, in <module>
  File "vrad.py", line 982, in main
  File "vrad.py", line 749, in pack_content
  File "F:\Git\srctools\srctools\bsp.py", line 199, in replace_lump
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\Portal 2\\sdk_content\\maps\\preview.bsp'
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vrad.py", line 1002, in <module>
  File "vrad.py", line 982, in main
  File "vrad.py", line 749, in pack_content
  File "F:\Git\srctools\srctools\bsp.py", line 199, in replace_lump
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\Portal 2\\sdk_content\\maps\\preview.bsp'

This appears after compiling

**Comment by LautaroL20** [comment]
This clearly seems to be an issue in the game caused by using old resources from past Beemod releases, to solving this annoyance, you will have to do the following:

1 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2 - Wait 1 minute while Beemod removes their resources from Portal 2.

3 - Verify the Game Cache Files. 

4 - Make sure to have downloaded and unzipped the latest Packages & Application version of Beemod, and both must have to be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application) 
https://github.com/BEEmod/BEE2-items/releases (Packages)

Note that if you are running Beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

6 - Now choose your favorite Items & Style and export your palette to the game.

7 - Make sure to save these steps in a text file in case you get similar issues in the future.

8 - Happy mapmaking!
