### ISSUE TITLE
Signage in P1 style doesn't work

### ISSUE THREAD

**Issue by Firepal** [BEEmod/BEE2.4#844]
When i try to compile a P1 level while a signage item is present, 
the level stops being generated, and a build error happens.
I checked the console, and this is what i noticed in the log:

[ERROR] cond.core.check_all(): **Error in <BEE2_SIGNAGE>/items/sign_p1**:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 485, in check_all
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 304, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 293, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 1217, in res_sub_condition
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 304, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 293, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 1217, in res_sub_condition
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 304, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 293, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 1217, in res_sub_condition
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 304, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 293, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 1217, in res_sub_condition
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 304, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 293, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\entities.py", line 98, in res_insert_overlay
  File "F:\Git\BEE2.4\src\template_brush.py", line 467, in import_template
  File "F:\Git\BEE2.4\src\template_brush.py", line 425, in get_template
template_brush.InvalidTemplateName: **Template not found: "bee2_signage_clean_sign2_floor"**

**Comment by Luke18033** [comment]
This issue was moved to BEEmod/BEE2-items#2512

**Comment by LautaroL20** [comment]
@Luke18033 - Do not forget to apply the "Packages Issue" when closing the issue.
