### ISSUE TITLE
ImportError: cannot import name 'Vec'

### ISSUE THREAD

**Issue by torzod** [BEEmod/BEE2.4#891]
When running `BEE2_launch.pyw` in Arch Linux in Python 3.6.4, i am getting the following output:
```Traceback (most recent call last):
  File "BEE2_launch.pyw", line 17, in <module>
    import BEE2
  File "/home/foobar/bee/src/BEE2.4-2.4.0pr29/src/BEE2.py", line 9, in <module>
    import tk_tools
  File "/home/foobar/bee/src/BEE2.4-2.4.0pr29/src/tk_tools.py", line 64, in <module>
    import img
  File "/home/foobar/bee/src/BEE2.4-2.4.0pr29/src/img.py", line 10, in <module>
    from srctools import Vec
ImportError: cannot import name 'Vec'
```

**Comment by TeamSpen210** [comment]
You'll want to clone `https://github.com/TeamSpen210/srctools`, and add it to `PYTHONPATH`.
