### ISSUE TITLE
[Crash] BeeMod crashes while initalising Ui

### ISSUE THREAD

**Issue by Jaxinator03** [BEEmod/BEE2.4#927]
After using this amazing program for years, I just started installing it on my new PC, and was hit with this error message. (Note I did try to remove and reinstall, same error) 
UPDATE: Same happens with older editions (28)
I] paletteLoader: Loading "LAST_EXPORT.bee2_palette"
[I] paletteLoader: Loading "original.bee2_palette"
[I] BEE2: Done!
[I] BEE2: Loading Item Translations...
[E] (unknown file): Uncaught Exception:
Traceback (most recent call last):
  File "F:\Git\srctools\srctools\property_parser.py", line 650, in __getitem__
  File "F:\Git\srctools\srctools\property_parser.py", line 436, in _get_value
srctools.property_parser.NoKeyError: No key language!

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2_launch.pyw", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "F:\Git\BEE2.4\src\BEE2.py", line 115, in <module>
  File "F:\Git\BEE2.4\src\gameMan.py", line 991, in init_trans
  File "F:\Git\srctools\srctools\property_parser.py", line 652, in __getitem__
IndexError: No key language!

**Comment by TeamSpen210** [comment]
Yeah, that should just silently be ignored. Here's a fix: go to your start menu, and search "environment variables". Select the user option. Then add a variable named 'BEE2_P2_LANG`, with a value of `english` (or whatever preferred language for Portal 2).

**Comment by Jaxinator03** [comment]
Yep that fixed this issue, thank so much for your help!
