### ISSUE TITLE
Error Importing to Portal 2

### ISSUE THREAD

**Issue by shkmaru** [BEEmod/BEE2.4#946]
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\UI.py", line 840, in export_editoritems
  File "F:\Git\BEE2.4\src\gameMan.py", line 723, in export
  File "F:\Git\BEE2.4\src\gameMan.py", line 475, in refresh_cache
PermissionError: [WinError 5] Access is denied: 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\bee2\\bin\\avbin.dll'

I have Python 3.7 and BEEmod application and package 2.4pr29.
Export options on Behind the Scenes, suggested properties.
PeTI thumbnail.
Custom Palette with partial, flat  and window blocks, bomb cube, catwalk, neurotoxin timer and vent, and other uncommon items.

**Comment by HugoBDesigner** [comment]
Try this:
https://github.com/BEEmod/BEE2-items/wiki/Updating-Beemod
