### ISSUE TITLE
Module? `srctools.filesys` not found

### ISSUE THREAD

**Issue by sirtomato999** [BEEmod/BEE2.4#952]
Version: 2.4.0pr29

Ok, so after compiling bee, I move to the `./build_BEE2/bin` directory, and run the BEE2 executable, and I get this error.
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
    module.run()
  File "/usr/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
    exec(code, m.__dict__)
  File "BEE2_launch.pyw", line 17, in <module>
  File "/home/matthew/downloads/BEE2.4-2.4.0pr29/src/BEE2.py", line 9, in <module>
    import tk_tools
  File "/home/matthew/downloads/BEE2.4-2.4.0pr29/src/tk_tools.py", line 64, in <module>
    import img
  File "/home/matthew/downloads/BEE2.4-2.4.0pr29/src/img.py", line 11, in <module>
    from srctools.filesys import FileSystem, RawFileSystem, FileSystemChain
ModuleNotFoundError: No module named 'srctools.filesys'
```
Googling ["srctools.filesys" python](https://www.google.com/search?q="srctools.filesys"+python&oq="srctools.filesys"+python) has the only result as BEE's file. I have no idea where I can get this and I think you should say something in the readme.

Thanks in advance

**Comment by TeamSpen210** [comment]
You need to download and install the dev branch of my https://github.com/TeamSpen210/srctools repo.

**Comment by sirtomato999** [comment]
Ok thanks. I installed srctools from pypi.
