### ISSUE TITLE
I receive an Error when opening Bee2.4 Pre Release 29 on Windows 8.1.

### ISSUE THREAD

**Issue by Entity447** [BEEmod/BEE2.4#972]
This is the error I get.

cx_Freeze: Python error in main script

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2_launch.pyw", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "F:\Git\BEE2.4\src\BEE2.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "F:\Git\BEE2.4\src\tk_tools.py", line 33, in <module>
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 1863, in wm_iconbitmap
_tkinter.TclError: bitmap "../BEE2.ico" not defined

**Comment by Entity447** [comment]
This error message pops up as a seperate window on my desktop, not in the p2 console.

**Comment by Entity447** [comment]
This error is not in the Portal 2 console, rather it acts as a Windows error and pops up as a seperate tab.

**Comment by Entity447** [comment]
I have also tried using older versions, (PRL27). It does not have this error, instead it will not let me compile my map AT ALL. No matter what I do, It will not let me preview.

**Comment by Entity447** [comment]
Has this been fixed yet??

**Comment by TeamSpen210** [comment]
How would it open in Portal 2, the BEE app has nothing to do with that. And I don't get it, do you actually have the BEE2.ico file? Update to the current version.

**Comment by Entity447** [comment]
I do have the BEE2.ico file. I'll try pre release 30.

**Comment by Entity447** [comment]
Nevermind, it works now. Thank you!
