### ISSUE TITLE
Building map error

### ISSUE THREAD

**Issue by FilziomYT** [BEEmod/BEE2.4#979]
When I click rebuild in my map I get error "There was an error building the puzzle". I've got pr25 and packages from pr29. Error in dev console:
VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr29 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'grating_scale': '0.25', 'voice_pack': 'BEE2_WHEATLEY'}
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/over/items/rex/pellet_dest/head.vmf', 'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/over/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/over/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/over/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/over/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/over/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/over/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/over/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/over/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/over/items/rex/pellet_dest/static_4.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/over/items/rex/pellet_dest/head.vmf', 'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/over/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/over/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/over/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/over/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/over/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/over/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/over/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/over/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/over/items/rex/pellet_dest/static_4.vmf'})
[INFO] cubes.parse_conf(): Parsed 0 cube types, 0 dropper types and 0 addons.
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3477, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 336, in load_settings
  File "F:\Git\BEE2.4\src\cubes.py", line 617, in parse_conf
Exception: Cube type "VALVE_CUBE_STANDARD" is missing!
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3477, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 336, in load_settings
  File "F:\Git\BEE2.4\src\cubes.py", line 617, in parse_conf
Exception: Cube type "VALVE_CUBE_STANDARD" is missing!

Please help me.

**Comment by LautaroL20** [comment]
Make sure your antivirus is not blocking the compiler´s files of Beemod that are located in the "bin" folder inside the Portal 2 game´s directory (i'd suggest to add the whole folder in the exception´s list) because this is also the cause of certain ammount of "building error" issues...

Once you solved any possible conflicts between your antivirus and the game files, then make sure to follow the steps from below:

1 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2 - Wait 1 minute while Beemod removes their resources from Portal 2.

3 - Verify the Game Cache Files. 

4 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise issues will occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application) 
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, or even on 32 Bit versions of Windows, issues can occur. Beemod currently works well only on 64 Bit versions of Windows 7, 8 and 10.

5 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

6 - Now choose your favorite Items & Style and export your palette to the game.

7 - Make sure to save these steps in a text file in case you get similar issues in the future.

8 - Happy mapmaking!

**Comment by FilziomYT** [comment]
1 hour ago bee2.4 in portal 2 was bugget. End when i third time click uninstall from select game my avast antivirus said "Bee2.exe was blocked, name of danger "idp.generic" I add this to quarantine and screen:
![bandicam 2018-08-27 1](https://user-images.githubusercontent.com/42720706/44656730-58b56080-a9fa-11e8-9be7-820714f1b019.jpg)
**Question from me: This files is save or not???**

**Comment by ZombiePwner1** [comment]
@FilziomYT Ignore that message from your anti-virus all anti-virus'es detect bee2 as a virus since it the .exe does the same thing viruses tend to do is 100% safe.

**Comment by FilziomYT** [comment]
txh now works
