### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by TailsXPrower** [BEEmod/BEE2.4#989]
VRAD failed.

[INFO] vrad.main(): BEE2 VRAD hook started!
[INFO] vrad.main(): Map path is D:\Steam\steamapps\common\Portal 2\sdk_content\maps\preview.bsp
[INFO] vrad.load_config(): Loading Settings...
[INFO] vrad.load_config(): Config Loaded!
[INFO] vrad.main(): Final status: is_peti=True, edit_args=True
[INFO] vrad.main(): Reading BSP
[INFO] vrad.main(): Done!
[INFO] vrad.gen_sound_manifest(): Written new soundscripts_manifest..
[INFO] vrad.pack_content(): Files to pack:
[INFO] vrad.pack_content():  # "materials/bee2/clean/black_1x1.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/clean/black_1x2.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/clean/black_ceil.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/tile_noise.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/tile_noise_2x1.vtf"
[INFO] vrad.pack_content():  # "scripts/vscripts/bee2/video_splitter_bsod.nut"
[INFO] vrad.pack_content():  # "sound/music/mel/sp_a4_factory_radio.wav"
[INFO] vrad.pack_content(): Injected files:
[INFO] vrad.pack_content():  # "scripts/game_sounds_manifest.txt"
[INFO] vrad.pack_content():  # "scripts/BEE2_generated_music.txt"
[INFO] vrad.pack_content():  # "scripts/vscripts/bee2/auto_run.nut"
[INFO] vrad.pack_content(): Packing Files!
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\logging\__init__.py", line 989, in emit
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1257.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1148-1155: character maps to <undefined>
Call stack:
  File "F:\Git\BEE2.4\src\utils.py", line 916, in except_handler
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\logging\__init__.py", line 1437, in _log
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\logging\__init__.py", line 1447, in handle
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\logging\__init__.py", line 1509, in callHandlers
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\logging\__init__.py", line 858, in handle
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\logging\handlers.py", line 73, in emit
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\logging\__init__.py", line 1065, in emit
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\logging\__init__.py", line 993, in emit
Message: 'Uncaught Exception:'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\logging\__init__.py", line 989, in emit
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1257.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1148-1155: character maps to <undefined>
Call stack:
  File "F:\Git\BEE2.4\src\utils.py", line 916, in except_handler
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\logging\__init__.py", line 1437, in _log
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\logging\__init__.py", line 1447, in handle
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\logging\__init__.py", line 1509, in callHandlers
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\logging\__init__.py", line 858, in handle
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\logging\handlers.py", line 73, in emit
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\logging\__init__.py", line 1065, in emit
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\logging\__init__.py", line 993, in emit
Message: 'Uncaught Exception:'
Arguments: ()
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vrad.py", line 1022, in <module>
  File "vrad.py", line 1002, in main
  File "vrad.py", line 732, in pack_content
  File "vrad.py", line 344, in get_zip_writer
PermissionError: [WinError 5] \u041e\u0442\u043a\u0430\u0437\u0430\u043d\u043e \u0432 \u0434\u043e\u0441\u0442\u0443\u043f\u0435: 'C:\\Users\\User\\Desktop\\Joel_Nielsen_BMS_Black_Mesa_Theme_Mesa_Remix_(mp3co.biz).mp3'
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vrad.py", line 1022, in <module>
  File "vrad.py", line 1002, in main
  File "vrad.py", line 732, in pack_content
  File "vrad.py", line 344, in get_zip_writer
PermissionError: [WinError 5] \u041e\u0442\u043a\u0430\u0437\u0430\u043d\u043e \u0432 \u0434\u043e\u0441\u0442\u0443\u043f\u0435: 'C:\\Users\\User\\Desktop\\Joel_Nielsen_BMS_Black_Mesa_Theme_Mesa_Remix_(mp3co.biz).mp3'

**Comment by TeamSpen210** [comment]
You really don't want to set the "dump" folder to your desktop, since it will delete everything in there.

**Comment by LautaroL20** [comment]
Try out the latest pre-release.
